OmniSharp/omnisharp-roslyn

- src/OmniSharp/Api/Navigation/OmnisharpController.FindUsages.cs
- tests/OmniSharp.Tests/FindReferencesFacts.cs
Fixed duplicate entries for properties (the getter/setter and backing properties were being returned)
Still unsure if the reference should return it'sself or not.
Added tests for most situations I can think of.
> Find references - Small fix and tests

- src/OmniSharp/Api/Navigation/OmnisharpController.FindUsages.cs
- tests/OmniSharp.Tests/FindReferencesFacts.cs
> code cleanup to satisfy @davidfowl ¬_¬

- src/OmniSharp/Workers/StructureComputer.cs
This is needed for the current build of brackets.
> Changes to the structurecomputer to return locations of the Identifier and not the start of the node

- src/OmniSharp/Api/Structure/OmnisharpController.Members.cs
- src/OmniSharp/Models/FileMemberElement.cs
- src/OmniSharp/Models/Node.cs
- src/OmniSharp/Workers/StructureComputer.cs
- tests/OmniSharp.Tests/StructureFacts.cs
> when computing the outline/structure of a document consider all frameworks

- src/OmniSharp/Services/FileSystemWatcherWrapper.cs
> Removed MONO_MANAGED_WATCHER, polling is bad

- src/OmniSharp/Api/ProjectSystem/OmnisharpController.ProjectSystem.cs
How do people want to start e2e testing? Do we ask people to make sure that this actually works via postman/an editor, this should've been caught pre PR-merge :(
> added FromBody to /projects action

- src/OmniSharp/AspNet5/DesignTimeHostManager.cs
Fixes issue if there is a space in the users home path
> wrap calls to klr in quotes

- src/OmniSharp/project.json
Title says it all :D solves issue #100
> upgraded NR6

- src/OmniSharp/project.json
- tests/OmniSharp.Tests/CodeActionsFacts.cs
> updated NRefactory 6 to alpha 3

- src/OmniSharp/Api/Navigation/OmnisharpController.FindUsages.cs
- src/OmniSharp/Models/FindUsagesRequest.cs
- src/OmniSharp/Models/QuickFix.cs
- src/OmniSharp/Startup.cs
- tests/OmniSharp.Tests/TestHelpers.cs
Right now this fixes the self references issue that @filipw raised, but not the other issues (deduping, listing what projects the references are in, etc..)
> moving branch to master

- src/OmniSharp/Api/Navigation/OmnisharpController.NavigateUpDown.cs
- src/OmniSharp/Models/NavigateResponse.cs
- tests/OmniSharp.Tests/NavigateUpDownFacts.cs
- tests/OmniSharp.Tests/TestHelpers.cs
For https://github.com/OmniSharp/omnisharp-roslyn/issues/97
> Navigate up and down. 

- src/OmniSharp/Api/Navigation/OmnisharpController.FindUsages.cs
- src/OmniSharp/Api/Navigation/OmnisharpController.QuickFixes.cs
- src/OmniSharp/Models/FindUsagesRequest.cs
- src/OmniSharp/Models/QuickFix.cs
- src/OmniSharp/Startup.cs
- tests/OmniSharp.Tests/FindReferencesFacts.cs
- tests/OmniSharp.Tests/TestHelpers.cs
Fixes duplicate usages bug and adds ExcludeDefinition flag for use with Codelens™
> Findreferences

- src/OmniSharp/Api/Navigation/OmnisharpController.FindSymbols.cs
- src/OmniSharp/Extensions/StringExtensions.cs
- src/OmniSharp/Models/FindSymbolsRequest.cs
- tests/OmniSharp.Tests/FindSymbolsFacts.cs
Adds /findsymbols endpoint to return all symbols in the workspace.
> Findsymbols

- src/OmniSharp/AspNet5/AspNet5ProjectSystem.cs
- src/OmniSharp/AspNet5/DesignTimeHostManager.cs
> Added support for yet another rename from k to dnx

- src/OmniSharp/Api/Diagnostics/OmnisharpController.Diagnostics.cs
- src/OmniSharp/Api/Navigation/OmnisharpController.FindSymbols.cs
- src/OmniSharp/Models/DiagnosticLocation.cs
- src/OmniSharp/Models/QuickFix.cs
- src/OmniSharp/Models/SymbolLocation.cs
- src/OmniSharp/Workers/Intellisense/SnippetGenerator.cs
- tests/OmniSharp.Tests/FindSymbolsFacts.cs
Adds the symbol kind to /findsymbols and added DiagnosticsLocation class
> Adds the symbol kind to /findsymbols

- README.md
- appveyor.yml
- build.cmd
So... this seems like a good start. It's not perfect, but it's on a par with our Travis CI build for linux I think.
> Create an Appveyor CI build

- src/OmniSharp/Api/Navigation/OmnisharpController.FindSymbols.cs
- tests/OmniSharp.Tests/FindSymbolsFacts.cs
> Removes event keyword from find symbols

- build.sh
- tests/OmniSharp.Stdio.Tests/project.json
- tests/OmniSharp.Tests/project.json
> update to aspnet.xunit

- src/OmniSharp/Api/Intellisense/OmnisharpController.Intellisense.cs
- src/OmniSharp/Api/Navigation/OmnisharpController.FindSymbols.cs
- src/OmniSharp/Extensions/SymbolExtensions.cs
- tests/OmniSharp.Tests/FindSymbolsFacts.cs
> distinguish between interfaces, classes etc for Named Types

- NuGet.Config
- omnisharp.json
- src/OmniSharp/AspNet5/AspNet5Context.cs
- src/OmniSharp/AspNet5/AspNet5Paths.cs
- src/OmniSharp/AspNet5/AspNet5ProjectSystem.cs
- src/OmniSharp/Options/AspNet5Options.cs
- src/OmniSharp/Services/IOmnisharpEnvironment.cs
- src/OmniSharp/Services/OmnisharpEnvironment.cs
- src/OmniSharp/Startup.cs
- src/OmniSharp/config.json
- src/OmniSharp/project.json
- Added default globbing patterns for scanning for project.json
files.
- Added per solution configuraiton for omnisharp via omnisharp.json
- Added ConfigurationFilePath to IOmnisharpEnvironment
- Added latest FileSystemGlobbing library
> Changed how we scan for projects for project.json

- src/OmniSharp/Api/Intellisense/OmnisharpController.Intellisense.cs
- src/OmniSharp/Api/Types/OmnisharpController.TypeLookup.cs
- src/OmniSharp/Roslyn/XmlDocumentationProvider.cs
- src/OmniSharp/Services/DocumentationConverter.cs
- tests/OmniSharp.Tests/DocumentationConverterFacts.cs
OK. This might work. Haven't tested it for reals yet ;)
> Plain text docs

- src/OmniSharp/MSBuild/MSBuildLogForwarder.cs
- src/OmniSharp/MSBuild/MSBuildLogger.cs
- src/OmniSharp/MSBuild/MSBuildProjectSystem.cs
- src/OmniSharp/MSBuild/ProjectFile/ProjectFileInfo.cs
- src/OmniSharp/Models/EventTypes.cs
- src/OmniSharp/Models/MSBuildDiagnosticsMessage.cs
- src/OmniSharp/Models/MSBuildProjectDiagnostics.cs
adds log forwards of warnings and errors for the MSBuild project system and emit project diagnostics messages to editors
> add logging for MSBuild project system

- src/OmniSharp/AspNet5/PackagesRestoreTool.cs
On mono you often and on windows you sometimes see dnu restore (or kpm restore) hanging forever. This PR adds a watchdog that kills the restore command if no progress was reported for >20 seconds. Then it will try one more time.
> add a watchdog that kills stuck dnu|kpm restore processes

- src/OmniSharp/AspNet5/AspNet5ProjectSystem.cs
- When project.lock.json files change, refresh dependencies
in the DTH. This will allow a workflow where package restore
can happen outside of the editor but the editor can still reflect
those changes that were made.
- Made some fixes where files weren't being watched for project references that were outside of the initially scanned projects.
Fixes #189
> Added support for watching project.lock.json files

- src/OmniSharp/MSBuild/MSBuildProjectSystem.cs
- src/OmniSharp/MSBuild/ProjectFile/ProjectFileInfo.cs
- src/OmniSharp/Options/MSBuildOptions.cs
- src/OmniSharp/Options/OmniSharpOptions.cs
Allow msbuild based projects to set the tools version (msbuild tools verson) and the visual studio version.
> Act like VS

- src/OmniSharp/Api/Navigation/OmnisharpController.GotoDefinition.cs
- src/OmniSharp/Api/Navigation/OmnisharpController.GotoFile.cs
- tests/OmniSharp.Tests/GoToFileFacts.cs
Returns a list of all files in the current workspace - same as the functionality in omnisharp-server.
> Added gotofile endpoint

- src/OmniSharp/Api/Navigation/OmnisharpController.GotoRegion.cs
- tests/OmniSharp.Tests/FindImplementationFacts.cs
- tests/OmniSharp.Tests/GoToRegionFacts.cs
This returns all regions and endregions in a file, on par with the functionality in omnisharp-server.
> Added gotoregion endpoint

- src/OmniSharp/MSBuild/MSBuildProjectSystem.cs
- src/OmniSharp/MSBuild/ProjectFile/ProjectFileInfo.cs
Builds OK, but new functionality is untested as installing Visual Studio 5 RC messed things a little bit...
> Support LangVersion property on csproj

- src/OmniSharp/Api/Refactoring/OmnisharpController.Rename.cs
- src/OmniSharp/Models/LinePositionSpanTextChange.cs
- tests/OmniSharp.Tests/RenameFacts.cs
> deduplicating renames

- src/OmniSharp/MSBuild/ProjectFile/ProjectFileInfo.cs
- src/OmniSharp/project.json
Fixes https://github.com/OmniSharp/omnisharp-atom/issues/325
> Fixes msbuild loading when LangVersion is missing

- src/OmniSharp/Startup.cs
Phew! Just had to do that before continuing my talk!
> Added line break!

- src/OmniSharp/Api/v1/ProjectSystem/OmnisharpController.ProjectSystem.cs
- src/OmniSharp/Models/v1/MsBuildWorkspaceInformation.cs
- src/OmniSharp/Models/v1/ProjectInformationRequest.cs
Hi
This PR relates to https://github.com/OmniSharp/omnisharp-server/pull/202
We need to exclude the project files from the response as they are not used by the clients.
> Added new parameter to allow excluding project files from response.

- build.cmd
> change feed url variable to DNX_FEED

- src/OmniSharp/Models/v1/DnxFramework.cs
- src/OmniSharp/Models/v1/DnxProject.cs
Removes extra framework property added in #259
> removed redundant dnx project property

- src/OmniSharp/Dnx/DesignTimeHostManager.cs
- tests/OmniSharp.Tests/DiagnosticsFacts.cs
Try to fix tests on appveyor from #281
> Alxandr master

- src/OmniSharp/Api/v1/Buffer/OmnisharpController.Buffer.cs
- src/OmniSharp/Models/v1/UpdateBufferRequest.cs
- src/OmniSharp/Roslyn/BufferManager.cs
- tests/OmniSharp.Tests/BufferManagerFacts.cs
- tests/OmniSharp.Tests/FindImplementationFacts.cs
- tests/OmniSharp.Tests/FindReferencesFacts.cs
- tests/OmniSharp.Tests/FindSymbolsFacts.cs
- tests/OmniSharp.Tests/GoToFileFacts.cs
- tests/OmniSharp.Tests/GoToRegionFacts.cs
- tests/OmniSharp.Tests/HighlightFacts.cs
- tests/OmniSharp.Tests/IntellisenseFacts.cs
- tests/OmniSharp.Tests/NavigateUpDownFacts.cs
- tests/OmniSharp.Tests/OmnisharpControllerFacts.cs
- tests/OmniSharp.Tests/RenameFacts.cs
- tests/OmniSharp.Tests/SignatureHelpFacts.cs
- tests/OmniSharp.Tests/SnippetFacts.cs
- tests/OmniSharp.Tests/TestHelpers.cs
- tests/OmniSharp.Tests/TypeLookupFacts.cs
I need this in emacs when a buffer is reverted from disk. I don't get any file changed events and just need the server to have the same version of the file.
> Add flag to allow update buffer to read from disk

- src/OmniSharp/MSBuild/MSBuildProjectSystem.cs
- src/OmniSharp/MSBuild/ProjectFile/ProjectFileInfo.cs
Fixed according to comment at bug #265.
> Fix for - Lots of mscorlib issues with 3rd party packages #265

- src/OmniSharp/Extensions/StringExtensions.cs
Phew! I just had to do that before continuing with my talk!
Thanks to my audience at DevDay!
> added missing braces

- src/OmniSharp/Workers/Refactoring/FixUsings.cs
For #305. Moving ambiguous using check after add/remove usings.
> Moving ambiguous check to be after add/remove usings

- src/OmniSharp/MSBuild/MSBuildProjectSystem.cs
- src/OmniSharp/MSBuild/ProjectFile/ProjectFileInfo.cs
> Respect AllowUnsafe

- src/OmniSharp/MSBuild/ProjectFile/ProjectFileInfo.cs
> don't expect AllowUnsafeBlocks and DefineConstants to be in all csproj files

- src/OmniSharp/Extensions/StringExtensions.cs
Inspired by @adamralph DevDay talk
> Added missing space

- NuGet.Config
- README.md
- build.cmd
- build.sh
- scripts/Bootstrap
- scripts/Bootstrap-coreclr.cmd
- scripts/Bootstrap.cmd
- scripts/Omnisharp
- scripts/Omnisharp-coreclr.cmd
- scripts/Omnisharp.cmd
> Switch back to aspnetcidev feed

- build.cmd
- build.sh
- src/OmniSharp.Abstractions/project.json
- src/OmniSharp.Bootstrap/project.json
- src/OmniSharp.Dnx/project.json
- src/OmniSharp.Host/Startup.cs
- src/OmniSharp.Host/project.json
- src/OmniSharp.MSBuild/project.json
- src/OmniSharp.Roslyn.CSharp/CodeActions/RoslynCodeActionProvider.cs
- src/OmniSharp.Roslyn/MetadataHelper.cs
- src/OmniSharp.Roslyn/Services/AbstractCodeActionProvider.cs
- src/OmniSharp.Roslyn/project.json
- src/OmniSharp.Stdio/Logging/StdioLogger.cs
- src/OmniSharp.Stdio/project.json
- tests/OmniSharp.Bootstrap.Tests/project.json
- tests/OmniSharp.Plugins.Tests/project.json
- tests/OmniSharp.Tests/EndpointMiddlewareFacts.cs
- tests/OmniSharp.Tests/Fakes/FakeLogger.cs
> Update dependencies and DNX

- README.md
Just some minor little spelling and grammatical changes to make it read a bit better that I noticed in the readme.
> Minor spelling and grammatical changes for readme.md

- build.sh
https://github.com/dotnet/cli/issues/531 is fixed
> Stop setting the DOTNET_REFERENCE_ASSEMBLIES_PATH

- src/OmniSharp.Host/Startup.cs
Returns the error message from project system initialization.
> Correctly log exception during project system initialization

- src/OmniSharp.DotNet/Tools/ProjectContextLens.cs
> Add source file references

- src/OmniSharp.DotNet/Models/DotNetProjectInformation.cs
Two new properties:
1. TargetFramework
2. EmitEntryPoint
cc @troydai
> Add more properties to DotNetProjectInformation

- src/OmniSharp.DotNet/DotNetProjectSystem.cs
- src/OmniSharp.DotNet/Tools/SnkUtils.cs
/cc @DustinCampbell @davidfowl 
#445
> Apply keyfile to compilation options

- .travis.yml
- appveyor.yml
- build.cake
Uses `-archive` on CI, but skips archiving by default for faster local builds.
> New option to skip archiving by default.

- build.cake
Based on clarifications in https://github.com/cake-build/cake/issues/769
> Fix install path for individual frameworks.

- omnisharp.json
> Disable package restore

- .gitignore
Just added `.vscode` folder into ignore list.
> Adding .vscode/settings.json into .gitignore

- .travis.yml
- build.cake
- src/OmniSharp.MSBuild/MSBuildLogForwarder.cs
- src/OmniSharp.MSBuild/MSBuildProjectSystem.cs
- src/OmniSharp.MSBuild/ProjectFile/ProjectFileInfo.cs
- src/OmniSharp.Nuget/OmniSharpSourceRepositoryProvider.cs
- src/OmniSharp.Nuget/Services/PackageSearchService.cs
- src/OmniSharp.Nuget/Services/PackageSourceService.cs
- src/OmniSharp.Nuget/Services/PackageVersionService.cs
- src/OmniSharp.Roslyn.CSharp/Workers/Refactoring/FixUsings.cs
> Quickfixes for release

- .lgtm
- MAINTAINERS
https://lgtm.co/
The idea of this is pretty cool, just adds another check to make sure things are ready to merge.  Thoughts?
cc @DustinCampbell @troydai @hal-ler
> add maintainers for https://lgtm.co/

- src/OmniSharp.Roslyn/ProjectEventForwarder.cs
phew! Just had to do that before continuing my talk at Code Forward!
Thanks to my audience for their patience.
> fixed braces

- src/OmniSharp.MSBuild/ProjectFile/ProjectFileInfo.cs
React to:
https://github.com/aspnet/Announcements/issues/191
https://github.com/aspnet/PlatformAbstractions/issues/46
https://github.com/aspnet/PlatformAbstractions/pull/45
> react to runtime changes

- src/OmniSharp.Abstractions/project.json
- src/OmniSharp.DotNet/project.json
- src/OmniSharp.DotNetTest/Helpers/ProjectPathResolver.cs
- src/OmniSharp.MSBuild/project.json
- src/OmniSharp.Plugins/project.json
- src/OmniSharp.Roslyn.CSharp/project.json
- src/OmniSharp.Roslyn/project.json
- tests/OmniSharp.MSBuild.Tests/project.json
- tests/OmniSharp.Roslyn.CSharp.Tests/project.json
- tests/OmniSharp.Tests/project.json
- tests/TestUtility/project.json
Address:
- https://github.com/omnisharp/omnisharp-vscode/issues/453
- https://github.com/OmniSharp/omnisharp-roslyn/issues/587
> Fix incorrect project path resolver

- .travis.yml
- src/OmniSharp.Abstractions/Models/v1/CodeFormatRequest.cs
- src/OmniSharp.Abstractions/Models/v1/CodeFormatResponse.cs
- src/OmniSharp.Roslyn.CSharp/Services/Formatting/CodeFormatService.cs
- src/OmniSharp.Roslyn.CSharp/Workers/Format/Formatting.cs
To opt in pass WantChanges=true.
This is a change to better be able to support the language server protocol.
> Added support for text changes to codeformat endpoint.  

- MAINTAINERS
https://lgtm.co/docs/maintainers/
> Removed MAINTAINERS in favor of Maintainers team under OmniSharp org

- src/OmniSharp.Abstractions/Options/FormattingOptions.cs
- src/OmniSharp.Roslyn.CSharp/Workers/Formating/FormattingWorker.cs
> Added Roslyn CSharp code formatting options to omnisharp.json.

- src/OmniSharp.Script/ScriptProjectSystem.cs
This PR resolved the issue found in #682
> Default to non-context path if context is null

- src/OmniSharp.Script/FileParser.cs
This PR ensures that relative `#r` references in scripts are correctly resolved (normalized to absolute paths) 
So far we only resolved them correctly if they were absolute or if the script was directly located in the working directory for omnisharp (the folder where `project.json` is). This was already done for `#load` before.
> correctly resolve relative #r

- src/OmniSharp.Roslyn.CSharp/Services/Types/TypeLookup.cs
- src/OmniSharp.Script/FileParser.cs
- src/OmniSharp.Script/ScriptContext.cs
- src/OmniSharp.Script/ScriptProjectSystem.cs
Merge latest bits into the new-msbuild branch
> Merge dev into new msbuild

- src/OmniSharp.MSBuild/ProjectFile/ProjectFileInfo.cs
This will ultimately address https://github.com/OmniSharp/omnisharp-vscode/issues/1049.
> Don't add duplicate source files to project

- src/OmniSharp.Host/Program.cs
See https://github.com/OmniSharp/omnisharp-vscode/pull/1169#discussion_r98970819
> loglevel should be a "--" argument

- src/OmniSharp.Roslyn.CSharp/Services/Refactoring/V2/BaseCodeActionService.cs
> Only show the remove unnecessary usings code fix for the appropriate diagnostic

- src/OmniSharp.Abstractions/Utilities/PlatformHelper.cs
Fixes https://github.com/OmniSharp/omnisharp-vscode/issues/1031
> When detecting Mono location, run shell commands specifically on bash

- src/OmniSharp.DotNet/DotNetProjectSystem.cs
Fixes https://github.com/OmniSharp/omnisharp-vscode/issues/1221
> Make sure we specify an AssemblyIdentityCompare in project.json project system

- .travis.yml
- NuGet.Config
- build.cake
- scripts/common.cake
- scripts/runhelpers.cake
Output build log on failure and clean up publish target a bit.
> Improve build

- src/OmniSharp.MSBuild/MSBuildProjectSystem.cs
This was causing solution files not to load properly on *Nix.
> Add back code to handle project paths within a solultion file correctly

- build.json
- src/OmniSharp.Abstractions/Configuration.cs
- src/OmniSharp.Abstractions/OmniSharp.Abstractions.csproj
- src/OmniSharp.DotNet/OmniSharp.DotNet.csproj
- src/OmniSharp.DotNetTest/OmniSharp.DotNetTest.csproj
- src/OmniSharp.MSBuild/OmniSharp.MSBuild.csproj
- src/OmniSharp.Roslyn.CSharp/OmniSharp.Roslyn.CSharp.csproj
- src/OmniSharp.Roslyn/OmniSharp.Roslyn.csproj
- src/OmniSharp.Script/OmniSharp.Script.csproj
- src/OmniSharp/app.config
- tests/OmniSharp.Stdio.Tests/OmniSharp.Stdio.Tests.csproj
- tests/TestUtility/TestUtility.csproj
- tests/app.config
- tools/packages.config
These are the latest packages available on nuget.org. I'm expecting that this will fix #865.
> Update to latest MSBuild, NuGet and Roslyn packages

- README.md
Just a small readme update in the `VS Code` section.
> Added a note about debugging against VS Code

- src/OmniSharp/app.config
- tests/app.config
> updated binding redirects to Roslyn 2.3.0

- src/OmniSharp.Abstractions/Services/DotNetCliService.cs
The CLI does not yet check this environment variable, but it will soon (https://github.com/dotnet/cli/pull/7021) as part of the effort to localize the CLI output.
> Set DOTNET_CLI_UI_LANGUAGE environment variable to 'en-US' when calling 'dotnet --info'

- CHANGELOG.md
- README.md
> Update changelog and README

- CHANGELOG.md
- src/OmniSharp.MSBuild/ProjectFile/ProjectFileInfo.ProjectData.cs
- test-assets/test-projects/HelloWorld/HelloWorld.csproj
- tests/OmniSharp.MSBuild.Tests/ProjectFileInfoTests.cs
we assigned the property to itself instead of the parameter 😄
Fixes #961
> fixed LanguageVersion assignment

- src/OmniSharp.Http/Host.cs
Configured Urls as per https://docs.microsoft.com/en-us/aspnet/core/fundamentals/hosting?tabs=aspnetcore2x
Fixed issue where the host URL was defaulting to 5000 regardless of the port number being passed in the parameters.
> Added UseUrls method

- src/OmniSharp.LanguageServerProtocol/Handlers/CompletionHandler.cs
- src/OmniSharp.LanguageServerProtocol/LanguageServerHost.cs
ping @david-driscoll 
Still needs some fine-tuning, but does the job.
> Adds CompletionHandler.

- src/OmniSharp.LanguageServerProtocol/Handlers/SignatureHelpHandler.cs
- src/OmniSharp.LanguageServerProtocol/LanguageServerHost.cs
This pull request adds SignatureHelpHandler to #968
> Adds SignatureHelpHandler

- src/OmniSharp.Script/ScriptProjectSystem.cs
> use MetadataReferenceEqualityComparer in scripting

- appveyor.yml
> Add encrypted connection string for blob storage

- CHANGELOG.md
- src/OmniSharp.Cake/CakeProjectSystem.cs
- tests/OmniSharp.Cake.Tests/CakeProjectSystemFacts.cs
Builds upon PR #1053. (Merge that first, and then rebase this...)
Add created `.cake` files to workspace and remove deleted `.cake` files from workspace.
>  Watch .cake files and add/remove files in workspace.

- appveyor.yml
> Replace connection string with storage key

- src/OmniSharp.LanguageServerProtocol/Handlers/DocumentSymbolHandler.cs
- src/OmniSharp.LanguageServerProtocol/LanguageServerHost.cs
> Add DocumentSymbolHandler

- appveyor.yml
> Update storage key

- .travis.yml
> Add secure variable BLOB_KEY

- src/OmniSharp.Roslyn/Utilities/TextChangeHelper.cs
As featured in _git commit -m "fix whitespace"_ at [PubConf](https://pubconf.io/) after NDC London 2018.
> add a blank line between blocks

- .travis.yml
> Add storage key to travis.yml

- .travis.yml
- scripts/archiving.cake
Required by the C# Extension for VS Code, which only knows how to download zip files.
> Create a ZIP archive on all platforms

- scripts/archiving.cake
Create versionInfo file so it can be used by vscode downloader to determine what version to use.
> Write out versionInfo file

- tests/OmniSharp.Roslyn.CSharp.Tests/SignatureHelpFacts.cs
Similar PR to https://github.com/OmniSharp/omnisharp-roslyn/pull/831
I also added 1 CSX specific test (global, class-less extension method signature).
> run SignatureHelpFacts for CSX too

- CHANGELOG.md
> Change log updates

- src/OmniSharp.Cake/Extensions/ResponseExtensions.cs
- src/OmniSharp.Cake/Services/RequestHandlers/Refactoring/RenameHandler.cs
- tests/OmniSharp.Cake.Tests/RenameFacts.cs
Add RenameHandler for Cake to support Rename requests.
> Add RenameHandler for Cake

- CHANGELOG.md
It was missing from the changelog
> added a note about script RSP support to a CHANGELOG.md

- build.cake
> Fixtypo in build.cake script

- .travis.yml
Updates to the latest directions from https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-apt?view=azure-cli-latest#signingKey
> Use latest az tools installation methodology

- CHANGELOG.md
> Update changelog.md for blockstructure

- CHANGELOG.md
- src/OmniSharp.Cake/Extensions/ResponseExtensions.cs
- src/OmniSharp.Cake/Services/RequestHandlers/Diagnostics/CodeCheckHandler.cs
- src/OmniSharp.Cake/Services/RequestHandlers/Navigation/FindUsagesHandler.cs
- tests/OmniSharp.Cake.Tests/FindUsagesFacts.cs
> GH1204: Only return usages from current file if OnlyThisFile is true

- src/OmniSharp.Abstractions/Models/v1/AutoComplete/AutoCompleteResponse.cs
- src/OmniSharp.Roslyn.CSharp/Services/Intellisense/IntellisenseService.cs
- tests/OmniSharp.Roslyn.CSharp.Tests/IntellisenseFacts.cs
Issue: https://github.com/OmniSharp/omnisharp-vscode/issues/1898
To enable preselect in completion service.
cc @rchande @DustinCampbell
> Add preselect property to autocomplete repsonse

- README.md
OmniSharp/omnisharp-vscode#2151
> add msbuild_stable to requires

- build/Packages.props
- tools/packages.config
> Update xUnit to 2.4.0 release

- CHANGELOG.md
Somehow, it was forgotten to get a mention.
> Added a changelog note about net461

- scripts/common.cake
cc @rchande @akshita31 @mholo65 @gep13
> pinned gitversion

- OmniSharp.sln
- build/Packages.props
- src/OmniSharp.Abstractions/Configuration.cs
- src/OmniSharp.Http.Driver/app.config
- src/OmniSharp.Stdio.Driver/app.config
- tests/app.config
- tools/packages.config
This change updates the package versions for Roslyn, MSBuild and NuGet releases.
> Update Roslyn, MSBuild and NuGet

- src/OmniSharp.DotNetTest/VSTestManager.cs
I have encountered strange behaviour when running omnisharp-roslyn tests using test lens in vscode:
- "Run test" on a single method would execute the test, but it would never display final results (Total tests: 0)
- "Run All Tests" would not discover all tests in the class (ex in ZeroBasedIndexConverterFacts.cs it would consistently run only 15 out of 19 tests). 4 tests missing from discovery are not runnable by "Run Test"
Turns out VSTest by protocol sends last bits of run/discovered test inside "LastRunTestResults"/ "LastDiscoveredTests" messages. This is done for optimization reasons https://github.com/Microsoft/vstest/issues/399. VSTestManager in o# doesn't handle this - I've found missing bits of information in completition payloads. PR adds code to handle those messages fully. …
> Fix missing test results/discoveries when tests are run with vscode's TestCodeLens

- .travis.yml
These are uploaded by AppVeyor builds
> Don't check for Windows builds when uploading blob

- CHANGELOG.md
> one more changelog update for 1.32.7

- src/OmniSharp.Host/MSBuild/Discovery/Providers/DevConsoleInstanceProvider.cs
> Fix devconsole MSBuild discovery

- CHANGELOG.md
- build/Packages.props
- src/OmniSharp.Abstractions/Configuration.cs
- src/OmniSharp.Http.Driver/app.config
- src/OmniSharp.Stdio.Driver/app.config
- tests/app.config
- tools/packages.config
Housekeeping PR.
Also filled in the missing stuff in the changelog.
> updated to Roslyn 2.10.0

- build.cake
MIT license should be embedded into the distributed artifacts/builds.
Fixes #1352
> include MIT license in build artifacts

- CHANGELOG.md
> added missing LSP note to CHANGELOG.md

- src/OmniSharp.LanguageServerProtocol/Handlers/ReferencesHandler.cs
- src/OmniSharp.LanguageServerProtocol/LanguageServerHost.cs
- Maps FindUsagesService
ping @david-driscoll
> Add ReferencesHandler

- build.cake
> fixed appveyor / travis publish with gitversion

- .travis.yml
This will let linux/osx releases succeed--see the bottom of this log for context https://api.travis-ci.org/v3/job/514412325/log.txt
> Suppress errors from rm when deleting build artifacts

- CHANGELOG.md
Some housekeeping after recent merges
> updated changelog with latest fixes and features

- build/Packages.props
- src/OmniSharp.Abstractions/Configuration.cs
- src/OmniSharp.Http.Driver/app.config
- src/OmniSharp.Roslyn.CSharp/Services/Refactoring/V2/RunCodeActionService.cs
- src/OmniSharp.Roslyn/MetadataHelper.cs
- src/OmniSharp.Script/ScriptProjectProvider.cs
- src/OmniSharp.Stdio.Driver/app.config
- tests/OmniSharp.Roslyn.CSharp.Tests/CodeActionsV2Facts.cs
- tests/app.config
We can take this in already, or we can wait a bit until there is an official dev16.1 preview, however I wanted to do the necessary changes to make use 3.1 compatible.
There is some reflection that goes away, and a few changes we needed to make to adapt our existing reflection 😀
> Updated to Roslyn 3.1

- CHANGELOG.md
> Changlog update for 1.32.13 - through to 1.32.16

- GitVersion.yml
- azure-pipelines.yml
- scripts/common.cake
Note, only updating GitVersion solved the issue, but after discussing with @gep13 the changes I made to the config also makes sense. Only updating config didn't work (seems to be a bug in v4 of GitVersion regarding merge-commits).
> Update gitversion and tweak config to avoid version increments from merge commits

- src/OmniSharp.Http.Driver/app.config
- src/OmniSharp.Stdio.Driver/app.config
> correctly set 4.7.2 as framework sku in app.config

- GitVersion.yml
@rchande @mholo65 @filipw this should get us back to a sane version number
> ignore shas creating incorrect version numbers

- .travis.yml
- appveyor.yml
This will only ever upload omnisharp binaries to the storage account from azure pipelines, which will only ever happen when all 3 builds succeed.
cc @rchande @filipw
> only upload from azure pipelines

- build/Packages.props
> Update LSP libs

- CHANGELOG.md
- build/Packages.props
see https://github.com/dotnet/versions/tree/master/build-info/dotnet/roslyn/dev16.1
> updated to Roslyn 3.1.0 beta4-19266-03 to match dev16.1

- CHANGELOG.md
> changelog updates for 1.32.20

- build.cake
This should have been removed in #1534 as it's no longer used.
> removed unused build code

- CHANGELOG.md
Includes the missing description for all the recent PR merges
> changelog updates for 1.34.0

- tests/OmniSharp.Roslyn.CSharp.Tests/CodeActionsV2Facts.cs
- tests/OmniSharp.Script.Tests/WorkspaceInformationTests.cs
- tests/TestUtility/AbstractCodeActionsTestFixture.cs
- tests/TestUtility/AbstractTestFixture.cs
- tests/TestUtility/SharedOmniSharpHostFixture.cs
- tests/TestUtility/TestHelpers.cs
Hello.
Some of unit tests don't work in my area.
So we added the function to set the default culture.
However, this may not be the best as not all test classes inherit AbstractTestFixture.
Are there any other good ideas?
> Unit test support in non-English countries.

- CHANGELOG.md
The existing release notes were not complete.
I will self-merge it, because there is not much to review here 😀
> changelog updates for 1.34.1

- .gitignore
- build.json
- test-assets/test-projects/ProjectWithComplexAnalyzers/Program.cs
- test-assets/test-projects/ProjectWithComplexAnalyzers/ProjectWithComplexAnalyzers.csproj
- tests/OmniSharp.MSBuild.Tests/ProjectWithAnalyzersTests.cs
- tests/OmniSharp.MSBuild.Tests/ProjectWithComplexAnalyzersTests.cs
Adds a test for #1566 
This test fails without the changes from that PR and passes now. Will help us not regress on this.
> test for #1566 

- CHANGELOG.md
follow up to #1597 where we forgot about it 😀
> added Roslyn 3.4 to the changelog

- omnisharp.json
project.json is no longer supported - #1539
> removed dotnet node from omnisharp.json

- CHANGELOG.md
> update changelog for 1.34.4

- CONTRIBUTING.md
> removed jabbr link from CONTRIBUTING.md

- omnisharp.json
- test-assets/test-scripts/DotnetCoreScriptSimple/main.csx
- test-assets/test-scripts/DotnetCoreScriptWithNuget/main.csx
- tests/OmniSharp.Script.Tests/WorkspaceInformationTests.cs
> moved scripting tests and test assets to .NET Core 3.0

- src/OmniSharp.Roslyn.CSharp/Services/Navigation/FindSymbolsService.cs
> removed project.json left over from symbol finder

- CHANGELOG.md
> added #1656 to the changelog

- CHANGELOG.md
> added #1672 to changelog

- CHANGELOG.md
I forgot to add it as part of #1686
> #1686 in the changelog

- azure-pipelines.yml
> Build on Catalina (macOS-10.15)

- src/OmniSharp.Roslyn.CSharp/Services/Decompilation/DecompilationExternalSourceService.cs
removed misleading comment that was not removed during refactoring
> removed invalid comment

- build/Packages.props
- tests/OmniSharp.Roslyn.CSharp.Tests/ImplementTypeFacts.cs
Updates to roughly match the VS 16.6 Preview 5.
> Update Roslyn to 3.6.0-4.20228.5

- CHANGELOG.md
- src/OmniSharp.MSBuild/ProjectFile/ProjectFileInfo.ProjectData.cs
- src/OmniSharp.MSBuild/ProjectFile/ProjectFileInfo.cs
- src/OmniSharp.MSBuild/ProjectFile/ProjectFileInfoExtensions.cs
- src/OmniSharp.MSBuild/ProjectFile/PropertyNames.cs
- test-assets/test-projects/WarningsAsErrors/WarningsAsErrors.csproj
- tests/OmniSharp.MSBuild.Tests/ProjectFileInfoTests.cs
> added support for WarningsNotAsErrors msbuild property

- tests/OmniSharp.Roslyn.CSharp.Tests/SemanticHighlightFacts.cs
cases take from here https://github.com/OmniSharp/omnisharp-roslyn/issues/1786
> added two cases to semantic highlighting tests

- build.json
- test-assets/test-projects/Net50Project/global.json
we should test using latest preview SDK
> updated the .net 5.0 sdk used for tests

- CHANGELOG.md
> added semantic highlighting endpoint to the changelog

- build/Packages.props
the currently used one is over 2 years old
> updated the .NET Test SDK to 16.6

- build/Packages.props
- src/OmniSharp.Host/WorkspaceInitializer.cs
- src/OmniSharp.Shared/Options/OmniSharpOptions.cs
when logging is set to DEBUG we now dump a serialized value of `OmniSharpOptions` - both at startup and on every change (since we run watchers when options change).
This can be very helpful in troubleshooting, debugging and solving problems.
Example:
```
[dbug]: OmniSharp.WorkspaceInitializer
Starting with OmniSharp options: {"RoslynExtensionsOptions":{"EnableDecompilationSupport":true,"EnableAnalyzersSupport":true,"DocumentAnalysisTimeoutMs":10000,"LocationPaths":["c:\\code\\roslynator"]},"FormattingOptions":{"OrganizeImports":true,"EnableEditorConfigSupport":true,"NewLine":"\n","UseTabs":false,"TabSize":4,"IndentationSize":4,"SpacingAfterMethodDeclarationName":false,"SpaceWithinMethodDeclarationParenthesis":false,"SpaceBetweenEmptyMethodDeclarationParentheses":false,"SpaceAfterMethodCall …
```
> Added dump of OmniSharp options at debug level

- build/Packages.props
- src/OmniSharp.Host/Services/OmniSharpEnvironment.cs
We released 0.52 over a month ago to better support .net core 3.1 scripts https://github.com/filipw/dotnet-script/releases/tag/0.52.0
> updated dotnet script packages to 0.53.0

- src/OmniSharp.Abstractions/Eventing/IEventEmitterExtensions.cs
- src/OmniSharp.Abstractions/Models/Events/ProjectConfigurationMessage.cs
- src/OmniSharp.MSBuild/Notification/ProjectLoadedEventArgs.cs
- src/OmniSharp.MSBuild/ProjectFile/ItemNames.cs
- src/OmniSharp.MSBuild/ProjectFile/ProjectFileInfo.cs
- src/OmniSharp.MSBuild/ProjectLoadListener.cs
- src/OmniSharp.MSBuild/ProjectManager.cs
- src/OmniSharp.MSBuild/ProjectSystem.cs
- tests/OmniSharp.MSBuild.Tests/ProjectFileInfoTests.cs
- tests/OmniSharp.MSBuild.Tests/ProjectLoadListenerTests.cs
The server-side work for https://github.com/OmniSharp/omnisharp-vscode/issues/3577
> Add more ProjectConfiguration information

- build.json
- test-assets/test-projects/Net50Project/global.json
- tests/OmniSharp.MSBuild.Tests/ProjectLoadListenerTests.cs
preview 5 was released last week.
> updated tests to dotnet SDK 5.0.100-preview.5

- CHANGELOG.md
> fixed changelog typos

- BUILD.md
build documentation file is out of date
> updated minimum versions in build documentation

- CHANGELOG.md
- build/Packages.props
- src/OmniSharp.Abstractions/Configuration.cs
- src/OmniSharp.Http.Driver/app.config
- src/OmniSharp.Stdio.Driver/app.config
- tests/app.config
This is from the 16.8 release train already.
> updated to Roslyn 3.8.0-1.20357.3

- CHANGELOG.md
- src/OmniSharp.LanguageServerProtocol/Handlers/OmniSharpCompletionHandler.cs
> fixed return type condition in LSP completions

- BUILD.md
- README.md
- build.cake
- build.cmd
- scripts/common.cake
- scripts/platform.cake
- src/OmniSharp.Http.Driver/OmniSharp.Http.Driver.csproj
- src/OmniSharp.LanguageServerProtocol/OmniSharp.LanguageServerProtocol.csproj
- src/OmniSharp.Stdio.Driver/OmniSharp.Stdio.Driver.csproj
- tools/packages.config
This would make it possible to preview the language service experience on Windows Arm64 devices.
> Build Windows Arm64 package

- README.md
> Mono versions update in the readme

- src/OmniSharp.LanguageServerProtocol/Handlers/OmniSharpCompletionHandler.cs
> fixed LSP completion item kinds

- CHANGELOG.md
> final changelog update for the release

- CHANGELOG.md
we forgot the entry about package bump for  .NET Core 5.0 RC2
I will self merge  it as there is nothing to review
> missed entry in changelog

- .gitignore
- src/OmniSharp.Host/Endpoint/EndpointHandler.cs
- src/OmniSharp.LanguageServerProtocol/LanguageProtocolInteropHandler.cs
- src/OmniSharp.Roslyn.CSharp/Services/Refactoring/V2/BaseCodeActionService.cs
- src/OmniSharp.Roslyn/WorkspaceServices/ExportWorkspaceServiceFactoryWithAssemblyQualifiedNameAttribute.cs
- src/OmniSharp.Script/ScriptProjectProvider.cs
When generating MSBuild binary logs for debugging purposes, they show up in files to be committed.
Additionally, I fixed some typos in the comments that I noticed today.
> added .binlog to .gitignore

- src/OmniSharp.LanguageServerProtocol/LanguageServerHost.cs
- test-assets/test-projects/ExternAlias/ExternAlias.App/ExternAlias.App.csproj
> Register languageServer as ILanguageServerFacade

- build.cake
This speeds up local development loop. The storage account is slow and on for me it speeds up the quick build by roughly 30s.
> do not download mono assets if they already exist (unless running full build)

- build.cake
Resolves https://github.com/OmniSharp/omnisharp-vscode/issues/4417
> Add sentinel file to MSBuild to enable workload resolver

- CHANGELOG.md
Since 1.37.7 has the binding redirect issue, it would be good to make a new release
> updated release notes for 1.37.8

- NuGet.Config
- tools/packages.config
https://github.com/dotnet/core/issues/6278
> Update included toolset to match .NET 6 preview4

- build/Packages.props
- src/OmniSharp.Abstractions/Configuration.cs
- src/OmniSharp.Http.Driver/app.config
- src/OmniSharp.LanguageServerProtocol/app.config
- src/OmniSharp.Stdio.Driver/app.config
- tests/OmniSharp.Roslyn.CSharp.Tests/AbstractGoToDefinitionFacts.cs
- tests/app.config
- tools/packages.config
> Update build tools to match NET 6 Preview 5

- tests/OmniSharp.Cake.Tests/CodeActionsV2Facts.cs
Fixes broken master following bad auto merge
> fixed Cake test following the auto merge of #2175

- .github/workflows/build.yml
- .github/workflows/tests.yml
- azure-pipelines.yml
I believe this would get CI running on https://github.com/OmniSharp/omnisharp-roslyn/pull/2179
> Run CI on PRs to feature branches

- build/Packages.props
Updating Roslyn for Razor team.
> Update Roslyn to 4.0.0-2.21322.50

- build/Packages.props
- src/OmniSharp.Host/CommandLineApplication.cs
Attempt to fix https://github.com/OmniSharp/omnisharp-vscode/issues/4090
> Upgrade McMaster.Extensions.CommandLineUtils to 3.1.0.

- .config/dotnet-tools.json
- .pipelines/init.yml
- azure-pipelines.yml
- tools/packages.config
Moved away from the RC, since there is a stable one now
> upgraded to Cake 1.1.0

- CODE_OF_CONDUCT.md
Added a .NET Foundation based Code of Conduct, this is standard for projects from DNF.
SInce last week there is a nice new feature in Github where the Code of Conduct, if found, would also be shown in the right hand menu (next to readme and license links).
> added Code of Conduct

- build.cake
> added build targets for ARM 64 macOS

- build/Packages.props
- test-assets/test-projects/CakeProject/tools/packages.config
- tests/OmniSharp.Cake.Tests/CompletionFacts.cs
- Update Cake.Bakery version used in tests.
> Update OmniSharp.Cake dependencies

- build.cake
- build.json
The merging of build file is pretty painful between the two branches.
> [vnext] missing build tasks

- build/Packages.props
- tools/packages.config
This is needed to unblock #2290
> Updated to Roslyn 4.0.1

- src/OmniSharp.Http.Driver/app.config
- src/OmniSharp.Stdio.Driver/app.config
- tests/app.config
Suggested in https://github.com/OmniSharp/omnisharp-roslyn/pull/2443#discussion_r959990108 but I missed it prior to merging.
> Add comment to app.config explaining System.Memory versioning

- CHANGELOG.md
- build/Packages.props
- tests/OmniSharp.Roslyn.CSharp.Tests/AbstractGoToDefinitionFacts.cs
- tests/OmniSharp.Roslyn.CSharp.Tests/GotoTypeDefinitionFacts.cs
New Language Features
```
C# 7.0 pattern matching
C# 8.0 stackalloc in nested contexts
C# 9.0 skip locals init
C# 9 covariant returns
C# 10 file-scoped namespace declarations
C# 10 abstract static interface members
```
there is already a preview of 8.0 but we can wait for the stable one.
> updated IL Spy to 7.2.1.6856

- CHANGELOG.md
- src/OmniSharp.Cake/Extensions/ResponseExtensions.cs
- src/OmniSharp.Cake/Services/RequestHandlers/Files/FileOpenHandler.cs
- tests/OmniSharp.Cake.Tests/FileOpenFacts.cs
Seems like this endpoint is missing, added it to remove some errors in VSCode logs
> Adds missing /open endpoint to Cake

- azure-pipelines.yml
Until the MyGet storage quota issue is resolved.
> Skip pushing packages to MyGet

- azure-pipelines.yml
> Fix push to Azure Artificats

- azure-pipelines.yml
This is getting silly. But third time's the charm...
> AzDo project name is Builds and feed is omnisharp

- CHANGELOG.md
Last release had some validation issues.  Creating a new release with fixes to hopefully get a new version of the extension out.
> Update changelog for 1.39.4

- CHANGELOG.md
I should have done this in https://github.com/OmniSharp/omnisharp-roslyn/pull/2518 but I completely forgot.
> Update changelog for 1.39.6

- Directory.Packages.props
- src/OmniSharp.Abstractions/Configuration.cs
- src/OmniSharp.Http.Driver/app.config
- src/OmniSharp.LanguageServerProtocol/app.config
- src/OmniSharp.Stdio.Driver/app.config
- tests/app.config
Updated Roslyn to match .NET SDK 8p7
> Update Roslyn to version 4.8.0-1.23374.10

- Directory.Packages.props
Updated the dotnet-script dependency to the latest released one
> Updated to latest dotnet-script 1.5.0

- Directory.Packages.props
- src/OmniSharp.Abstractions/Configuration.cs
- src/OmniSharp.Roslyn.CSharp/Services/Refactoring/V2/CachingCodeFixProviderForProjects.cs
- src/OmniSharp.Roslyn.CSharp/Workers/Diagnostics/CSharpDiagnosticWorkerWithAnalyzers.cs
- src/OmniSharp.Roslyn/BufferManager.cs
- src/OmniSharp.Roslyn/ProjectEventForwarder.cs
- tests/Directory.Build.props
- tests/OmniSharp.Lsp.Tests/OmnisharpCompletionHandlerFacts.cs
- tests/OmniSharp.MSBuild.Tests/OmniSharp.MSBuild.Tests.csproj
- tests/OmniSharp.Roslyn.CSharp.Tests/CompletionFacts.cs
- tests/OmniSharp.Roslyn.CSharp.Tests/CustomRoslynAnalyzerFacts.cs
- tests/TestUtility/TestUtility.csproj
Builds on the SDK update PR https://github.com/OmniSharp/omnisharp-roslyn/pull/2652
> Update Roslyn to 5.0.0-2.25373.17
