build.cmd
`kvm upgrade` is not needed because OmniSharp explicitly needs `1.0.0-beta2`. `kvm upgrade` gets the latest version of KVM which is ignore anyway, moreover it is aliasing it as 'default' forcing VS to pick it up. 
so if you run the `build.cmd` you will not be able to compile OmniSharp in VS until you manually reset the `default back to `1.0.0-beta2` which is a bit odd.
Alternatively, the build script could reset the `default` alias to `1.0.0-beta2`.
=> do not call kvm upgrade in build.cmd

src/OmniSharp/Api/Refactoring/OmnisharpController.Rename.cs, src/OmniSharp/Roslyn/OmniSharpWorkspace.cs, tests/OmniSharp.Tests/OmnisharpControllerFacts.cs, tests/OmniSharp.Tests/RenameFacts.cs, tests/OmniSharp.Tests/TestHelpers.cs, tests/OmniSharp.Tests/project.json
fixes #55.
Since `OmniSharpWorkspace` inherits from `Workspace` abstract class, it needs to explicitly specify which changes can be done - and it seems reasonable to assume that all changes specified in the `ApplyChangesKind` should be allowed.
This prevents the exception mentioned in the #55 from happening and the buffer is correctly updated. 
However, the changes are not saved to disk at this moment. Roslyn normally does it using `MSBuildWorkspace` not through the base `Workspace` class. I haven't included this in the PR as I am not sure if any strategy for that has been discussed, but I can extend `OmniSharpWorkspace` to persist to disk if needed.
=> allow any change to be done in OmnisharpWorkspace

src/OmniSharp/Api/Diagnostics/OmnisharpController.Diagnostics.cs, src/OmniSharp/Models/QuickFix.cs
ends up with a response as below
{
"QuickFixes": [
{
"LogLevel": "Hidden",
"FileName": "C:\\GitHub\\omnisharp-roslyn\\src\\OmniSharp\\Roslyn\\OmniSharpWorkspace.cs",
"Line": 4,
"Column": 1,
"EndLine": 4,
"EndColumn": 19,
"Text": "Unnecessary using directive.",
"Projects": [
"OmniSharp+aspnet50",
"OmniSharp+aspnetcore50"
]
}
]
}
=> Returning collecion of projects with code check

src/OmniSharp/Api/Refactoring/OmnisharpController.CodeActions.cs
This fixes a small issue that I was having in brackets where the buffer was not updated properly, so codeactions changed randomly.
=> ensure the buffer is updated

src/OmniSharp/Api/Buffer/OmnisharpController.Buffer.cs, src/OmniSharp/Api/Diagnostics/OmnisharpController.Diagnostics.cs, src/OmniSharp/Api/Formatting/OmnisharpController.FormatDocument.cs, src/OmniSharp/Api/Intellisense/OmnisharpController.Intellisense.cs, src/OmniSharp/Api/Navigation/OmnisharpController.FindImplementations.cs, src/OmniSharp/Api/Navigation/OmnisharpController.FindUsages.cs, src/OmniSharp/Api/Navigation/OmnisharpController.GotoDefinition.cs, src/OmniSharp/Api/OmnisharpController.cs, src/OmniSharp/Api/Refactoring/OmnisharpController.CodeActions.cs, src/OmniSharp/Api/Refactoring/OmnisharpController.Rename.cs, src/OmniSharp/Api/TestCommands/TestCommandController.cs, src/OmniSharp/Api/Types/OmnisharpController.TypeLookup.cs, src/OmniSharp/Filters/UpdateBufferFilter.cs, src/OmniSharp/Startup.cs, tests/OmniSharp.Tests/FindImplementationFacts.cs, tests/OmniSharp.Tests/FindReferencesFacts.cs, tests/OmniSharp.Tests/OmnisharpControllerFacts.cs, tests/OmniSharp.Tests/RenameFacts.cs, tests/OmniSharp.Tests/TestCommandFacts.cs, tests/OmniSharp.Tests/TestHelpers.cs, tests/OmniSharp.Tests/UpdateBufferFilterFacts.cs
instead of remembering to update buffer all over the place, if the action takes a `Request` model and if the request has `FileName` and `Buffer` populated, update the buffer automatically
=> if the Request has buffer content and filename, always update buffer

src/OmniSharp/Workers/Format/Formatting.cs, src/OmniSharp/Workers/Format/TextChange.cs, tests/OmniSharp.Tests/FormattingFacts.cs
The easiest way to apply a bunch of (non-overlapping) text changes is to apply them in reverse order. This changes makes sure that Omnisharp always sort them that way. Also adding test to verify this behaviour and fixing some formatting issues.
=> sort text changes descending (by span)

src/OmniSharp/Api/Navigation/OmnisharpController.FindUsages.cs, src/OmniSharp/Models/FindUsagesRequest.cs, tests/OmniSharp.Tests/FindReferencesFacts.cs
Allows to limit the find usages call to the current file. This will allow editors to implement a _mark occurrences_ feature (highlighting all occurrences of the symbol under the caret)
=> Find usages in file

src/OmniSharp/Api/Buffer/OmnisharpController.Buffer.cs, src/OmniSharp/Api/Diagnostics/OmnisharpController.Diagnostics.cs, src/OmniSharp/Api/Formatting/OmnisharpController.Format.cs, src/OmniSharp/Api/Intellisense/OmnisharpController.Intellisense.cs, src/OmniSharp/Api/Navigation/OmnisharpController.FindImplementations.cs, src/OmniSharp/Api/Navigation/OmnisharpController.FindUsages.cs, src/OmniSharp/Api/Navigation/OmnisharpController.GotoDefinition.cs, src/OmniSharp/Api/ProjectSystem/OmnisharpController.ProjectSystem.cs, src/OmniSharp/Api/Refactoring/OmnisharpController.CodeActions.cs, src/OmniSharp/Api/Refactoring/OmnisharpController.Rename.cs, src/OmniSharp/Api/Structure/OmnisharpController.Members.cs, src/OmniSharp/Api/TestCommands/TestCommandController.cs, src/OmniSharp/Api/Types/OmnisharpController.TypeLookup.cs, src/OmniSharp/Settings/FromBodyApplicationModelConvention.cs, src/OmniSharp/Startup.cs
This ensures that `[FromBody]` is auto-applied to all complex types. It also respects overriding this, so if you use i.e. `[FromQuery]` on a parameter, that will take precedence.
This will help avoid issues such as #87
=> Automatically use [FromBody] for all complex types

src/OmniSharp/Extensions/StringExtensions.cs, tests/OmniSharp.Tests/SnippetFacts.cs
Limit fuzzy matching so that it only matches when the first characters match. This can improve the performance tremendously (especially when you are at the root level of a method and are matching on a single char)
It was returning far too many results previously.
=> limit fuzzy matching 

build.sh, src/OmniSharp.Stdio/Protocol/RequestPacket.cs, src/OmniSharp.Stdio/StdioServer.cs, tests/OmniSharp.Stdio.Tests/StdioServerFacts.cs, tests/OmniSharp.Stdio.Tests/TestTextWriter.cs
learnt that ```JsonConvert.DeserializeObject``` does not complain about something like this: ```{"KeyWithOutValue":,"KeyWithValue":true}```
=> tackle #107, add (and fix) tests, check for valid request packet

src/OmniSharp/Api/Refactoring/OmnisharpController.Rename.cs, src/OmniSharp/Models/RenameResponse.cs, tests/OmniSharp.Tests/RenameFacts.cs
Catches ```ArgumentException``` from the renamer and fills a error message. Added a test which tries to rename ```Console.Write```
=> fix for #113

src/OmniSharp/Api/Files/OmnisharpController.Files.cs, src/OmniSharp/AspNet5/AspNet5ProjectSystem.cs, src/OmniSharp/AspNet5/Project.cs, src/OmniSharp/Models/AspNet5Project.cs, src/OmniSharp/Models/MSBuildProject.cs, src/OmniSharp/Roslyn/ProjectEventForwarder.cs, src/OmniSharp/Services/IEventEmitter.cs, src/OmniSharp/Services/ManualFileSystemWatcher.cs, src/OmniSharp/Services/NullEventEmitter.cs, src/OmniSharp/Services/StdioEventEmitter.cs, src/OmniSharp/Startup.cs
This PR covers the ground work for #106 and I would like get it out before it gets too big. Until now, it contains these changes
* replace the (flaky) file event watcher with a ```filesChanged``` route which drives the ```IFileWatcher```
* Add an IEventEmitter interface which allows OmniSharp to talk back to an editor (such that it can communicate the effects of changed files)
* Listen for some workspace events (project modifications) and send those events (in the shape of ```ProjectInformationResponse```-objects) to the connected editor
* Make ```ProjectInformationResponse``` also include the source files of a project such that an editor can use this information, for instance requesting diagnostics for more than the open files.
What still needs to be done is refining the file events …
=> Files changed

src/OmniSharp/Api/Buffer/OmnisharpController.Buffer.cs, src/OmniSharp/Filters/UpdateBufferFilter.cs, src/OmniSharp/Roslyn/BufferManager.cs, src/OmniSharp/Roslyn/OmniSharpWorkspace.cs, tests/OmniSharp.Tests/BufferManagerFacts.cs, tests/OmniSharp.Tests/RenameFacts.cs, tests/OmniSharp.Tests/TestHelpers.cs, tests/OmniSharp.Tests/UpdateBufferFilterFacts.cs
This PR adds support for handling unknown buffers. The idea goes like this:
1. a ```Request``` for an unknown files comes in and
2. the buffer manager simply adds this file to all projects (I figured it's better then guessing, but we can discuss) and
3. the buffer manager remembers that file path so that later when
4. a project system adds the same file (because it caught up after a FS change event or ```/addToProject``` was called) the buffer manager can remove the transient file again (avoid duplication)
=> Transient buffers

src/OmniSharp/Program.cs, src/OmniSharp/project.json
When I tried to `build.sh` the latest master to use in OmniSharp-Sublime I found:
* the `OmniSharp` build failed because of a missing namespace in `Program.cs`
* when running the server from Sublime it failed because it needed `Microsoft.Composition 1.0.30` and the bundled version was `1.0.27`
This fixes those two problems.
=> Fixed issues with build

src/OmniSharp/AspNet5/DesignTimeHostManager.cs
With the dnx adoption we broke launching on windows, because ```File.Exists``` isn't so smart to figure out the ```klr``` is ```klr.exe``` when executed.
=> fix windows launch bug

src/OmniSharp/Api/Intellisense/OmnisharpController.Intellisense.cs, src/OmniSharp/Workers/Intellisense/SnippetGenerator.cs, tests/OmniSharp.Tests/IntellisenseFacts.cs
Display text now displays correctly for both snippeted and no snippeted response
=> Fixing the display text so it shows correctly

src/OmniSharp/Api/Signatures/InvocationContext.cs, src/OmniSharp/Api/Signatures/OmnisharpController.SignatureHelp.cs, src/OmniSharp/Models/SignatureHelp.cs, src/OmniSharp/Models/SignatureHelpItem.cs, src/OmniSharp/Models/SignatureHelpParameter.cs, tests/OmniSharp.Tests/SignatureHelpFacts.cs
This PR add a new route ```/signatureHelp``` which can be used to get information about signatures at a given position. It will return a list of signatures if invoked inside a constructor call or method call. Each signature represents an overload with its specific comment and parameters. The active signature and active parameter are denoted by the result object.
=> Signature Help

src/OmniSharp/AspNet5/AspNet5Paths.cs, src/OmniSharp/AspNet5/AspNet5ProjectSystem.cs, src/OmniSharp/AspNet5/DesignTimeHostManager.cs, src/OmniSharp/AspNet5/PackagesRestoreTool.cs
This PR makes sure that OmniSharp automatically restores packages (via ```dnu restore``` or ```kpm restore```) if needed. The flow goes like this:
1. OmniSharp receives a _dependencies_-message from DTH which flags ```unresolved``` dependencies
2. OmniSharp runs ```dnu restore``` or ```kpm restore``` (depending on the target runtime)
3. Upon completion OmniSharp sends DTH _restoreComplete_-messages (one per project)
4. DTH updates project references etc which in return makes OmniSharp update the Roslyn project
5. Roslyn emit a project modification event and forwards that to the editor
6. The editor ask request a new code check etc
=> Restore packages if needed

src/OmniSharp/AspNet5/AspNet5ProjectSystem.cs, src/OmniSharp/Models/EventTypes.cs, src/OmniSharp/Roslyn/ProjectEventForwarder.cs
When project state in Roslyn changes we already emit an event. This PR makes sure we also emit an event when project information outside roslyn (like commands in ASP projects) changes.
=> forward ProjectInformation events

src/OmniSharp/AspNet5/AspNet5Paths.cs, src/OmniSharp/AspNet5/AspNet5TestCommandProvider.cs, tests/OmniSharp.Tests/Fakes/FakeLoggerFactory.cs, tests/OmniSharp.Tests/Fakes/FakeOmniSharpEnvironment.cs, tests/OmniSharp.Tests/Fakes/FakeOmniSharpOptions.cs, tests/OmniSharp.Tests/TestCommandFacts.cs
This switches xunit arguments to be compatible with the new aspnet.xunit.runner.
`--test` becomes `-method`
I've also added a fixture `-class` command that we had in v1.
If you attempt to run a single test when the cursor is at the class level, then the fixture is ran instead.
This PR also allows test commands to work using either `dnx` or `k`
=> Update Xunit commands for the latest aspnet.xunit.runner

src/OmniSharp/AspNet5/AspNet5ProjectSystem.cs
This PR is a pragmatic fix for #174 as it doesn't use the Matcher when the project pattern is ```**/project.json``` which is the default. If you author that flag you are supposed to know what you are doing but the default behaviour should not crash OmniSharp
=> don't use matcher when project pattern is **/project.json

src/OmniSharp/Api/Diagnostics/OmnisharpController.Diagnostics.cs, src/OmniSharp/Api/ProjectSystem/OmnisharpController.ProjectSystem.cs, src/OmniSharp/MSBuild/MSBuildProjectSystem.cs, src/OmniSharp/Models/WorkspaceInformationResponse.cs, src/OmniSharp/Roslyn/ProjectEventForwarder.cs, src/OmniSharp/ScriptCs/NullScriptEngine.cs, src/OmniSharp/ScriptCs/ScriptCsContext.cs, src/OmniSharp/ScriptCs/ScriptCsProjectSystem.cs, src/OmniSharp/Startup.cs, src/OmniSharp/project.json, tests/OmniSharp.Tests/CurrentProjectFacts.cs
This introduces a 3rd project system - `ScriptCsProjectSystem`. It's ifdef-ed since it will not work on Core.
It finds CSX files in the directory and uses scriptcs assemblies to retrieve all the necessary information about the runtime - what usings are in the context, what DLLs are references and all other scriptcs-specific things. 
It then creates scripting projects in the workspace. After that, all Omnisharp endpoints work normally against the incoming requests as if you were working with any other type of project.
Example:
Note: I currently suppress `CS1024` error for scriptcs projects - this is to prevent treating `#load` directive as error (which is valid in scriptcs). Roslyn will introduce it later too, so this is temporary.
=> Add support for language services for scriptcs

src/OmniSharp/Api/Diagnostics/OmnisharpController.Diagnostics.cs
Added comment from PR #199 to the source code.
The `#load` directive, valid for script files (mentioned here https://github.com/dotnet/roslyn/issues/122) is currently not recognized by Roslyn so [CS1024](https://msdn.microsoft.com/en-us/library/ww43bwhw%28v=vs.90%29.aspx) need to be suppressed
=> added comment about CS1024

src/OmniSharp/MSBuild/MSBuildProjectSystem.cs, src/OmniSharp/ScriptCs/ScriptCsProjectSystem.cs, src/OmniSharp/Startup.cs
- wrapped the call to `Initialize()` on project system collection in try/catch since any unhandled exception that spills from project systems (file IO but also other) will crash the server. now at least other project systems have a chance to take over
- before, the only CSX exception handled was `InvalidDirectiveUseException`, but really any exception should be caught, and the processing should move to the next CSX file
=> Added exception handling to project initialization

src/OmniSharp/Api/Types/OmnisharpController.TypeLookup.cs, src/OmniSharp/ScriptCs/ScriptCsContext.cs, tests/OmniSharp.Tests/GoToFileFacts.cs, tests/OmniSharp.Tests/TestHelpers.cs, tests/OmniSharp.Tests/TypeLookupFacts.cs
For `SourceCodeKind.Interactive` and `SourceCodeKind.Script`, do not report a namespace as part of type lookup.
Fixes #222.
Also added a helper for creating a CSX workspace which we can use for more tests in the future.
=> Do not report namespace for non-regular C# syntax

src/OmniSharp/AspNet5/AspNet5Paths.cs
1. Both %HOME% and %USERPROFILE% are searched.
2. Environment variables are expanded to accomodate default value of
DNX_HOME.
=> DNX runtime algorithm fixes:

src/OmniSharp/AspNet5/AspNet5ProjectSystem.cs
DTH is language agnostic and with some project.json configuration^ OmniSharp ends up loading random files into roslyn. This PR fixes #230 by only feeding CS-files into roslyn. 
^https://github.com/aspnet/Home/wiki/Project.json-file#sources
=> filter sources message by ending and only allow .cs files

src/OmniSharp/Dnx/DnxProjectSystem.cs, src/OmniSharp/Utilities/DirectoryEnumerator.cs
This is an attempt to fix #192 by ignoring (and logging) any paths that are unauthorized while searching for project.json files.  I added a check for paths that are too long as well.  I've tested this on Windows and Linux with unauthorized paths and without.
=> Handle unauthorized access exceptions when searching for projects

src/OmniSharp/MSBuild/MSBuildProjectSystem.cs, src/OmniSharp/MSBuild/ProjectFile/ProjectFileInfo.cs
While Omnisharp doesn't support msbuild configuration switches at the moment - and always defaults to `Debug` configuration, this PR at least introduces the capability of reading its `<DefineConstants>` into the `CSharpCompilationOptions` which would allow the language services to properly respect them.
Based on #226
=> Read DefineConstants from MsBuild file

src/OmniSharp/Dnx/DesignTimeHostManager.cs
On my system I found that 4 seconds was not long enough for DHT to start.
Time for a new computer perhaps...
Anyway I have bumped the timeout to 10 seconds (FYI: my system on average took
6 seconds to start DHT).
I have also added in a check to see if the timeout has indeed been reached.
=> Fixes OmniSharp/omnisharp-roslyn#272

src/OmniSharp/Dnx/DesignTimeHostManager.cs
Allows omnisharp to work with both older and newer versions of DNX
=> React to DesignTimeHost rename

src/OmniSharp/Api/v1/Refactoring/OmnisharpController.Rename.cs, src/OmniSharp/Models/v1/RenameRequest.cs, tests/OmniSharp.Tests/RenameFacts.cs
Added a new flag to the request. Ideally, we would have used
WantsTextChanges to both return text changes and also to not apply
them at immediately at the server.
The assumption here is that new text changes will be returned to the
server as they are applied to the editor.
=> Conditionally apply changes for rename server side.

src/OmniSharp/Api/v1/Buffer/OmnisharpController.Buffer.cs, src/OmniSharp/Filters/UpdateBufferFilter.cs, src/OmniSharp/Models/v1/Request.cs, src/OmniSharp/Roslyn/BufferManager.cs, tests/OmniSharp.Tests/BufferManagerFacts.cs
Simliar to requests containing a new [buffer](https://github.com/OmniSharp/omnisharp-roslyn/blob/master/src/OmniSharp/Models/v1/Request.cs#L11) this PR adds support for attaching incremental buffer updates to a request. This allows you get around an explicit call to ```/changebuffer``` and also has the neat side effect that clients don't have to process requests one after the other but send them in parallel - given they know what they do ;-)
=> Allow to send file specific edits with a request

scripts/Omnisharp.cmd, src/OmniSharp/MSBuild/MSBuildProjectSystem.cs
There was incorrect usage of CSharpParseOptions.WithPreprocessorSymbols. Fixed after reading sources of roslyn - https://github.com/dotnet/roslyn/blob/6d228445c972c67259dbfa1aa203395cccb6f92e/src/Compilers/CSharp/Portable/CSharpParseOptions.cs
=> Fix setting up PreprocessorSymbols for MSBuild project.

src/OmniSharp.Stdio/StdioServer.cs, src/OmniSharp/Api/v1/ProjectSystem/OmnisharpController.Status.cs
Works in stdio, unlike https://github.com/OmniSharp/omnisharp-roslyn/pull/190.
Run needs to returns for RequestShutdown to shutdown the server in stdio mode.
RequestShutdown is requested in the background to avoid an error which sometime occurs if it is ran in an action.
=> Added /stopserver

src/OmniSharp/Dnx/DesignTimeHostManager.cs, src/OmniSharp/Dnx/DnxPaths.cs, src/OmniSharp/Dnx/DnxSdk.cs
- Today we choose whatever default the user has as the thing to launch for *everything*. This is normally ok but DTH doesn't work on coreclr cross platform as yet (because of missing socket support). This change fixes up the runtime to be mono before launching the design time host. This change can be removed once things work with core clr again.
=> Always launch DTH using mono (on non windows)

src/OmniSharp/Api/v1/Types/OmnisharpController.TypeLookup.cs, tests/OmniSharp.Tests/TypeLookupFacts.cs
Fixes https://github.com/OmniSharp/omnisharp-roslyn/issues/287
Fixes https://github.com/OmniSharp/omnisharp-atom/issues/275
=> Do not show <global namespace> in type lookup

src/OmniSharp/Api/v1/Formatting/OmnisharpController.Format.cs, src/OmniSharp/Options/FormattingOptions.cs, src/OmniSharp/config.json, tests/OmniSharp.Tests/FormattingFacts.cs
Fixes https://github.com/OmniSharp/omnisharp-roslyn/issues/266
Currently, omnisharp options expose `tabSize` which some of the users have been trying to use to control indentation (see https://github.com/OmniSharp/omnisharp-roslyn/issues/266).
However, it's only applicable to code formatting with Roslyn (and indeed it works with omnisharp now) when tabs are enabled - to determine the size of the tab. 
For regular indentation, Roslyn exposes another setting called `Microsoft.CodeAnalysis.Formatting.FormattingOptions.IndentationSize` which is the principal way of controlling how large the indentation should be.
=> Added IndentationSize to formatting options

src/OmniSharp/Options/FormattingOptions.cs, src/OmniSharp/Workers/Format/Formatting.cs
I noticed another bug in formatting code - the formatting options are not flown correctly into `FormatAsync` when using `GetFormattingChangesForRange`.
On the other hand, when using `GetFormattedDocument`, the options are applied ([see here](https://github.com/OmniSharp/omnisharp-roslyn/blob/master/src/OmniSharp/Workers/Format/Formatting.cs#L80)).
This looks like a clear bug, because when formatting **the entire document**, the options (i.e. the new indentation size I added yesterday or use of tabs) are applied as expected, but on stroke or range formatting they are not falling back to the defaults, resulting in two different types of behavior in the document :)
This PR fixes it and correctly applies formatting also on stroke/range:
=> correctly flow formatting options

src/OmniSharp/Dnx/DnxProjectSystem.cs, src/OmniSharp/Dnx/OutgoingMessages/CompilationSettings.cs
- Flow compilation options to the workspace
There's a missing feature with respect to strong naming support for dnx projects. VsCode is still based off 1.5.5 so I made a branch to enable fixing this specific thing. VSCode can't take 1.6.0 because it still has a bunch of bugs that need to be worked out (I've filed some myself). 
This is mostly a for code review. I'll send out another one based on 1.6.0 soon. The port should be trivial.
/cc @jrieken
=> [Don't merge yet]: Fix strong naming support in dnx projects

src/OmniSharp.Stdio/StdioServer.cs
Stdio passes exception messages through as an `error` event-type but fails to escape the string, which causes an error on the client-side when parsing the JSON.
=> Fix string escaping on exception messages for Stdio

tests/OmniSharp.Roslyn.CSharp.Tests/FixUsingsFacts.cs
If the test source, and thus the test contents is using a different new
line sequence than the system, these tests will fail because the output
will differ by the new lines. Flatten new lines into a single new line
format before testing for equality.
Closes #376 (code via @mispencer)
=> Ignore new line differences in tests

.travis.yml, build.sh, scripts/tasks.sh
Move tasks to their own scripts so as to clean up the main build scripts
and enable sharing in the future.
Add packaging to the build process.
=> Update build scripts

src/OmniSharp.DotNet/Cache/ProjectStatesCache.cs, src/OmniSharp.DotNet/DotNetProjectSystem.cs, src/OmniSharp.DotNet/Models/DotNetProjectInformation.cs, src/OmniSharp.DotNet/Models/DotNetWorkspaceInformation.cs, src/OmniSharp.Roslyn/WorkspaceInformationService.cs
This is necessary for the DotNetProjectSystem to handle the /projects end point.
cc @troydai, @david-driscoll
=> Add support for DotNetProjectSystem.GetInformationModel(...)

src/OmniSharp.Roslyn.CSharp/Services/Signatures/SignatureHelpService.cs
OmniSharp used the full span of an argument list to determine whether signature help should be shown. However, that includes both leading and trailing trivia, which means that it would return signatures for positions outside of the argument list. In addition, I switched it to use `Contains(...)` rather than `IntersectsWith(...)` since checking the position against the argument list span should not include the outer positions (e.g. on the left or right of the parentheses).
This fixes https://github.com/OmniSharp/omnisharp-vscode/issues/64.
cc @david-driscoll, @troydai
=> Fix span used to determine whether signature help should be shown

CONTRIBUTING.md
[Contribution guidelines](https://github.com/blog/1184-contributing-guidelines) was missing - and now that we have `dev` and `master` it might be especially useful.
=> Added contribution file

build.cake, build.json, depversion.json, scripts/cake-bootstrap.ps1, scripts/cake-bootstrap.sh, src/OmniSharp.Abstractions/project.json, src/OmniSharp.Bootstrap/project.json, src/OmniSharp.DotNet/project.json, src/OmniSharp.Host/Startup.cs, src/OmniSharp.Host/project.json, src/OmniSharp.MSBuild/Analyzers/SimpleAnalyzerAssemblyLoader.cs, src/OmniSharp.MSBuild/project.json, src/OmniSharp.Nuget/project.json, src/OmniSharp.Plugins/project.json, src/OmniSharp.Roslyn.CSharp/project.json, src/OmniSharp.Roslyn/project.json, src/OmniSharp.ScriptCs/project.json, src/OmniSharp.Stdio/project.json, src/OmniSharp/project.json, tests/OmniSharp.Bootstrap.Tests/project.json, tests/OmniSharp.MSBuild.Tests/project.json, tests/OmniSharp.Roslyn.CSharp.Tests/MetadataFacts.cs, tests/OmniSharp.Roslyn.CSharp.Tests/project.json, tests/OmniSharp.Stdio.Tests/project.json, tests/OmniSharp.Tests/project.json
Updated to the latest CLI and new framework names/packages.
Updating to the most recent CLI requires updating the version of `"Microsoft.Extensions.DependencyModel"`, which brings with itself dependencies on a newer NETStandard library. Since changes were required to the `project.json`, I decided to also update the framework monikers.
Changes:
- dnx451->net451
- dnxcore50->netcoreapp1.0 for OmniSharp and tests and appropriate netstandard for the others
- netstandard projects depend on `NETStandard.Library` (and other libraries if needed)
- netcoreapp1.0 projects depend on `NETStandard.Library` and `Microsoft.DotNet.ProjectModel` (and other libraries if needed)
- NETCore.App brings extra unneeded dependencies including conflicting CodeAnalysis
- Changed `NETStandard.Library`, …
=> Updated to new frameworks and CLI + extra sugaring in build script

scripts/cake-bootstrap.ps1
It seems like if someone has a `nuget.exe` from the v2 erra, that when installing cake the destination folder is incorrect, it includes the Version in the folder name.
We don't see this on CI because the CI server doesn't come with `nuget.exe` by default, and locally I'm sure I don't have any V2 nuget.exe in my path.
fixes #484 
cc @troydai @danroth27
=> Use local nuget over PATH based nuget

build.cake, build.json, build.ps1, build.sh
New virtual RID within the build script called `default`. When targeting `default`, `dotnet publish` is called with no explicit runtime, thus allowing it to select the best match based on the list specified in `project.json`. When targeting `default` and trying to package, the environment variable `OMNISHARP_PACKAGE_OSNAME` is used instead of the short runtime identifier. `default` should always be in the list of Rids! The targets `Install` and `TestPublished` use `default` as it is the only one guaranteed to work locally.
RestrictToLocal sets the runtime list to `default`.
RestrictToEnvironment was changed to PopulateRuntimes and should populate the list of Rids, based on the OS. For now it sets the runtime list to `default` + `win7-x86` on Windows. Better logic could be used in the …
=> Updated RID logic to remove need for dotnet-info

src/OmniSharp.Abstractions/Services/IOmnisharpEnvironment.cs, src/OmniSharp.Host/Services/OmnisharpEnvironment.cs, src/OmniSharp.Host/Startup.cs
Currently, when `omnisharp.json` exists in the project folder, Omnisharp crashes and exits. This is because the base path is set to the `ConfigurationBuilder`, which points to the `ApplicaitonBase` instead of the root folder of the project .
=> Fix omnisharp.json configuration loading

omnisharp.json
The restore `--infer-runtimes` is not in the auto package restore. The auto restore now run into endless issues for now
=> Disable package restore for this solution

build.cake
Proposal for simpler archiving logic. I'm also including existing functionality to make the behavior clear and easy to discuss.
Windows: nothing changes, archives generated with the `win-x64-{framework}` and `win-x86-{framework}` (for non-Local builds) identifiers.
Linux/Users: nothing changes, archives generated with the `linux-64-{framework}` identifiers for the local runtime.
Linux/Travis:
- archive generated with the `mono` identifier for the local runtime using .NET 4.5.1 as framework.
- archives generated with the `{osshortname}-x64` identifier for all the runtimes explicitly mentioned in PopulateRuntimes (none for the local one, we expect it to be in the list) using .NET Core as framework.
OSX/User: nothing changes, archive generated with the `osx-x64-{framework}` identifier for …
=> Refinement of archive generation

src/OmniSharp.MSBuild/MSBuildProjectSystem.cs, src/OmniSharp.MSBuild/ProjectFile/ProjectFileInfo.cs
This change adds support for the SignAssembly and AssemblyOriginatorKeyFile properties in MSBuild project.
It allows projects with InternalsVisibleTo attributes for strong named assemblies to have proper error reporting and intellisense.
=> Handle strong-name key files from msbuild projects

src/OmniSharp.Host/Program.cs
Sometimes the server is not on the same machine as the client. In order to reach it we need the ability to specify the listening interface.
For more details see https://github.com/OmniSharp/omnisharp-emacs/pull/223.
=> Parameterize listening interface

scripts/archiving.cake
`ChangeExtension` was interacting poorly with the dot in `netcoreapp1.5`. The resulting archive name looked weird in the release. Sorry for the bug.
=> Fixed archive name with dots in name.

src/OmniSharp.Roslyn.CSharp/Workers/Intellisense/ReturnTypeFormatter.cs, tests/OmniSharp.Roslyn.CSharp.Tests/SnippetFacts.cs
In [PR](https://github.com/OmniSharp/omnisharp-vscode/pull/164) I have added return type information into `completionItemProvider`. But the `ReturnType` of an `event` was returned `null` from omnisharp server.
I have changed to return `event`'s `delegate` type for `ReturnType` like it is implemented in Visual Studio's intellisense.
P.S. Waiting for [new icon](https://github.com/Microsoft/vscode/issues/5407) in VS Code to change event's icon.
=> Set event's delegate type as return type

src/OmniSharp.Abstractions/Configuration.cs, src/OmniSharp.Roslyn.CSharp/CodeActions/RoslynCodeActionProvider.cs, src/OmniSharp.Roslyn.CSharp/Workers/Intellisense/CSharpSyntaxContext.cs, src/OmniSharp.Roslyn/MetadataHelper.cs
Fixes #554, while keeping the ability to hard-code version number and make it easy to manage long-term.
=> Refactored version information for CodeAnalysis Assemblies.

src/OmniSharp.DotNet/DotNetProjectSystem.cs, src/OmniSharp.MSBuild/MSBuildProjectSystem.cs, src/OmniSharp.MSBuild/ProjectFile/ProjectFileInfo.cs
Solves #542.
Only enabled when XML document generation is requested to avoid FxCop warnings. Should work for both `csproj` and `project.json` (tested locally on `project.json`).
Still needs unit-tests if you guys like the methodology.
=> Added tracking of XML comments via Roslyn (#542)

src/OmniSharp.ScriptCs/Extensions/EnumerableExtensions.cs, src/OmniSharp.ScriptCs/Extensions/ScriptcsExtensions.cs, src/OmniSharp.ScriptCs/ScriptCsContext.cs, src/OmniSharp.ScriptCs/ScriptCsProjectSystem.cs, src/OmniSharp.ScriptCs/project.json
This is a refactoring and rewrite of the initialization logic in the ScriptCs subsytem.
The aims are the following:
1. Support .csx files in all subdirectories not just root
2. Do not crash on multiple `#load# references in scripts
3. Follow `#load` references recursively and map them to proper project references
4. Do not break anything that worked before.
=> Do #load traversal recursively in scriptcs subsystem, #512

src/OmniSharp.Host/Program.cs
vs code need utf-8 encoding for stdio,and other maybe not.
=> config encoding For Stdio

build.cake
This avoids loading the default powershell profile when executing powershell scripts during Windows builds, since the user can define a default powershell profile that might do things like change the CWD.
=> Pass -NoProfile when executing powershell scripts

src/OmniSharp.MSBuild/ProjectFile/ProjectFileInfo.cs
On mono code in OmniSharp.MSBuild/ProjectFile/ProjectFileInfo.cs would
crash when any of the following keys "SignAssembly" "AssemblyOriginatorKeyFile" or
"DocumentationFile" is missing.
This adds check before referencing those properties.
=> OmniSharp.MSBuild: fix .csproj loading when some props are missing

src/OmniSharp.Abstractions/Services/IProjectSystem.cs, src/OmniSharp.DotNet/Cache/ProjectStatesCache.cs, src/OmniSharp.DotNet/DotNetProjectSystem.cs, src/OmniSharp.MSBuild/MSBuildProjectSystem.cs, src/OmniSharp.Plugins/Plugin.cs, src/OmniSharp.Roslyn/ProjectEventForwarder.cs, src/OmniSharp.Roslyn/ProjectInformationService.cs, src/OmniSharp.Roslyn/WorkspaceInformationService.cs, src/OmniSharp.ScriptCs/ScriptCsProjectSystem.cs, tests/OmniSharp.Tests/EndpointMiddlewareFacts.cs
This method almost always returns null because all implementations assume that the path passed in is a document path. However, every caller within OmniSharp always pass a project file path. Now, if a document isn't found, each implementation attempts the path as a project path. This fixes the '/projects' endpoint when a file path is specified and the Roslyn workspace events emitted from the OmniSharp server, such as 'ProjectChanged'.
cc @david-driscoll
=> Fix IProjectSystem.GetProjectModel(...) API

build.cake, scripts/cake-bootstrap.sh
This adds quotes to two paths used during the execution of `./build.sh`, to prevent failing the build if `pwd` contains spaces.
Fixes #599.
=> Add required quotes to paths

src/OmniSharp.Host/Program.cs
When the --encoding switch was specified, it unintentionally only applied to stdin, but not stdout. This was due to the fact that the `SharedConsoleWriter` was instantiated before `Console.OutputEncoding` was set. Because `SharedConsoleWriter` initializes itself with the current value of `Console.Out`, it had the default encoding rather than the intended encoding.
A bit subtle.
cc @david-driscoll and @nabychan
=> Fix OmniSharp --encoding switch to apply to both stdin and stdout

src/OmniSharp.DotNet/DotNetProjectSystem.cs, src/OmniSharp.MSBuild/Options/MSBuildOptions.cs, src/OmniSharp.MSBuild/ProjectFile/ProjectFileInfo.PropertyNames.cs, src/OmniSharp.MSBuild/ProjectFile/ProjectFileInfo.cs
Two settings have been added:
* dotnet.enabled: If set to false, the DotNetProjectSystem will not attempt to initialize and load any projects.
* msbuild.msbuildextensionpath: If set, the value will be passed into MSBuild as the MSBuildExtensionPath property.
=> Add configuration to make OmniSharp easier to test with MSBuild-based .NET Core projects

.travis.yml, build.json, scripts/archiving.cake, scripts/artifacts.cake, src/OmniSharp.Abstractions/project.json, src/OmniSharp.DotNet/project.json, src/OmniSharp.DotNetTest/project.json, src/OmniSharp.Host/project.json, src/OmniSharp.MSBuild/ProjectFile/ProjectFileInfo.cs, src/OmniSharp.MSBuild/ProjectFile/ProjectFileInfo_Mono.cs, src/OmniSharp.MSBuild/project.json, src/OmniSharp.Nuget/OmniSharpSourceRepositoryProvider.cs, src/OmniSharp.Nuget/Services/PackageSearchService.cs, src/OmniSharp.Nuget/Services/PackageSourceService.cs, src/OmniSharp.Nuget/Services/PackageVersionService.cs, src/OmniSharp.Nuget/project.json, src/OmniSharp.Plugins/project.json, src/OmniSharp.Roslyn.CSharp/project.json, src/OmniSharp.Roslyn/project.json, src/OmniSharp.ScriptCs/project.json, src/OmniSharp.Stdio/project.json, src/OmniSharp/project.json, tests/OmniSharp.MSBuild.Tests/project.json, tests/OmniSharp.Roslyn.CSharp.Tests/project.json, tests/OmniSharp.Stdio.Tests/project.json, tests/OmniSharp.Tests/project.json, tests/TestCommon/project.json, tests/TestUtility/project.json
This is necessary to take advantage of newer MSBuild bits in the near future.
=> Move OmniSharp to net46

build.cake, src/OmniSharp/project.json
Fixes #603
The build scripts may not be right yet, so this is still a work in progress. However, targeting AnyCPU definitely allows OmniSharp.exe to run on 32-bit Windows.
=> Support 32-bit Windows

src/OmniSharp.Abstractions/project.json, src/OmniSharp.DotNet/project.json, src/OmniSharp.DotNetTest/project.json, src/OmniSharp.MSBuild/project.json, src/OmniSharp.Roslyn.CSharp/project.json, src/OmniSharp.Roslyn/MetadataHelper.cs, src/OmniSharp.Roslyn/project.json, tests/OmniSharp.DotNet.Tests/project.json, tests/OmniSharp.Stdio.Tests/project.json, tests/TestUtility/project.json
This change updates the Microsoft.CodeAnalysis packages to 2.0.0-beta5, which should match the versions shipped with Visual Studio "15" Preview 5 earlier this month. In addition, we now reference specific packages rather than just "Microsoft.CodeAnalysis", so it no longer pulls in Microsoft.CodeAnalysis.VisualBasic.Workspaces for netcoreapp1.0 builds or Microsoft.CodeAnalysis.VisualBasic for net46 builds.
=> Update to Roslyn 2.0.0-beta5

README.md
* Update link to .NET Core SDK
* Update TFM references to current names
* Update required Mono version
* Add link to build.md
* Update VS Code setting
* Remove jabbr.net link, since it appears to be dead.
=> Minor tweaks to readme.md

src/OmniSharp.MSBuild/ProjectFile/PropertyConverter.cs
For MSBuild projects, C# 6 was hard-coded as the "default" language version. Now that OmniSharp is on Roslyn 2.0.0-beta5 it can use the `LanguageVersion.Default`, which defaults to the latest major version of the language. In this case, that'll be C# 7.
See https://github.com/dotnet/roslyn/commit/042823a3170bb2c2ca718cd39cc02762fb6f3770 for details on how `LanguageVersion.Default` works.
=> Allow OmniSharp to default to the latest C# language version

src/OmniSharp/app.config
This will cause a dialog to be displayed when launching OmniSharp.exe to inform the user that they need to install .NET Framework 4.6 to run it.
=> Add app.config to require .NET 4.6 when launching OmniSharp.exe

src/OmniSharp.Roslyn.CSharp/Services/DocumentationConverter.cs, tests/OmniSharp.Roslyn.CSharp.Tests/DocumentationConverterFacts.cs
Missing spacing after `<paramref />` (if spaces are used in the text that follows, it is always trimmed).
Fixes https://github.com/OmniSharp/omnisharp-vscode/issues/672
=> Missing space in <paramref />

src/OmniSharp.Roslyn.CSharp/Services/Types/TypeLookup.cs, tests/OmniSharp.Roslyn.CSharp.Tests/TypeLookupFacts.cs
Instead of manually composing type information, use `SymbolDisplayFormat` to format the response according to the predefined rules:
- default `SymbolDisplayFormat.FullyQualifiedFormat` but without `global::` for regular C# syntax
- `SymbolDisplayFormat.FullyQualifiedFormat`but without `global::` and without namespace for script/interactive syntax
Fixes https://github.com/OmniSharp/omnisharp-vscode/issues/394 (currently OmniSharp doesn't show type lookup information for nested types correctly)
=> use SymbolDisplayFormat in TypeLookup

src/OmniSharp.Roslyn.CSharp/Services/Intellisense/IntellisenseService.cs, tests/OmniSharp.Roslyn.CSharp.Tests/IntellisenseFacts.cs
Fixes https://github.com/OmniSharp/omnisharp-vscode/issues/980
=> Don't throw null-ref when Roslyn CompletionService doesn't return anything

src/OmniSharp.Roslyn.CSharp/Services/Types/TypeLookup.cs
At the moment if there is a symbol miss in `TypeLookup` (which can happen if we have missing unresolved references and so on) OmniSharp will always respond with 500 - due a null reference exception in `TypeLookup`.
This fixes the issue.
=> avoid null reference in TypeLookup

src/OmniSharp.Abstractions/Utilities/PlatformHelper.cs, src/OmniSharp.MSBuild/ProjectFile/ProjectFileInfo.cs
I just noticed that I hadn't pushed these important commits to new-msbuild. These are critical for properly setting the TargetFrameworkRootPath when running on Mono.
=> When running on Mono, populate the TargetFrameworkRootPath using the location of 'mono'

src/OmniSharp.Roslyn.CSharp/Services/Signatures/SignatureHelpService.cs
There was a bug when dealing with constructors, OmniSharp was returning `symbol.ContainingType.ToDisplayString(SymbolDisplayFormat.MinimallyQualifiedFormat)` rather than `symbol.ToDisplayString(SymbolDisplayFormat.MinimallyQualifiedFormat)`. 
This resulted in all entries being identical for each constructor.
fixes https://github.com/OmniSharp/omnisharp-roslyn/issues/697 and fixes https://github.com/OmniSharp/omnisharp-vscode/issues/36
=> fixed constructor signature helper

src/OmniSharp.Script/ScriptProjectSystem.cs
Fixes #702.
This allows OmniSharp to support intellisense when GAC reference is used. i.e. instead of:
```
#r "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6\System.Web.dll"
```
we can use:
```
#r "System.Web"
```
This is in line with the default CSI behavior, which supports GAC references.
=> use the default ScriptMetadataResolver for scripts

global.json
At the moment, looks like a lot of people are already on preview3 or preview4 which causes a failure when loading OmniSharp in VS.
=> added global.json to enforce an older .net sdk version

src/OmniSharp.Host/Program.cs
This PR introduces a new startup argument `-loglevel {value}`, which allows OmniSharp logging level to be configured from outside.
At the moment there is only a `-v` switch which toggles between `information` and `debug` levels, but there is no way to set up more granular logging levels. For now I have not removed the `-v` switch yet, so as to not break any existing use case.
The PR will allow adding this feature https://github.com/OmniSharp/omnisharp-vscode/issues/993 to the editors.
=> allow loglevel to be passed in as an argument 

src/OmniSharp.Script/ScriptProjectSystem.cs, src/OmniSharp.Script/project.json
This PR adds `System.ValueTuple` automatically into the compilation references.
This is required because it's already part of "standard scripting" - CSI also automatically adds it https://github.com/dotnet/roslyn/commit/4d6c590f42fc5558aea5ed45f0d1698719533793, allowing users to use tuples straight away without any extra manual set up.
=> include System.ValueTuple in C# Scripts

src/OmniSharp.DotNet/DotNetProjectSystem.cs, src/OmniSharp.MSBuild/MSBuildProjectSystem.cs, src/OmniSharp.Script/ScriptProjectSystem.cs
`SourceText` will attempt to detect encoding from BOM (and fallback to UTF-8 anyway) so we shouldn't impose it on the loaded files.
=> do not implicity use UTF-8 for SourceText

src/OmniSharp.MSBuild/MSBuildEnvironment.cs
This allows the MSBuild tools to be found when attaching a debugger to OmniSharp (as opposed to starting it under the debugger).
This also makes things work when setting the "omnisharp.path" in VS Code to bin/Debug/net46/OmniSharp.exe.
=> Use Application.BaseDirectory when searching for OmniSharp.sln in MSBuildEnvironment

build.cake, msbuild/15.0/Microsoft.Common.targets/ImportAfter/Microsoft.NuGet.ImportAfter.targets, msbuild/15.0/SolutionFile/ImportAfter/Microsoft.NuGet.ImportAfter.targets, packages/packages.config, scripts/pathhelpers.cake, src/OmniSharp.MSBuild/MSBuildEnvironment.cs, src/OmniSharp.MSBuild/Options/MSBuildOptions.cs, src/OmniSharp.MSBuild/ProjectFile/ProjectFileInfo.PropertyNames.cs, src/OmniSharp.MSBuild/ProjectFile/ProjectFileInfo.cs
This PR includes the following changes
* Update OmniSharp to the latest .NET Core SDK packages
* Include "ImportAfter" targets which will should allow it to perform package restores via MSBuild in the near feature.
* Clean up build.cake somewhat (at least, reducing some noise).
* Add support for setting MSBuildSDKsPath in omnisharp.json. This can be used to redirect OmniSharp to a different set of SDK packages if desired.
=> Update to VS 2017 RC .NET Core SDK packages

src/OmniSharp.Abstractions/Extensions/ISymbolExtensions.cs, src/OmniSharp.DotNetTest/Helpers/TestFeaturesDiscover.cs
Fixes https://github.com/OmniSharp/omnisharp-vscode/issues/743 and fixes https://github.com/OmniSharp/omnisharp-vscode/issues/1151
The issue here is that the metadata name for nested classes was not correct. OmniSharp would report "A.B.C" for the following code, but it should be "A.B+C".
```C#
namespace A
{
class B
{
class C
{
}
}
}
```
=> Fix running unit tests defined in nested classes

src/OmniSharp.MSBuild/MSBuildProjectSystem.cs
The .NET CLI offers commands to add and remove projects from an SLN file (e.g. `dotnet sln Solution1 add Project1.csproj`). When it does this, it uses a different project type GUID which we need to support in OmniSharp.
cc @blackdwarf
=> Support project type GUID added when the .NET CLI manipulates an SLN file

src/OmniSharp.Abstractions/Services/IOmnisharpEnvironment.cs, src/OmniSharp.Host/Internal/CommandOptionExtensions.cs, src/OmniSharp.Host/Program.cs, src/OmniSharp.Host/Startup.cs, src/OmniSharp.Host/project.json, src/OmniSharp/Program.cs, tests/TestUtility/Fake/FakeOmniSharpEnvironment.cs
Removed manual arg parsing in favor of https://www.nuget.org/packages/Microsoft.Extensions.CommandLineUtils/
Fixes #744 
This has a couple of benefits:
- obviously no need to maintain the arg parsing code anymore
- automatic help generation
- better/automatic support for short/long names of options
- automatic support for no value / single value / multi value options
- in the future we could easily introduce **commands** that could do interesting things (at the moment we have only **options**) i.e. `omnisharp plugin foo`
Note that we have a feature that supports passing `omnisharp.json` values via command line. This is great but is a bit of mess since "real/fixed" OmniSharp options are mixed up with `omnisharp.json` args which are then integrated into the runtime configuration. Ideally …
=> Added Microsoft.Extensions.CommandLineUtils

src/OmniSharp.Abstractions/Extensions/LoggerExceptions.cs, src/OmniSharp.Host/Loader/AssemblyLoader.cs, src/OmniSharp.Roslyn.CSharp/CodeActions/CodeActionHelper.cs, src/OmniSharp.Roslyn.CSharp/Services/Refactoring/V2/BaseCodeActionService.cs, src/OmniSharp.Roslyn.CSharp/Services/Refactoring/V2/GetCodeActionsService.cs, src/OmniSharp.Roslyn.CSharp/Services/Refactoring/V2/RunCodeActionService.cs, src/OmniSharp.Roslyn.CSharp/Workers/Refactoring/FixUsingsWorker.cs, tests/OmniSharp.Roslyn.CSharp.Tests/CodeActionsV2Facts.cs
Fixes https://github.com/OmniSharp/omnisharp-vscode/issues/925
There's a fair amount of refactoring in this PR but most of it is moving code around.
=> Clean up code action service and rationalize how we disallow certain Roslyn code actions

src/OmniSharp.Script/ScriptProjectSystem.cs
This is a copycat of https://github.com/OmniSharp/omnisharp-roslyn/pull/763
However, since C# script compiler implicitly uses `DesktopAssemblyIdentityComparer.Default` ([ref](https://github.com/dotnet/roslyn/blob/master/src/Scripting/CSharp/CSharpScriptCompiler.cs#L66)) it only makes sense we set up OmniSharp the same way when handling scripts.
=> use DesktopAssemblyIdentityComparer.Default for scripts

tests/OmniSharp.DotNet.Tests/project.json, tests/OmniSharp.DotNetTest.Tests/project.json, tests/OmniSharp.MSBuild.Tests/project.json, tests/OmniSharp.Roslyn.CSharp.Tests/project.json, tests/OmniSharp.Stdio.Tests/project.json, tests/OmniSharp.Tests/project.json
@filipw [mentioned](https://github.com/OmniSharp/omnisharp-roslyn/pull/770#issuecomment-279510689) that the TFMs can be swapped in the project.json files to make the VS 2015 Test Window properly discover tests. This change does exactly that.
=> Fix test discovery in VS 2015 by swapping the TFMs

src/OmniSharp.Script/ScriptProjectSystem.cs
At the moment C# script compiler APIs in Roslyn implicitly always allows unsafe blocks.
OmniSharp should match that because at the moment we break when defining i.e.
```
unsafe void Print(string txt) {
// do stuff
}
```
=> allow unsafe in C# scripts

src/OmniSharp.Script/ScriptProjectSystem.cs
This is what the Roslyn Script Compiler API does internally (see https://github.com/dotnet/roslyn/blob/version-2.0.0-rc4/src/Scripting/CSharp/CSharpScriptCompiler.cs#L67). We should do the same in order to avoid invalid error reporting in some cases (unfortunately the API required is internal).
Fixes #784
=> use IgnoreCorLibraryDuplicatedTypes binder flag in scripts

BUILD.md
* add mono-mdk prerequisite to BUILD.md documentation
Closes: #792
=> docs(build): add missing mono-mdk prerequisite for macos (#792)

src/OmniSharp.Script/CachingScriptMetadataResolver.cs, src/OmniSharp.Script/ScriptProjectSystem.cs
This fixes https://github.com/OmniSharp/omnisharp-vscode/issues/1306
Basically, instead of letting `ScriptMetadataResolver` run entire reference resolution every time the semantic model is needed (which is how it is right now, and can sky rocket into GBs of memory usage, because it happens pretty much on every request into OmniSharp), we cache the results and reuse the same references over and over. This alleviates the memory usage.
When a new `#r` is added by user, it will still cause a jump in RAM but it would be much much smaller than what can be observed now.
=> cache ScriptMetadataResolver results

src/OmniSharp.Roslyn.CSharp/Services/Diagnostics/CodeCheckService.cs, src/OmniSharp.Script/ScriptProjectSystem.cs
- instead of excluding some diagnostics in the `CodeCheckService` (which was a hack), moved the suppression to the compilation options of the `ScriptProjectSystem`
- we do not need to suppress `CS8099` anymore, because we are setting `SourceFileResolver` on the compilation (beforehand, it was missing, which generated the diagnostic).
=> Script code check improvements

src/OmniSharp.DotNet/DotNetProjectSystem.cs
This keeps the DotNetProjectSystem continuing to load in the face of missing project references. It still reports the failure, but continues to load.
=> Fix null reference in DotNetProjectSystem when project reference is invalid

tests/TestUtility/TestAssets.TestProject.cs
Avoid `UnauthorizedAccessException` when cleaning up test directories if any of the contents are still locked by another process (such as 'dotnet').
Should address #806.
=> Add retry logic for test clean up

src/OmniSharp.Abstractions/OmniSharp.Abstractions.csproj, src/OmniSharp.Abstractions/Services/FileWatching/FileSystemWatcherWrapper.cs, src/OmniSharp.Abstractions/Services/IOmniSharpEnvironment.cs, src/OmniSharp.Abstractions/Utilities/PhysicalFileProviderExtensions.DisposableChangeCallback.cs, src/OmniSharp.Abstractions/Utilities/PhysicalFileProviderExtensions.PhysicalFileProviderWrapper.cs, src/OmniSharp.Abstractions/Utilities/PhysicalFileProviderExtensions.PollingFileChangeToken.cs, src/OmniSharp.Abstractions/Utilities/PhysicalFileProviderExtensions.cs, src/OmniSharp.DotNet/DotNetProjectSystem.cs, src/OmniSharp.Host/Internal/ConfigurationBuilderExtensions.cs, src/OmniSharp.Host/Program.cs, src/OmniSharp.Host/Services/OmniSharpEnvironment.cs, src/OmniSharp.Host/Startup.cs, src/OmniSharp.MSBuild/MSBuildProjectSystem.cs, src/OmniSharp.Script/ScriptProjectSystem.cs, tests/OmniSharp.Tests/OmniSharpEnvironmentFacts.cs, tests/TestUtility/TestAssets.cs
Recently, we've added support for reloading the user's local or global OmniSharp options when the relevant "omnisharp.json" file changes on disk. This causes the Microsoft.Extensions.Configuration API to start using a FileSystemWatcher. Unfortunately, this watcher looks for changes recursively, which can easily hit the [ulimit](https://ss64.com/osx/ulimit.html) for open files OSX just to watch for a couple of files.
This change adds a wrapper for PhysicalFileProvider that polls the file system every 2 seconds for just the files we care about.
This change also rationalizes some of the property names in OmniSharpEnvironment and fixes an issue where "Path" could be invalid if it was specified relative to the current working directory. E.g., if the OmniSharp is started with `-s OmniSharp.sln` …
=> Add PhysicalFileProvider.WrapForPolling() extension method to avoid using FileSystemWatcher

src/OmniSharp.MSBuild/MSBuildProjectSystem.cs, src/OmniSharp.MSBuild/ProjectFile/PackageReference.cs, src/OmniSharp.MSBuild/ProjectFile/ProjectFileInfo.cs, src/OmniSharp.MSBuild/ProjectFile/PropertyConverter.cs
When I did the initial punch through to get package references working in .csproj, I failed to account for version ranges. This should address the unresolved dependencies warnings reported in #795.
=> Handle package reference version ranges in .csproj files

src/OmniSharp.MSBuild/ProjectFile/ProjectFileInfo.cs
Fixes #795
It's possible for project references to appear twice within an MSBuild project after execution:
* As a ProjectReference item
* As a ReferencePath item with ReferenceSourceTarget="ProjectReference"
This change makes sure that ReferencePath items that were sourced from project references aren't added. We just use the project references, which is a better experience at designtime when the project is built.
Note: There was code that used to do this, but it was unintentionally removed in a refactoring a few months ago (by me -- oops!): https://github.com/OmniSharp/omnisharp-roslyn/commit/ef4b3838d39666ed5ca9780ea133bfdc08ff5844.
=> Ensure that MSBuildProjectSystem doesn't add project references twice

src/OmniSharp.Abstractions/Utilities/PlatformHelper.cs, src/OmniSharp.MSBuild/Extensions.cs, src/OmniSharp.MSBuild/MSBuildEnvironment.cs, src/OmniSharp.MSBuild/MSBuildHelpers.cs, src/OmniSharp.MSBuild/MSBuildProjectSystem.cs, src/OmniSharp.MSBuild/Options/MSBuildOptions.cs, src/OmniSharp.MSBuild/ProjectFile/ProjectFileInfo.PropertyNames.cs, src/OmniSharp.MSBuild/ProjectFile/ProjectFileInfo.cs, src/OmniSharp/Program.cs
Fixes https://github.com/OmniSharp/omnisharp-vscode/issues/1368
This change ensures that OmniSharp will use the MSBuild tools installed with Visual Studio 2017 if they're present on the machine. This allows OmniSharp to properly handle VS 2017 projects where the targets/tasks aren't include with OmniSharp's local MSBuild, such as WebApplication projects as reported in the bug listed above. If VS 2017 is not on the machine, OmniSharp will continue to use its local MSBuild which has a fallback to the Microsoft Build Tools for targets/tasks that it can't find.
I've also taken the opportunity to clean up a lot of the MSBuild environment initialized code and project file processing.
=> Clean up MSBuild environment initialization and allow it to use Visual Studio 2017 if it's present

src/OmniSharp.MSBuild/ProjectFile/PropertyConverter.cs
=> In MSBuildProjectSystem, add NoWarn values that do not parse as ushorts

build.cake, scripts/archiving.cake, src/OmniSharp/OmniSharp.csproj
Fixes #658 
Fixes #639
* Fix issue where de-duping during publish would skip a RID-specific publish step if that RID matched the current machine.
* Show version numbers in archives for Linux distros
* Add more Linux distros, namely ubuntu16.10, fedora24, and opensuse42.1
The additionally Linux distros is really a temporary measure since we'll be moving to an embedded Mono as part of #666. However, this will at least allow folks to build on those machines.
=> Build script work

src/OmniSharp.DotNetTest/VSTestManager.cs, test-assets/test-projects/NUnitTestProject/NUnitTestProject.csproj, test-assets/test-projects/NUnitTestProject/NuGet.config, tests/OmniSharp.DotNetTest.Tests/AbstractRunTestFacts.cs, tests/OmniSharp.DotNetTest.Tests/RunTestFacts.cs
Fixes https://github.com/OmniSharp/omnisharp-vscode/issues/1434
This change updates the test manager to pass dummy `RunSettings`, which allows the latest NUnit alpha to work (the NUnit test adapter does not handle null RunSettings). In addition, this updates our NUnit test project to use the latest NUnitTestAdapter CI build and uncomments the NUnit tests. When there's an official NUnitTestAdapter release, we'll want to update the test project to reference that and get rid of its NuGet.config.
cc @bernardbr and @rprouse
=> Get NUnit test running/debugging working

build.cake
Our build script finishes up by running the published OmniSharp bits with a timeout. This timeout is no longer long enough and the bits continue trying to run after the build is finished. I *believe* the reason for this is because the MSBuildProjectSystem now loads referenced projects outside of the directory OmniSharp is started with. More projects means more time processing, which causes the bits run longer. I'm increasing the timeout from 10 seconds to 30 seconds.
=> Increase the timeout specified when running published bits during build

tests/OmniSharp.Roslyn.CSharp.Tests/AbstractAutoCompleteTestFixture.cs, tests/OmniSharp.Roslyn.CSharp.Tests/DiagnosticsV2Facts.cs, tests/OmniSharp.Roslyn.CSharp.Tests/IntellisenseFacts.cs, tests/OmniSharp.Roslyn.CSharp.Tests/MetadataFacts.cs, tests/OmniSharp.Roslyn.CSharp.Tests/SnippetFacts.cs, tests/TestUtility/TestHelpers.cs
In the last PR I introduced a possibility to run our regular `AbstractTestFixture`-based tests against CSX files. 
In this PR I enabled a bunch of existing tests to run both against `.cs` files and against `.csx` files.
As a result there are 36 more tests.
=> Enable lots of tests to run for CSX

src/OmniSharp.Roslyn.CSharp/Services/Navigation/FindSymbolsService.cs, src/OmniSharp.Roslyn.CSharp/Services/Navigation/GotoDefinitionService.cs, tests/OmniSharp.Roslyn.CSharp.Tests/FindSymbolsFacts.cs, tests/OmniSharp.Roslyn.CSharp.Tests/GoToDefinitionFacts.cs
At the moment, when we have the following code:
```
public partial class MyClass 
{
public MyClass()
{
Method();
} 
partial void Method()
{
Console.WriteLine("foo");
}
}
public partial class MyClass  
{
partial void Method();
}
```
- using `ctrl+T` in VS Code, and typing `Method()` will always send the user to the one without body
- using "go to definition" in VS Code over the method invocation, will also always send the user to the one without body
This PR ensures that we send the caret to the version with body instead.
=> When finding partial methods, pick the one with body 

src/OmniSharp.MSBuild/MSBuildProjectSystem.cs, src/OmniSharp.MSBuild/ProjectFile/ProjectFileInfo.cs, src/OmniSharp.MSBuild/SolutionParsing/Constants.cs, src/OmniSharp.MSBuild/SolutionParsing/LineScanner.cs, src/OmniSharp.MSBuild/SolutionParsing/ProjectBlock.cs, src/OmniSharp.MSBuild/SolutionParsing/ProjectKind.cs, src/OmniSharp.MSBuild/SolutionParsing/SectionBlock.cs, src/OmniSharp.MSBuild/SolutionParsing/SolutionFile.cs
Fixes #839
Solutions generated by Unity often have multiple projects with the same name but, the MSBuild solution parsing API throws an error if there are any projects with a duplicated name (this error can be seen when passing a Unity solution to MSBuild at the command-line). However, Visual Studio is resilient to solutions where projects have the same name, so we should be too. This change restores the solution parsing logic copied from https://github.com/dotnet/roslyn.
=> Fix solution parsing for Unity solutions with multiple projects

src/OmniSharp.Roslyn.CSharp/Workers/Diagnostics/CSharpDiagnosticService.cs
This is a leftover from old scripting logic. It's not needed anymore because we now use the [default](https://github.com/OmniSharp/omnisharp-roslyn/blob/dev/src/OmniSharp.Script/ScriptProjectSystem.cs#L50) `#load` resolver.
=> removed suppressing CS1024 in scripts

build.cake, src/OmniSharp.Abstractions/Services/DotNetCliService.cs, src/OmniSharp.Abstractions/Services/DotNetInfo.cs, src/OmniSharp.MSBuild/Extensions.cs, src/OmniSharp.MSBuild/MSBuildEnvironment.cs, src/OmniSharp.MSBuild/MSBuildProjectSystem.cs, src/OmniSharp.MSBuild/ProjectFile/ProjectFileInfo.cs, tests/OmniSharp.MSBuild.Tests/ProjectFileInfoTests.cs, tests/OmniSharp.Tests/DotNetCliServiceFacts.cs, tools/packages.config
Fixes #765
This change stops deploying the .NET Core MSBuild SDKs with OmniSharp. That was a stop gap for .NET Core 1.0. However, with .NET Core 2.0 around the corner, it's time to stop deploying them and rely on the .NET Core SDK installed on the user's machine.
To locate the correct .NET Core SDK, we simply launch `dotnet --info` in the working directory of the project. That should properly handle the case where the SDK is specified in a global.json file. Then, we process the text returned by `dotnet --info` and locate the "Base Path" value. Combining this with "Sdks" should be the correct value.
=> Stop deploying SDKs with OmniSharp

src/OmniSharp.Script/ScriptContextModel.cs, src/OmniSharp.Script/ScriptHelper.cs, src/OmniSharp.Script/ScriptProjectSystem.cs, tests/OmniSharp.Roslyn.CSharp.Tests/IntellisenseFacts.cs, tests/TestUtility/TestHelpers.cs, tests/TestUtility/TestUtility.csproj
Replaced `InteractiveScriptGlobals` with `CommandLineScriptGlobals ` as CSX host object type. This is required, because CSI uses `CommandLineScriptGlobals` as host object for CSX script execution. `InteractiveScriptGlobals` is **only** used for REPL mode ([reference](https://github.com/dotnet/roslyn/blob/master/src/Scripting/Core/Hosting/CommandLine/CommandLineRunner.cs#L176-L196)), so naturally it makes sense to offer `CommandLineScriptGlobals` in OmniSharp intellisense. 
As a bonus, I extracted some of the project/compilation set up logic from `ScriptProjectSystem` into `ScriptHelper`. This way, it can be used in the tests as well, to ensure that the test set up is using the same logic as the project system would. This makes tests more reliable than before, where the code to create CSX …
=> replaced `InteractiveScriptGlobals` with `CommandLineScriptGlobals ` as CSX host object type

src/OmniSharp.MSBuild/Options/MSBuildOptions.cs, src/OmniSharp.MSBuild/ProjectFile/ProjectFileInfo.PropertyNames.cs, src/OmniSharp.MSBuild/ProjectFile/ProjectFileInfo.cs
This allows choosing other (than default) MsBuild configuration, e.g.
`MsBuild:Configuration=Release` `MsBuild:Platform=x64`, especially usable
for projects that are not using default (AnyCPU) platforms.
This relates to #202.
P.S. Do we need to add some tests on that one? Or is there any other particular way to override Configuration/Platform planned?
=> Expose MsBuild Configuration and Platform setting

build.json, src/OmniSharp.DotNetTest/Legacy/LegacyTestManager.cs, src/OmniSharp.DotNetTest/TestFrameworks/MSTestFramework.cs, src/OmniSharp.DotNetTest/TestFrameworks/TestFramework.cs, test-assets/test-projects/LegacyMSTestProject/NuGet.Config, test-assets/test-projects/LegacyMSTestProject/TestProgram.cs, test-assets/test-projects/LegacyMSTestProject/project.json, test-assets/test-projects/MSTestProject/MSTestProject.csproj, test-assets/test-projects/MSTestProject/TestProgram.cs, tests/OmniSharp.DotNetTest.Tests/AbstractGetTestStartInfoFacts.cs, tests/OmniSharp.DotNetTest.Tests/AbstractRunTestFacts.cs, tests/OmniSharp.DotNetTest.Tests/GetTestStartInfoFacts.cs, tests/OmniSharp.DotNetTest.Tests/LegacyGetTestStartInfoFacts.cs, tests/OmniSharp.DotNetTest.Tests/LegacyRunTestFacts.cs, tests/OmniSharp.DotNetTest.Tests/RunTestFacts.cs
Accompanying PR : https://github.com/OmniSharp/omnisharp-vscode/pull/1478
=> Support to run MSTest based tests.

src/OmniSharp.MSBuild/MSBuildProjectSystem.cs
This can result in incorrect package restore prompts in VS Code if the PackageReference name isn't a case-sensitive match of the actual package identity. For example, the restore prompt would appear for `<PackageReference Include="microsoft.codeanalysis"/>`
=> NuGet package identities should be compared case-insensitively

src/OmniSharp.MSBuild/MSBuildProjectSystem.cs
This fixes regression introduced in 2fbcc854f, where null info.BasePath
is passed to Path.Combine causing exception.
=> Fix Path.Combine exception in MSBuildProjectSystem.GetSdksPath

src/OmniSharp.Abstractions/Eventing/IEventEmitterExtensions.cs, src/OmniSharp.DotNet/DotNetProjectSystem.cs, src/OmniSharp.MSBuild/MSBuildProjectSystem.cs, src/OmniSharp.MSBuild/Resolution/PackageDependencyResolver.cs
Fixes https://github.com/OmniSharp/omnisharp-vscode/issues/1272
This change cleans up the logic (which had gotten kinda messy) that resolves MSBuild package references against a project's lock file. This also adds logging when package references can't be resolved, which should help diagnose situations where VS Code is getting restore prompts unnecessarily.
=> Clean up unresolved dependencies check

src/OmniSharp.Abstractions/Options/CodeActionOptions.cs, src/OmniSharp.Abstractions/Options/OmniSharpOptions.cs, src/OmniSharp.Abstractions/Options/RoslynExtensionsOptions.cs, src/OmniSharp.Abstractions/Services/IAssemblyLoader.cs, src/OmniSharp.Host/Services/AssemblyLoader.cs, src/OmniSharp.Roslyn.CSharp/CodeActions/ExternalCodeActionProvider.cs, src/OmniSharp.Roslyn.CSharp/Services/ExternalFeaturesHostServicesProvider.cs, src/OmniSharp.Roslyn.CSharp/Services/RoslynFeaturesHostServicesProvider.cs, src/OmniSharp/app.config
**Use case**: I'd like to load my own or 3rd party code actions into Omnisharp.
In this PR I added a possibility to add the following `CodeActions` node to the `omnisharp.json`.
```
{
"FormattingOptions": {
"IndentationSize": 2
},
"CodeActions": {
"LocationPaths": [
"C:/codeactions"
]
}
}
```
This will be picked up by `RoslynFeaturesHostServicesProvider` as a source location for loading assemblies containing refactorings and code fixes.
Because `omnisharp.json` is hierarchical (global/local) we can specify code actions on a global and local level if needed.
No I could download something like https://marketplace.visualstudio.com/items?itemName=josefpihrt.Roslynator2017 and extract its DLLs into `C:/codeactions` and profit. Relative and absolute paths are supported.
=> Added an option to configure a code actions folder

src/OmniSharp.Roslyn.CSharp/Services/Intellisense/CompletionItemExtensions.cs, src/OmniSharp.Roslyn.CSharp/Services/Intellisense/IntellisenseService.cs, src/OmniSharp.Roslyn/Extensions/SymbolExtensions.cs
This change fixes a regression where overloads would not be collapsed in the VS Code completion list. In addition, I added a couple of tweaks to ensure that we report the "EnumMember" and "Const" kinds.
=> Don't set completion text to full signature unless its override or partial method completion

src/OmniSharp.Host/Startup.cs
This is a breaking change, but of - I believe - small impact because it's very much a power feature to feed configuration into OmniSharp via environment variables (pretty much all current use cases would be via `omnisharp.json` or command line arguments).
However, we still allow to override any of the configuration via environment variables. 
Because we didn't prefix OmniSharp specific env variables, it can lead to unexpected results like https://github.com/OmniSharp/omnisharp-vscode/issues/1512. 
This PR requires that OmniSharp uses for configuration only environment variables following this format: `OMNISHARP_{name}`. 
Fixes https://github.com/OmniSharp/omnisharp-vscode/issues/1512.
=> Prefix OmniSharp-specific configuration environment variables with "OMNISHARP_"

src/OmniSharp.Roslyn.CSharp/Helpers/LocationExtensions.cs, src/OmniSharp.Roslyn.CSharp/Helpers/QuickFixExtensions.cs, src/OmniSharp.Roslyn.CSharp/Helpers/QuickFixHelper.cs, src/OmniSharp.Roslyn.CSharp/Services/Navigation/FindImplementationsService.cs, src/OmniSharp.Roslyn.CSharp/Services/Navigation/FindUsagesService.cs, src/OmniSharp.Roslyn.CSharp/Services/Navigation/GotoRegionService.cs, tests/OmniSharp.Roslyn.CSharp.Tests/FindImplementationFacts.cs
Replace the hand-rolled code used to find derived named type symbols with [SymbolFinder.FindDerivedClassesAsync](http://source.roslyn.io/#Microsoft.CodeAnalysis.Workspaces/FindSymbols/SymbolFinder_Hierarchy.cs,dbb07fa6e6e5a08c). That API didn't exist at the time of writing that feature - it was only added, I believe, for VS15.
Also enabled the find implementations code to run on CSX files.
=> Use SymbolFinder.FindDerivedClassesAsync inside "find implementations" endpoint

src/OmniSharp.Host/Services/AssemblyLoader.cs
Follow up to #848 
Added try/catch to the directory enumeration inside `AssemblyLoader`. It can throw due to a number of problems - directory not found, path too long, lack of permissions etc.
We should gracefully exit with no assemblies loaded and not crash OmniSharp.
=> Error handling when loading assemblies from an external folder

build.cake
I'm using this  [dotnet-cli](https://aur.archlinux.org/packages/dotnet-cli/ ) (binary Ubuntu-based)  package  on Arch Linux which works fine even though Arch Linux is not an _officially_ supported platform.
Thanks to [Stop deploying SDKs with OmniSharp](https://github.com/OmniSharp/omnisharp-roslyn/pull/847)  I'm one step closer to building this project on Arch Linux.
This commit improves error reporting from:
```
...
========================================
BuildEnvironment
========================================
Executing task: BuildEnvironment
/home/juergen/csharp/omnisharp-roslyn/.dotnet-legacy/dotnet-install.sh: line 70: VERSION_ID: unbound variable
Using .NET CLI
Version: 1.0.4
RID: ubuntu.16.10-x64
Base Path: /opt/dotnet/sdk/1.0.4
Finished executing task: BuildEnvironment …
```
=> Report and exit if installation of SDK fails

src/OmniSharp.Abstractions/Services/DotNetCliService.cs, src/OmniSharp.Abstractions/Services/DotNetInfo.cs
Fixes https://github.com/OmniSharp/omnisharp-vscode/issues/1532
=> Harden DotNetInfo a bit to handle situations when 'dotnet' doesn't launch properly or return data

src/OmniSharp.Abstractions/Models/v1/AutoComplete/AutoCompleteResponse.cs, src/OmniSharp.Roslyn.CSharp/Services/Intellisense/IntellisenseService.cs, tests/OmniSharp.Roslyn.CSharp.Tests/IntellisenseFacts.cs
Related to https://github.com/OmniSharp/omnisharp-vscode/issues/1524
=> Add IsSuggestionMode to AutoCompleteResponse for determining when the completion list should commit aggressively

src/OmniSharp.Abstractions/OmniSharp.Abstractions.csproj, src/OmniSharp.MSBuild/OmniSharp.MSBuild.csproj, tests/app.config
The NuGet 4.3.0 preview packages really aren't ready for prime time yet. Moving back to 4.0.0 packages.
=> Move back to NuGet 4.0.0 RTM packages

src/OmniSharp.Abstractions/Configuration.cs, src/OmniSharp.Abstractions/Utilities/DictionaryExtensions.cs, src/OmniSharp.Roslyn.CSharp/CodeActions/ExternalCodeActionProvider.cs, src/OmniSharp.Roslyn.CSharp/CodeActions/RoslynCodeActionProvider.cs, src/OmniSharp.Roslyn.CSharp/Services/ExternalFeaturesHostServicesProvider.cs, src/OmniSharp.Roslyn.CSharp/Services/Refactoring/GetCodeActionService.cs, src/OmniSharp.Roslyn.CSharp/Services/Refactoring/RunCodeActionService.cs, src/OmniSharp.Roslyn.CSharp/Services/Refactoring/V2/BaseCodeActionService.cs, src/OmniSharp.Roslyn.CSharp/Services/RoslynFeaturesHostServicesProvider.cs, src/OmniSharp.Roslyn.CSharp/Workers/Refactoring/FixUsingsWorker.cs, src/OmniSharp.Roslyn/Services/AbstractCodeActionProvider.cs, src/OmniSharp.Roslyn/Services/ICodeActionProvider.cs
This change reworks how we compute code fixes and refactorings. Much of this is just basic refactoring and clean up, but there are substantial changes to to code fixes are computed. Now, we'll return code fixes when there are multiple diagnostics with overlapping spans. For example, consider this scenario:
```C#
class C
{
void M()
{
StringBuilder
}
}
```
There are three diagnostics at the position immediately following `StringBuilder`:
1. CS1001: Identifier expected
2. CS1002: ; expected
3. CS0246: The type or name 'StringBuilder' could not be found
The problem is that the first two diagnostics have a zero-width span immediately following `StringBuilder`, but the last diagnostic has the same span as `StringBuilder`. Previously, if the code action service was called with the line and …
=> Rework code action service

src/OmniSharp.Abstractions/Configuration.cs, src/OmniSharp.DotNet/OmniSharp.DotNet.csproj, src/OmniSharp.DotNetTest/OmniSharp.DotNetTest.csproj, src/OmniSharp.Roslyn.CSharp/OmniSharp.Roslyn.CSharp.csproj, src/OmniSharp.Roslyn/BufferManager.cs, src/OmniSharp.Roslyn/OmniSharp.Roslyn.csproj, src/OmniSharp.Script/OmniSharp.Script.csproj, tests/OmniSharp.Stdio.Tests/OmniSharp.Stdio.Tests.csproj, tests/TestUtility/TestUtility.csproj
This change also tweaks the BufferManager to fix some bugs that the latest Roslyn now exposes (an OmniSharp test started failing without this change).
=> Update Roslyn dependency to 2.3.0-beta2

src/OmniSharp.DotNet/DotNetProjectSystem.cs, src/OmniSharp.Host/Services/WorkspaceHelper.cs, src/OmniSharp.Host/Startup.cs, tests/TestUtility/OmniSharpTestHost.cs
At the moment we had [logic in place](https://github.com/OmniSharp/omnisharp-roslyn/blob/dev/src/OmniSharp.DotNet/DotNetProjectSystem.cs#L105-L114) that allowed users to disable the "legacy" `project.json` project system - using a configuration flag from `omnisharp.json` or any other of the several configuration sources we have in place.
For consistency, this PR extends this concept to allow the `"enabled": false` flag to be used against MsBuild and Script project systems too. 
It can help for example performance, as the user can easily (even globally) switch off scanning of the file system done by these project systems.
I also moved out some of the logic from the `Startup` class because, well, SRP.
=> added support for disabling any project system via configuration

src/OmniSharp.Abstractions/OmniSharp.Abstractions.csproj, src/OmniSharp.DotNet/OmniSharp.DotNet.csproj, src/OmniSharp.DotNetTest/OmniSharp.DotNetTest.csproj, src/OmniSharp.Host/OmniSharp.Host.csproj, src/OmniSharp.MSBuild/OmniSharp.MSBuild.csproj, src/OmniSharp.Nuget/OmniSharp.Nuget.csproj, src/OmniSharp.Plugins/OmniSharp.Plugins.csproj, src/OmniSharp.Roslyn.CSharp/OmniSharp.Roslyn.CSharp.csproj, src/OmniSharp.Roslyn/OmniSharp.Roslyn.csproj, src/OmniSharp.Script/OmniSharp.Script.csproj, src/OmniSharp.Stdio/OmniSharp.Stdio.csproj, src/OmniSharp/OmniSharp.csproj, tests/OmniSharp.DotNet.Tests/OmniSharp.DotNet.Tests.csproj, tests/OmniSharp.DotNetTest.Tests/OmniSharp.DotNetTest.Tests.csproj, tests/OmniSharp.MSBuild.Tests/OmniSharp.MSBuild.Tests.csproj, tests/OmniSharp.Roslyn.CSharp.Tests/OmniSharp.Roslyn.CSharp.Tests.csproj, tests/OmniSharp.Stdio.Tests/OmniSharp.Stdio.Tests.csproj, tests/OmniSharp.Tests/OmniSharp.Tests.csproj, tests/OmniSharp.Tests/UpdateBufferFilterFacts.cs, tests/TestUtility/TestUtility.csproj
Most project files in this repo contain a common mistake:
WarningsAsErrors is a list of warnings that should be treated as errors.
TreatWarningsAsErrors is the boolean that lifts all warnings to errors.
FYI - 
This introduces a compiler error RS1014 in one of the tests that was previously only a warning.
> UpdateBufferFilterFacts.cs(91,17): error RS1014: 'Solution' is immutable and 'AddDocument' will not have any effect on it. Consider using the return value from 'AddDocument'.
Fixing the compiler error causes the test to fail.
```
Failed   OmniSharp.Tests.UpdateBufferFilterFacts.UpdateBuffer_TransientDocumentsDisappearWhenProjectAddsThem
Error Message:
Assert.Equal() Failure
Expected: 2
Actual:   3
Stack Trace:
at OmniSharp.Tests.UpdateBufferFilterFacts.<UpdateBuffer_TransientDocumentsDis …
```
=> Change WarningsAsErrors => TreatWarningsAsErrors

build.cake, scripts/common.cake, scripts/msbuild.cake
Big changes:
* Don't produce so much build output by using custom IO helpers. You can still get all of the "copy file blah to baz" by passing the `--verbosity Diagnostic` flag.
* Refactor the MSBuild setup logic to be sensible and reduce the overall size of build.cake.
=> Clean up build log

CHANGELOG.md, src/OmniSharp.Script/ScriptProjectSystem.cs
This PR reverts the change introduced in https://github.com/OmniSharp/omnisharp-roslyn/commit/cd7b3c369b7c77540aee5d8eec7924a8c59d414d 
Functionally everything is the same.
The problem is when we switched to using `IAssemblyLoader`, we would now throw (since `IAssemblyLoader` rethrows the exceptions it encounters) when i.e. `System.Runtime` is not found and we'd like to avoid that. For simplicity, it makes sense for us to always try to load `System.Runtime` if we can. 
The alternative wold be to make `IAssemblyLoader` not rethrow anymore, but it would still log errors into the command line which is not good. 
Due to this issue the scripting project system for desktop is broken on Windows at the moment.
=> regression fix - revert cd7b3c369b7c77540aee5d8eec7924a8c59d414d

NuGet.Config, tests/OmniSharp.DotNet.Tests/OmniSharp.DotNet.Tests.csproj, tests/OmniSharp.DotNetTest.Tests/AbstractGetTestStartInfoFacts.cs, tests/OmniSharp.DotNetTest.Tests/GetTestStartInfoFacts.cs, tests/OmniSharp.DotNetTest.Tests/OmniSharp.DotNetTest.Tests.csproj, tests/OmniSharp.MSBuild.Tests/GlobalSuppressions.cs, tests/OmniSharp.MSBuild.Tests/OmniSharp.MSBuild.Tests.csproj, tests/OmniSharp.MSBuild.Tests/WorkspaceInformationTests.cs, tests/OmniSharp.Roslyn.CSharp.Tests/DiagnosticsV2Facts.cs, tests/OmniSharp.Roslyn.CSharp.Tests/OmniSharp.Roslyn.CSharp.Tests.csproj, tests/OmniSharp.Roslyn.CSharp.Tests/SignatureHelpFacts.cs, tests/OmniSharp.Stdio.Tests/OmniSharp.Stdio.Tests.csproj, tests/OmniSharp.Stdio.Tests/StdioServerFacts.cs, tests/OmniSharp.Tests/GlobalSuppressions.cs, tests/OmniSharp.Tests/MarkupCodeFacts.cs, tests/OmniSharp.Tests/OmniSharp.Tests.csproj, tests/OmniSharp.Tests/ZeroBasedIndexConverterFacts.cs, tests/TestUtility/TestUtility.csproj, tests/app.config
This PR updates xUnit to fix running tests in VS 2017 per https://github.com/Microsoft/vstest/issues/811. Because we're updating to the latest xUnit 2.3.0, this change also includes fixes for errors introduced by the new xUnit Roslyn analyzers. The suggested fixes all looked to be righteous to me, so I went ahead and made them.
Note that this change also requires a new binding redirect for the tests to run properly. This is because our test fixtures pull in Microsoft.Extensions.Logging.Abstractions, 1.1.0, but NuGet is pulling in 1.1.1 due to the `Dotnet.Script.NuGetMetadataResolver` dependency.
=> Update xUnit to fix test runner in VS 2017

src/OmniSharp.MSBuild/MSBuildProjectSystem.cs, src/OmniSharp.MSBuild/SolutionParsing/GlobalSectionBlock.cs, src/OmniSharp.MSBuild/SolutionParsing/InvalidSolutionFileException.cs, src/OmniSharp.MSBuild/SolutionParsing/ProjectBlock.cs, src/OmniSharp.MSBuild/SolutionParsing/ProjectSectionBlock.cs, src/OmniSharp.MSBuild/SolutionParsing/Property.cs, src/OmniSharp.MSBuild/SolutionParsing/Scanner.cs, src/OmniSharp.MSBuild/SolutionParsing/SectionBlock.cs, src/OmniSharp.MSBuild/SolutionParsing/SolutionFile.cs, tests/OmniSharp.MSBuild.Tests/SolutionParsingTests.cs
It turns out that my recent change to use the MSBuild solution parsing API (for a second time) has broken Unity solutions. In this particular case, the MSBuild API throws if a solution file contains multiple projects with the same name, which is how Unity solutions are generated. Thanks to @Leopotam for reporting this issue!
The MSBuild API is much more restrictive about the format of a solution file than Visual Studio. I suppose that makes sense given that MSBuild can fail fast if a solution file is invalid. However, an IDE must be more resilient against faults. So, I've written a brand new solution parser from scratch. It is heavily derived from the [parser in MSBuild](https://github.com/Microsoft/msbuild/blob/master/src/Build/Construction/Solution/SolutionFile.cs).
Fixes …
=> Fix solution parsing (again!)

build.cake, build.json, src/OmniSharp.Abstractions/Utilities/PlatformHelper.cs, src/OmniSharp.MSBuild/MSBuildEnvironment.cs, src/OmniSharp.MSBuild/Options/MSBuildOptions.cs, src/OmniSharp.MSBuild/ProjectFile/ProjectFileInfo.PropertyNames.cs, src/OmniSharp.MSBuild/ProjectFile/ProjectFileInfo.cs, tools/packages.config
I'm cherry-picking this change from https://github.com/OmniSharp/omnisharp-roslyn/pull/915, since it's unrelated to that PR.
Fixes #892 
Fixes https://github.com/OmniSharp/omnisharp-vscode/issues/1597
Fixes https://github.com/OmniSharp/omnisharp-vscode/issues/1624
Fixes https://github.com/OmniSharp/omnisharp-vscode/issues/1396
Related PR: https://github.com/mono/msbuild/pull/22
=> Add logic to set MSBuildExtensionsPath to Mono's xbuild directory

src/OmniSharp.Abstractions/Utilities/PlatformHelper.cs
Ensure that we don't pass null into `Path.Combine(...)`.
cc @cesarbs
=> Fail gracefully if Mono lib dir is null

src/OmniSharp.Abstractions/OmniSharp.Abstractions.csproj, src/OmniSharp.DotNet/OmniSharp.DotNet.csproj, src/OmniSharp.DotNetTest/OmniSharp.DotNetTest.csproj, src/OmniSharp.Host/OmniSharp.Host.csproj, src/OmniSharp.MSBuild/OmniSharp.MSBuild.csproj, src/OmniSharp.Nuget/OmniSharp.Nuget.csproj, src/OmniSharp.Plugins/OmniSharp.Plugins.csproj, src/OmniSharp.Roslyn.CSharp/OmniSharp.Roslyn.CSharp.csproj, src/OmniSharp.Roslyn/OmniSharp.Roslyn.csproj, src/OmniSharp.Script/OmniSharp.Script.csproj, src/OmniSharp.Stdio/OmniSharp.Stdio.csproj, src/OmniSharp/OmniSharp.csproj, tests/OmniSharp.DotNet.Tests/OmniSharp.DotNet.Tests.csproj, tests/OmniSharp.DotNetTest.Tests/OmniSharp.DotNetTest.Tests.csproj, tests/OmniSharp.MSBuild.Tests/OmniSharp.MSBuild.Tests.csproj, tests/OmniSharp.Roslyn.CSharp.Tests/OmniSharp.Roslyn.CSharp.Tests.csproj, tests/OmniSharp.Stdio.Tests/OmniSharp.Stdio.Tests.csproj, tests/OmniSharp.Tests/OmniSharp.Tests.csproj, tests/TestUtility/TestUtility.csproj, tests/app.config, tools/packages.config
This PR also includes an update to System.Composition, 1.0.31, since Roslyn now targets that instead of Microsoft.Composition, 1.0.30. That also allows us to remove our PackageTargetFallback.
=> Update to latest 2.3.1 Roslyn packages

src/OmniSharp/app.config
Follow up to #930 
At the moment if you start Omnisharp, and you have a folder with external code actions configured, it will fail to start:
```
C:\code\omnisharp-roslyn>"C:\code\omnisharp-roslyn\artifacts\publish\OmniSharp\default\net46\OmniSharp.exe" -s C:\code\omnisharp-roslyn\src\OmniSharp --stdio
OmniSharp: -s C:\code\omnisharp-roslyn\src\OmniSharp --stdio
System.IO.FileNotFoundException: Could not load file or assembly 'System.Composition.AttributedModel, Version=1.0.27.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
File name: 'System.Composition.AttributedModel, Version=1.0.27.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
at System.ModuleHandle.ResolveType(RuntimeModule module, Int32 typeToken, …
```
=> added System.Composition binding redirects to omnisharp.exe

src/OmniSharp.MSBuild/MSBuildEnvironment.cs, src/OmniSharp.MSBuild/Options/MSBuildOptions.cs, src/OmniSharp.MSBuild/ProjectFile/ProjectFileInfo.PropertyNames.cs, src/OmniSharp.MSBuild/ProjectFile/ProjectFileInfo.cs
Fixes #936
Fixes https://github.com/OmniSharp/omnisharp-vscode/issues/1676
This PR addresses a few issues with using MSBuild for execution on Mono:
1. There was a bug introduced where we would set `MSBuildExtensionsPath` to `$mono_prefix/xbuild` in situations that caused things to break. OmniSharp will now only do that if `$mono_prefix/msbuild` and `$mono_prefix/xbuild/15.0` exist. If we set it when those paths don't exist, it's likely that we'll lose the targets to properly handle .NET Core projects.
2. The Mono targets have hardcoded a redirect of `CscToolPath` to a different location. Unfortunately, that breaks OmniSharp when we call the `Compile` target, since the `Csc` task requires a correct path to `csc.exe`. So, we override `CscToolsPath` and set it to point to our own copy of …
=> Msbuild project fixes

CHANGELOG.md, src/OmniSharp.MSBuild/MSBuildEnvironment.cs, src/OmniSharp.MSBuild/Options/MSBuildOptions.cs, src/OmniSharp.MSBuild/ProjectFile/ProjectFileInfo.PropertyNames.cs, src/OmniSharp.MSBuild/ProjectFile/ProjectFileInfo.cs
We set CscToolPath to the Roslyn directory that we include with OmniSharp to ensure that the Compile task can run. However, we failed to set CscToolExe to "csc.exe". So, if a project or target was using something else (like "mcs.exe"), OmniSharp fails to process the project.
Note: "csc.exe" is never actually called. However, MSBuild tool tasks validate that the tool (in this case, "csc.exe") actually exist on disk. Since _our_ "csc.exe" will always be there, this should be quite safe.
=> Ensure that CscToolExe is set to 'csc.exe'

src/OmniSharp.Abstractions/Services/IAssemblyLoader.cs, src/OmniSharp.Host/Services/AssemblyLoader.cs
- Makes it possible to load single assembly from path.
- Make private method in `AssemblyLoader` public.
- Rename to `LoadFrom` to align with `LoadAllFrom`
=> Adds LoadFrom to IAssemblyLoader

CHANGELOG.md, src/OmniSharp.Roslyn/HostServicesAggregator.cs, tests/OmniSharp.Roslyn.CSharp.Tests/BufferFacts.cs, tests/OmniSharp.Roslyn.CSharp.Tests/BufferManagerFacts.cs, tests/TestUtility/TestHelpers.cs
Fixed a bug where an external code action DLL with missing dependencies would crash OmniSharp. This can happen when - for example - the refactoring DLL is built in a way that it takes dependency on Visual Studio DLLs or GAC DLLs that don't exist on the machine where OmniSharp runs.
If that happens, we will now just log a warning and continue, rather than crashing OmniSharp.
=> Don't crash when encountering external code action DLL with missing dependencies 

CHANGELOG.md, src/OmniSharp.Abstractions/Services/DotNetCliService.cs, src/OmniSharp.DotNetTest/DebugSessionManager.cs, src/OmniSharp.DotNetTest/Legacy/LegacyTestManager.cs, src/OmniSharp.DotNetTest/Models/DebugTestGetStartInfoRequest.cs, src/OmniSharp.DotNetTest/Models/GetTestStartInfoRequest.cs, src/OmniSharp.DotNetTest/Models/RunTestRequest.cs, src/OmniSharp.DotNetTest/OmniSharp.DotNetTest.csproj, src/OmniSharp.DotNetTest/Services/DebugTestService.cs, src/OmniSharp.DotNetTest/Services/GetTestStartInfoService.cs, src/OmniSharp.DotNetTest/Services/RunTestService.cs, src/OmniSharp.DotNetTest/TestManager.cs, src/OmniSharp.DotNetTest/VSTestManager.cs
Fixes https://github.com/OmniSharp/omnisharp-roslyn/issues/942 and https://github.com/OmniSharp/omnisharp-roslyn/issues/944
* When running a test via 'dotnet vstest' support, pass "--no-restore" when building with the .NET CLI to ensure that implicit restore does not run, making build a bit faster.
* Add support for specifying the 'TargetFrameworkVersion' to the 'dotnet vstest' endpoints.
=> A couple of fixes to test support

CHANGELOG.md, src/OmniSharp.Roslyn.CSharp/Services/Navigation/GotoDefinitionService.cs, tests/OmniSharp.Roslyn.CSharp.Tests/GoToDefinitionFacts.cs
At the moment, when you try to go to definition on a namespace, we throw a NullReferenceException. 
OmniSharp doesn't crash but a nasty exception shows up in the logs.
=> Do not throw NullReferenceException when trying to "go to definition" on a namespace

Common.props, OmniSharp.sln, build.cake, build/Packages.props, build/Settings.props, scripts/common.cake, src/Directory.Build.props, src/OmniSharp.Abstractions/OmniSharp.Abstractions.csproj, src/OmniSharp.DotNet/OmniSharp.DotNet.csproj, src/OmniSharp.DotNetTest/OmniSharp.DotNetTest.csproj, src/OmniSharp.Host/OmniSharp.Host.csproj, src/OmniSharp.Http/OmniSharp.Http.csproj, src/OmniSharp.MSBuild/OmniSharp.MSBuild.csproj, src/OmniSharp.Nuget/OmniSharp.Nuget.csproj, src/OmniSharp.Plugins/OmniSharp.Plugins.csproj, src/OmniSharp.Roslyn.CSharp/OmniSharp.Roslyn.CSharp.csproj, src/OmniSharp.Roslyn/OmniSharp.Roslyn.csproj, src/OmniSharp.Script/OmniSharp.Script.csproj, src/OmniSharp.Stdio/OmniSharp.Stdio.csproj, tests/Directory.Build.props, tests/OmniSharp.DotNet.Tests/OmniSharp.DotNet.Tests.csproj, tests/OmniSharp.DotNetTest.Tests/OmniSharp.DotNetTest.Tests.csproj, tests/OmniSharp.Http.Tests/OmniSharp.Http.Tests.csproj, tests/OmniSharp.MSBuild.Tests/OmniSharp.MSBuild.Tests.csproj, tests/OmniSharp.Roslyn.CSharp.Tests/OmniSharp.Roslyn.CSharp.Tests.csproj, tests/OmniSharp.Stdio.Tests/OmniSharp.Stdio.Tests.csproj, tests/OmniSharp.Tests/OmniSharp.Tests.csproj, tests/TestUtility/TestUtility.csproj
This PR makes several changes to how our projects are defined and where binaries are built to:
1. Package versions are defined in a single Package.props MSBuild file.
2. Shared project properties (such as TreatWarningsAsErrors) are defined in a single Settings.pop MSBuild file.
3. All `bin` and `obj` folders are now located in a top-level `bin` folder rather than under each project. These are laid out like so:
* `bin` -> `bin\$(Configuration)\${MSBuildProjectName`. So, building `OmniSharp.Roslyn` in the Debug configuration builds to `$omnisharp_root\bin\Debug\OmniSharp.Roslyn`.
* `obj` -> `bin\obj\${MSBuildProjectName)`. So, the intermediate output path when building `OmniSharp.Roslyn` in Debug configuration is `$omnisharp_root\bin\obj\OmniSharp.Roslyn`
=> Refactor package references, shared project properties, and build output

src/OmniSharp.Roslyn.CSharp/Helpers/DiagnosticExtensions.cs, src/OmniSharp.Roslyn.CSharp/Helpers/QuickFixExtensions.cs, src/OmniSharp.Roslyn.CSharp/Services/Diagnostics/CodeCheckService.cs, src/OmniSharp.Roslyn.CSharp/Workers/Diagnostics/CSharpDiagnosticService.cs, src/OmniSharp.Stdio/Host.cs
With the merge of #854 we overlooked the fact that we lost request/response logging when running over STDIO. That logic was handled by `LoggingMiddleware` which is now part of the HTTP host. This PR restores the old functionality of logging of request/response packets for log levels debug and lower (this is what shows up i.e. in "omnisharp log" panel in VS Code). This is quite useful for debugging what is going on.
As a bonus, I removed some code duplication between `CodeCheckService` and `CSharpDiagnosticService`
=> Restore request/response logging in STDIO

.travis.yml
It's not necessary to use the Mono beta channel in Travis any longer since the latest stable release has all of the changes we depend on.
=> Use latest Mono rather than beta in Travis

NuGet.Config, build/Packages.props, tests/OmniSharp.DotNetTest.Tests/RunTestFacts.cs, tests/OmniSharp.MSBuild.Tests/ProjectFileInfoTests.cs, tests/OmniSharp.MSBuild.Tests/SolutionParsingTests.cs, tests/OmniSharp.Roslyn.CSharp.Tests/BufferManagerFacts.cs, tests/OmniSharp.Roslyn.CSharp.Tests/DiagnosticsFacts.cs, tests/OmniSharp.Roslyn.CSharp.Tests/DiagnosticsV2Facts.cs, tests/OmniSharp.Roslyn.CSharp.Tests/FindReferencesFacts.cs, tests/OmniSharp.Roslyn.CSharp.Tests/GoToFileFacts.cs, tests/OmniSharp.Roslyn.CSharp.Tests/GoToRegionFacts.cs, tests/OmniSharp.Roslyn.CSharp.Tests/RenameFacts.cs, tests/OmniSharp.Roslyn.CSharp.Tests/SignatureHelpFacts.cs, tests/OmniSharp.Roslyn.CSharp.Tests/SnippetFacts.cs, tests/OmniSharp.Roslyn.CSharp.Tests/StructureFacts.cs, tests/OmniSharp.Tests/MarkupCodeFacts.cs, tools/packages.config
This should fix the failed build in #971
=> Update to latest xUnit and fix up tests affected by analyzers

NuGet.Config, build.cake, build.json, src/OmniSharp.MSBuild/AssemblyInfo.cs, src/OmniSharp.MSBuild/MSBuildEnvironment.cs, src/OmniSharp.MSBuild/MSBuildProjectSystem.cs, src/OmniSharp.MSBuild/ProjectFile/ProjectFileInfo.cs, tests/OmniSharp.MSBuild.Tests/ProjectFileInfoTests.cs, tests/TestUtility/OmniSharpTestHost.cs, tools/packages.config
Currently, we launch `dotnet --info` for every MSBuild project. This allows us to detect the .NET Core SDK that is used for that project without having to replicate a lot of code to search for a `global.json`, or look in various places. Once we've have the output of `dotnet --info`, we look for the "Base Path" property and use that to decide where the location of the "Sdks" are within the relevant .NET Core SDK's directory. Once we've got that, we set the `MSBuildSDKsPath` environment variable to tell MSBuild where the SDKs are before we load the project.
This approach has several problems:
1. Setting an environment variable is fragile! It means that we can't load MSBuild projects in parallel because the projects might target a different .NET Core SDK. Also, another process (even another …
=> Use MSBuild SDK Resolvers

src/OmniSharp.Abstractions/Models/v1/AutoComplete/AutoCompleteRequest.cs, src/OmniSharp.Roslyn.CSharp/Services/Intellisense/CompletionItemExtensions.cs, src/OmniSharp.Roslyn.CSharp/Services/Intellisense/IntellisenseService.cs, tests/OmniSharp.Roslyn.CSharp.Tests/AbstractAutoCompleteTestFixture.cs, tests/OmniSharp.Roslyn.CSharp.Tests/IntellisenseFacts.cs
...if object creation completion is available. Currently does not
attempt to implement any preselection-like experience.
Depends on https://github.com/OmniSharp/omnisharp-vscode/pull/1776
=> Trigger completion on space if object creation completion is available

BUILD.md, build.cake, scripts/platform.cake
This fixes two issues building Omnisharp on CentOS 7:
System.Version needs a major and minor version or it refuses to parse it. For Linux distributions with a single major-only version in /etc/os-release, add a ".0" suffix to the version.
Add a documentation note about `msbuild` being a dependency as well since it is sometimes not included with the default mono installation.
=> Fix build on CentOS 7

build.cake
Without this, we get warnings about msbuild not finding the desired SDK that we just installed because `dotnet` was not added to PATH.
See https://github.com/OmniSharp/omnisharp-roslyn/issues/984
=> Add any installed SDKs to PATH

src/OmniSharp.Roslyn/Extensions/StringExtensions.cs, tests/OmniSharp.Roslyn.CSharp.Tests/FindSymbolsFacts.cs, tests/OmniSharp.Roslyn.CSharp.Tests/IntellisenseFacts.cs
Given the following code:
```
public class Options { }
public interface IConfigurationOptions { }
public class ConfigurationOptions : IConfigurationOptions { }
```
When passing `Opt` into symbol lookup or completion service, we will only return `Options`, which is not the optimal user experience.
In fact, this is not in line with the Visual Studio behavior, where in both symbol lookup and completion, `opt` returns all 3 possibilities.
This PR changes a subset match of length longer than 1 to be valid when verifying symbol/completion subsequences, resulting in much better experience.
=> Consider subset match valid for symbol lookups and completions

.gitattributes
Related to #989, this forces `LF` to be used as the EOL character on `.sh` scripts, if the contributor was using `autocrlf = true` in his `.gitconfig` when cloning the project, it would cause the errors mentioned in the issue.
Having this info in `.gitattributes` will force the correct EOL character on checkin and checkout.
=> Force LF EOL for sh scripts

README.md
Remove all mentions to `dev` branch that no longer exists.
Small things to reduce friction to new contributors :)
=> Remove dev branch from README

build/Packages.props, src/OmniSharp.Abstractions/Configuration.cs, src/OmniSharp.Http/app.config, src/OmniSharp.Stdio/app.config, tests/app.config
Also updated `Dotnet.Script.DependencyModel` packages to 0.2.0 as they fixed some bugs with regards to parsing `#r` nuget references in scripts (i.e. UNC path support).
=> Updated to Roslyn 2.4.0

src/OmniSharp.Host/MSBuild/Discovery/Providers/VisualStudioInstanceProvider.cs
Since #998 I've been getting:
```
System.PlatformNotSupportedException: Operation is not supported on this platform.
at OmniSharp.MSBuild.Discovery.Interop.GetSetupConfiguration () [0x0000a] in <fc86425b83fa4820a94c3447774fdb30>:0
at OmniSharp.MSBuild.Discovery.Providers.VisualStudioInstanceProvider.GetInstances () [0x0000e] in <fc86425b83fa4820a94c3447774fdb30>:0
at OmniSharp.MSBuild.Discovery.MSBuildLocator.GetInstances () [0x0001e] in <fc86425b83fa4820a94c3447774fdb30>:0
at OmniSharp.CompositionHostBuilder.Build () [0x00053] in <fc86425b83fa4820a94c3447774fdb30>:0
at OmniSharp.Stdio.Host..ctor (System.IO.TextReader input, OmniSharp.Stdio.Services.ISharedTextWriter writer, OmniSharp.IOmniSharpEnvironment environment, Microsoft.Extensions.Configuration.IConfiguration configuration, …
```
=> disable VisualStudioInstanceProvider on mono

build.cake, build.json, scripts/common.cake, src/OmniSharp.MSBuild/ProjectFile/ProjectFileInfo.PropertyNames.cs, src/OmniSharp.MSBuild/ProjectFile/ProjectFileInfo.TargetNames.cs, src/OmniSharp.MSBuild/ProjectFile/ProjectFileInfo.cs, test-assets/test-projects/AntlrGeneratedFiles/Grammar.g4, test-assets/test-projects/AntlrGeneratedFiles/Program.cs, test-assets/test-projects/AntlrGeneratedFiles/Test.csproj, tests/OmniSharp.MSBuild.Tests/WorkspaceInformationTests.cs, tests/TestUtility/ConditionalFactAttribute.cs
Fixes https://github.com/OmniSharp/omnisharp-vscode/issues/1822
This change may fix several issues, but it particular it fixes files not appearing in the OmniSharpWorkspace that were generated through Antlr. Essentially, we had failed to set the `BuildingInsideVisualStudio` property when running a design-time build in OmniSharp. Antlr uses this property to determine whether the antlr design-time grammar compilation target runs ([link](https://github.com/tunnelvisionlabs/antlr4cs/blob/f62010862bd1e38b3c6e3940931dcde949bdaa91/runtime/CSharp/Antlr4BuildTasks/Antlr4.net40.targets#L95)).
In addition, there a couple of other tweaks in this change that are somewhat unrelated:
1. There was a type in the `ProvideCommandLineArgs` property.
2. We should run two targets: `Compile` and `CoreCompile`. …
=> Fix design-time build for Antlr-generated files

build.json, src/OmniSharp.MSBuild/MSBuildProjectSystem.cs, src/OmniSharp.MSBuild/ProjectFile/ProjectFileInfo.MetadataNames.cs, src/OmniSharp.MSBuild/ProjectFile/ProjectFileInfo.cs, test-assets/test-projects/CSharpAndFSharp/CSharpAndFSharp.sln, test-assets/test-projects/CSharpAndFSharp/csharp-console/Program.cs, test-assets/test-projects/CSharpAndFSharp/csharp-console/csharp-console.csproj, test-assets/test-projects/CSharpAndFSharp/fsharp-lib/Library.fs, test-assets/test-projects/CSharpAndFSharp/fsharp-lib/fsharp-lib.fsproj, tests/OmniSharp.MSBuild.Tests/WorkspaceInformationTests.cs
Fixes https://github.com/OmniSharp/omnisharp-vscode/issues/371 and https://github.com/OmniSharp/omnisharp-vscode/issues/1829
This fixes a long-standing problem where C# projects would attempt to load project references
to non-C# projects. This is related to the problem on not adding file references for C# project references
to avoid duplicate references. Now, we're a bit more selective when we decide to throw out a project or file
reference: We check the file path and see if it ends with ".csproj".
I'll be porting this change into https://github.com/OmniSharp/omnisharp-roslyn/pull/1003 as well.
=> Fix issue with C# projects referencing F# projects

src/OmniSharp.LanguageServerProtocol/Handlers/RenameHandler.cs, src/OmniSharp.LanguageServerProtocol/LanguageServerHost.cs
This pull request adds RenameHandler to #968 
@david-driscoll Let me know what should return in the event the underlying service returns an error.  Should the handler throw an exception or just return null?
=> Adds RenameHandler

src/OmniSharp.Abstractions/AssemblyInfo.cs, src/OmniSharp.Http/Program.cs, src/OmniSharp.Stdio/Program.cs
This change fixes an issue where the --zero-based-indices command
line argument was not being passed along to Configuration.ZeroBasedIndices
so that location/range serialization uses zero-based indices. This
fix wires up the argument to configure the serializer correctly.
=> Use --zero-based-indices argument in Stdio and Http hosts

CHANGELOG.md, src/OmniSharp.Abstractions/Utilities/Platform.cs, src/OmniSharp.Host/CompositionHostBuilder.cs, src/OmniSharp.Host/MSBuild/Discovery/Extensions.cs, src/OmniSharp.Host/MSBuild/Discovery/Providers/MonoInstanceProvider.cs, src/OmniSharp.Http/Startup.cs, src/OmniSharp.Stdio/Host.cs
Fixes #1011 
Fixes #1014 
This PR addresses a couple of MSBuild discovery issues:
1. Don't use Mono MSBuild if `Microsoft.Build.dll` is missing. This can happen on Linux layouts of Mono when the user hasn't installed the `msbuild` package yet.
2. Don't use Visual Studio 2017 MSBuild if it is VS 2017 RTM. In this case, the user is encouraged to update VS 2017.
=> Fix 1.26.1 bugs

src/OmniSharp.Host/MSBuild/Discovery/MSBuildLocator.cs
This works around what appears to be an issue with Mono when `AppDomain.AssemblyResolve` events are now triggered on ThreadPool threads due to my recent changes to MSBuild project loading.
=> Load MSBuild assemblies up front

CHANGELOG.md, src/OmniSharp.Abstractions/Utilities/Platform.cs, src/OmniSharp.Host/CompositionHostBuilder.cs, src/OmniSharp.Host/MSBuild/Discovery/Extensions.cs, src/OmniSharp.Host/MSBuild/Discovery/Providers/MonoInstanceProvider.cs, src/OmniSharp.Http/Startup.cs, src/OmniSharp.Stdio/Host.cs
This PR cherry picks changes from https://github.com/OmniSharp/omnisharp-roslyn/pull/1016 to master.
=> Port fixes for 1.26.2

src/OmniSharp.MSBuild/MSBuildProjectSystem.cs, src/OmniSharp.MSBuild/ProjectFile/ProjectFileInfo.cs, src/OmniSharp.MSBuild/SdksPathResolver.cs, tests/OmniSharp.MSBuild.Tests/ProjectFileInfoTests.cs
Unfortunately, it seems that there are some [reliability issues](https://github.com/Microsoft/msbuild/issues/2532) with the MSBuild SDK Resolvers that we haven't gotten to the bottom of yet. So, I'm adding back code to set the `MSBuildSDKsPath` environment variable per project based on running the `dotnet` in that project's directory.
This should address issues like https://github.com/OmniSharp/omnisharp-vscode/issues/1849 and https://github.com/OmniSharp/omnisharp-vscode/issues/1846.
Note that this is not a long term solution. It will work for now, but there are several future concerns that we need to be mindful of:
1. Setting an environment variable will be problematic if we ever want to run design-time builds in parallel. Currently, that's blocked by several issues, but maybe someday. …
=> Add back code that sets MSBuildSDKsPath environment variable for each project

src/OmniSharp.MSBuild/ProjectLoader.cs, src/OmniSharp.MSBuild/ProjectSystem.cs, src/OmniSharp.MSBuild/SdksPathResolver.cs, tests/OmniSharp.MSBuild.Tests/ProjectFileInfoTests.cs
This ports the change from #1021 ("Add back code that sets MSBuildSDKsPath environment variable for each project") to master. See that PR for details.
=> Port #1021 to master

build.cake, scripts/runhelpers.cake
This change ensures that we get to see the whole run script before terminating it during a build. Recently, a bug was masked because the run scripts were terminated before the bug would have manifested.
=> Build: Wait for run scripts to idle rather than terminate them after a timeout

src/OmniSharp.Roslyn/Utilities/CompilationOptionsHelper.cs
Diagnostic ids can be repeated when passed in from a project system. A [recent refactoring](https://github.com/OmniSharp/omnisharp-roslyn/pull/1025) seems to have changed code in such a way that creating a dictionary fails and that causes the workspace to not get populated with projects. Making the diagnostic ids distinct before creating a dictionary fixes the issue.
@filipw @DustinCampbell
=> Fix a regression causing netcore projects to fail to load

src/OmniSharp.Host/MSBuild/Discovery/Providers/VisualStudioInstanceProvider.cs
Since OmniSharp requires Roslyn, it makes sense to filter the installations
being discovered to those that have the required `Microsoft.VisualStudio.Component.Roslyn.Compiler`
component installed (see https://docs.microsoft.com/en-us/visualstudio/install/workload-component-id-vs-community).
Fixes #1031
=> Select first VS2017 instance with the required Roslyn compilers component

src/OmniSharp.Abstractions/Models/v1/Diagnostics/DiagnosticLocation.cs, src/OmniSharp.Roslyn.CSharp/Helpers/DiagnosticExtensions.cs
So that when displaying an error we can show the error code as well.
@DustinCampbell
=> Return a diagnostic's Id from /codecheck calls

build/Packages.props, src/OmniSharp.Script/ScriptProjectSystem.cs
This PR aligns OmniSharp.Script with Dotnet.Script.DependencyModel 0.3.0 and adds support for providing metadata for script packages. 
Also took the liberty to fix a typo 😄  ("Destkop CLR scripts" -> "Desktop CLR scripts")
=> Align OmniSharp.Script with Dotnet.Script.DependencyModel 0.3.0

src/OmniSharp.Script/ScriptProjectSystem.cs
This PR ensures that we don't load multiple versions of the same compilation assembly. This PR only affects loading metadata for scripts targeting .Net Core.
This PR also resolves the issue discussed here. 
https://github.com/filipw/dotnet-script/issues/194
=> Ensure that we don't load multiple compilation assemby versions

src/OmniSharp.Stdio/Host.cs
Instead of logging STDIO Server requests/responses like this:
```
************ Request ************
{"Type":"request","Seq":30,"Command":"/findusages","Arguments":{"FileName":"c:\\code\\csharp-scripting-demos\\build\\build.csx","Line":14,"Column":5,"OnlyThisFile":false,"ExcludeDefinition":true}}
[dbug]: OmniSharp.Stdio.Host
************  Response ************ 
{"Request_seq":30,"Command":"/findusages","Running":true,"Success":true,"Message":null,"Body":{"QuickFixes":[{"FileName":"c:\\code\\csharp-scripting-demos\\build\\build.csx","Line":41,"Column":25,"EndLine":41,"EndColumn":35,"Text":"if (!Directory.Exists(outputPath)) {","Projects":["build.csx"]},{"FileName":"c:\\code\\csharp-scripting-demos\\build\\build.csx","Line":42,"Column":31,"EndLine":42,"EndColumn":41,"Text":"Directory.CreateDi …
```
=> pretty print JSON when logging requests/responses in STDIO server

build/Settings.props, src/OmniSharp.Roslyn.CSharp/OmniSharp.Roslyn.CSharp.csproj, src/OmniSharp.Roslyn.CSharp/Services/Signatures/CheckStaticInvocation.cs, src/OmniSharp.Roslyn.CSharp/Services/Signatures/InvocationContext.cs, src/OmniSharp.Roslyn.CSharp/Services/Signatures/SignatureHelpService.cs, tests/OmniSharp.Roslyn.CSharp.Tests/SignatureHelpFacts.cs
Issue : https://github.com/OmniSharp/omnisharp-vscode/issues/1440
During the search for the signature help, only the immediate Type that contains the given method  was being searched for possible method overloads hence the overloads present in the Base Classes were not appearing. Added the code to search for members using the GetMemberGroup. Added a test for the same. 
Please review @DustinCampbell @TheRealPiotrP @rchande
=> Intellisense not showing methods from the Base class in Signature Help

src/OmniSharp.Roslyn.CSharp/Services/Formatting/FormatRangeService.cs, tests/OmniSharp.Roslyn.CSharp.Tests/FormattingFacts.cs
Issue : https://github.com/OmniSharp/omnisharp-vscode/issues/214
On selecting after the first (alphanumeric) character in "Format Selection" , the code was not trimming the preceding white spaces in the first line of the selection. Modified the code to set the start of the span to the full span of the intersecting token and added the relevant test cases.
Please review : @DustinCampbell @TheRealPiotrP @rchande
=> Format range

src/OmniSharp.Cake/CakeProjectSystem.cs, src/OmniSharp.Cake/Services/CakeScriptService.cs, src/OmniSharp.Cake/Services/ICakeScriptService.cs
Just to avoid throwing any uneccesary exceptions.
=> Check if file exist before trying to create MetadataReference.

CHANGELOG.md
Here's an update to the CHANGELOG for OmniSharp 1.28. Also, this is an official heads-up/reminder to include a changelog update when making PRs. :smile:
cc @mholo65
=> Update changelog with latest changes for 1.28

CHANGELOG.md, src/OmniSharp.Script/ScriptProjectSystem.cs
Builds upon PR #1053. (Merge that first, and then rebase this...)
Add created .csx files to workspace and remove deleted .csx files from workspace.
ping @filipw
=>  Watch .csx files in order to add/remove script projects to workspace.

CHANGELOG.md, build/Packages.props, test-assets/test-projects/CakeProject/tools/packages.config
Just leaving this here as a reminder that it would be good to get `Cake.Scripting` 0.2.x into next OmniSharp-Roslyn release as it will bring significant performance improvements to Cake.
0.2.x is not released yet (therefore the beta reference), but I'll make sure to create a release right before you'll start preparing the OmniSharp-Roslyn release.
=> Update Cake.Scripting dependencies to 0.2.0

src/OmniSharp.Host/MSBuild/Discovery/Providers/VisualStudioInstanceProvider.cs
=> Fix typo that breaks discovery of more than one installed Visual Studio

CHANGELOG.md, build/Packages.props, src/OmniSharp.Abstractions/Configuration.cs, src/OmniSharp.Http/app.config, src/OmniSharp.MSBuild/ProjectFile/PropertyConverter.cs, src/OmniSharp.Stdio/app.config, tests/OmniSharp.Roslyn.CSharp.Tests/FindImplementationFacts.cs, tests/OmniSharp.Roslyn.CSharp.Tests/IntellisenseFacts.cs, tests/OmniSharp.Roslyn.CSharp.Tests/SignatureHelpFacts.cs, tests/app.config
- upgraded to Roslyn 2.6.0
- added C# 7.2 support
- added a C# 7.2 test for scripting (scripting by design should default to latest language version)
- fixed some tests that contained invalid C#
=> Roslyn 2.6.0 + C# 7.2

src/OmniSharp.Abstractions/Services/IAssemblyLoader.cs, src/OmniSharp.LanguageServerProtocol/LanguageServerHost.cs, src/OmniSharp.Stdio/Program.cs
This allows plugins to be specified using the path to a dll. This adds to the existing behavior of allowing plugins to be specified using an assembly name.
=> allow plugins to be specified by a dll file path

src/OmniSharp.Host/WorkspaceInitializer.cs, src/OmniSharp.Http/Middleware/EndpointMiddleware.cs, src/OmniSharp.Http/Middleware/MiddlewareExtensions.cs, src/OmniSharp.Http/Middleware/StatusMiddleware.cs, src/OmniSharp.Http/Startup.cs
JsonSerializers are relatively expensive to create, and are thread safe, so for the HTTP server we can just reuse the same instance.
Also updated a few places where extension methods were not invoked like extension methods.
=> reuse JsonSerializer in the HTTP server

src/OmniSharp.Abstractions/Models/v1/TypeLookup/DocumentationComment.cs, src/OmniSharp.Roslyn.CSharp/Services/DocumentationConverter.cs, tests/OmniSharp.Roslyn.CSharp.Tests/TypeLookupFacts.cs
Fixes: #1046 
Before concatenating the string, a TrimStart was being called that removed all the whitespaces. Added a call to a function that retains a single space if the string begins with a whitespace. Added a test for the same and modified the existing tests to match the behaviour.
Please review : @DustinCampbell @TheRealPiotrP @rchande
=> Retain single leading space when appending string in TypeLookUp

CHANGELOG.md, src/OmniSharp.MSBuild/ProjectSystem.cs, src/OmniSharp.MSBuild/SolutionParsing/ProjectBlock.cs
Fixes issue "The given path's format is not supported" #1036 when you have an ASP.NET website in your solution.
=> don't parse ASP.NET websites

src/OmniSharp.Abstractions/Models/v1/MembersTree/FileMemberElement.cs, src/OmniSharp.Roslyn.CSharp/Workers/StructureComputer.cs
Issue : https://github.com/OmniSharp/omnisharp-vscode/issues/429
Added properties to contain the attribute span in a file member element, which will be used by the editor to display the "# of references" before the attributes.
=> Added attribute span property for fileMemberElement

CHANGELOG.md, src/OmniSharp.MSBuild/ProjectSystem.cs, src/OmniSharp.MSBuild/SolutionParsing/ProjectBlock.cs, tests/OmniSharp.MSBuild.Tests/SolutionParsingTests.cs
This is a follow up to #1066.
I just noticed the logic there wasn't sufficient as these projects don't necessarily start with `http://` - for example it could be `localhost` or any other string really (up to the user).
However, the legacy ASP.NET Websites have a common well-known project GUID so we can use that to exclude it from OmniSharp (since they don't have csproj files, we can't support them at the moment).
I threw in a test just to be on the safe side.
=> Detect legacy ASP.NET Websites via project GUID

src/OmniSharp.Roslyn.CSharp/Services/Navigation/GotoDefinitionService.cs, tests/OmniSharp.Roslyn.CSharp.Tests/GoToDefinitionFacts.cs
Fixes: https://github.com/OmniSharp/omnisharp-vscode/issues/1949
Changes:
1. Check for property accessors in GoToTypeDefinition.
2. Test cases for the same.
Please review : @DustinCampbell @TheRealPiotrP @rchande
=> Changes for empty reponse for GoToDefinition on PropertyAccessorSymbol

src/OmniSharp.Host/Services/AssemblyLoader.cs
@filipw mentioned this in Slack.
=> AssemblyLoader.Load should not throw if loading fails.

src/OmniSharp.Abstractions/OmniSharpEndpoints.cs, src/OmniSharp.DotNetTest/DebugSessionManager.cs, src/OmniSharp.DotNetTest/Models/BaseTestClassRequest.cs, src/OmniSharp.DotNetTest/Models/DebugTestClassGetStartInfoRequest.cs, src/OmniSharp.DotNetTest/Models/RunTestInClassRequest.cs, src/OmniSharp.DotNetTest/Services/DebugTestClassService.cs, src/OmniSharp.DotNetTest/Services/RunTestsInClassService.cs, src/OmniSharp.DotNetTest/TestManager.cs, src/OmniSharp.DotNetTest/VSTestManager.cs
Added endpoints to enable "Run All Tests" in class and "Debug All Tests" in class
Please review : @DustinCampbell @rchande @TheRealPiotrP @filipw
=> Endpoints for running and debugging all tests in a class

src/OmniSharp.Abstractions/Utilities/Platform.cs
1. Trim the osName and osArch values returned by `uname`
2. Ensure that the `/etc/os-release` file exists before reading it
=> A couple of tweaks to platform-sniffing code

CHANGELOG.md, src/OmniSharp.Cake/Services/RequestHandlers/CakeRequestHandler.cs, src/OmniSharp.Cake/Services/RequestHandlers/Diagnostics/CodeCheckHandler.cs, tests/OmniSharp.Cake.Tests/CodeCheckFacts.cs
Cake's diagnostics engine calls the generic CodeCheckService, which generates all diagnostics for the solution if called without a specific file path. This results in duplicate errors in C# projects when VS Code requests project level diagnostics. The solution is to only compute diagnostics for specified files.
Fixes https://github.com/OmniSharp/omnisharp-vscode/issues/1830
Diagnostics window in VS Code now looks like:
cc @mholo65
=> Disable cake diagnostics endpoint for requests that don't specify a file

.travis.yml, CHANGELOG.md, build/Packages.props, src/OmniSharp.Abstractions/Configuration.cs, src/OmniSharp.Http/app.config, src/OmniSharp.LanguageServerProtocol/app.config, src/OmniSharp.Stdio/app.config, tests/app.config
=> updated to Roslyn 2.7.0

NuGet.Config, build.cake, build.json, build/Packages.props, src/OmniSharp.Host/MSBuild/Discovery/Providers/StandAloneInstanceProvider.cs, src/OmniSharp.MSBuild/ProjectFile/PropertyNames.cs, src/OmniSharp.MSBuild/ProjectLoader.cs, tools/packages.config
This change updates OmniSharp with the latest MSBuild binaries. Recent performance changes for MSBuild now require NuGet.Build.Tasks, which requires a set of NuGet binaries be included as well. Because the versions of these NuGet binaries might be different (actually, they *are* different) than the binaries that OmniSharp uses, there's a bit of duplication.
=> Update OmniSharp to latest MSBuild

.travis.yml, appveyor.yml
These aren't huge improvements, but they help a bit.
* Ensure that we set DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true for ALL CI builds to avoid the first run population of the NuGet cache. Previously, we only did this for Travis. Now we do it for AppVeyor as well.
* Don't install openssl on OSX builds. At one time, this was needed for the legacy .NET Core SDK, but we don't even run those tests on OSX builds anymore.
* Disable caching in CI builds.
Now that the build performance has been improved a great deal, it's clear that the build caching itself is taking a big chunk of time. On Linux, it takes ~90 seconds to set up the build cache and about ~130 to pack and upload the cache. From what I can tell, it does this for every single build, adding around 3.5 minutes on Linux. Disabling the …
=> Further build performance improvements

tests/app.config
This is causing warnings during builds and doesn't appear to be necessary.
=> Remove unnecessary binding redirect from tests app.config

src/OmniSharp.MSBuild/ProjectFile/PropertyNames.cs, src/OmniSharp.MSBuild/ProjectLoader.cs
Fixes https://github.com/OmniSharp/omnisharp-vscode/issues/2173
We need to set the AlwaysCompileMarkupFilesInSeparateDomain property to false. Otherwise, the XAML markup compiler task will try to create an AppDomain to run the markup compiler in. In normal MSBuild scenarios, this is fine. However, in OmniSharp, our AppDomain.AssemblyResolve handler that's used to locate MSBuild will not be installed in the marker compiler task's AppDomain, causing it to fail.
=> Set MSBuild property to allow the XAML markup compiler task to run

src/OmniSharp.Host/FileWatching/ManualFileSystemWatcher.Callbacks.cs, src/OmniSharp.Host/FileWatching/ManualFileSystemWatcher.cs, src/OmniSharp.MSBuild/ProjectManager.cs
While refactoring some code, I noticed that we were queuing the same callback with the `IFileSystemWatcher` many, many times in order to watch source file directories. That means that these callbacks would be called multiple times for any notification. This change expands the `ManualFileSystemWatcher` to only add the same callback for a particular extension, file or directory once. Note that the callback is only checked for reference equality, so it's necessary to stash your callback in a field if you don't want it added multiple times.
=> Ensure that we don't subscribe the same file-watcher callback multiple times

src/OmniSharp.MSBuild/OmniSharp.MSBuild.csproj
Set `ExcludeAssets="Runtime"` on the `Microsoft.Build.*` in addition to `PrivateAssets="All"`
to stop these assemblies from being copied to the build output.
=> Ensure that `Microsoft.Build.*` assemblies are _really_ removed by build output

src/OmniSharp.Host/MSBuild/Discovery/Providers/DevConsoleInstanceProvider.cs
For prereleases, the Visual Studio command prompt sets the environment
variable `VSCMD_VER` to a value like `15.7.0-pre.3.0`, which is not
parseable by System.Version.
This could be handled by using a version parser that can handle this
SemVer 2 version as well as Windows 4-part versions, but that would be
another dependency, so I just special-cased the problematic dash.
=> Report better version for VS preview consoles

build/Packages.props
The net46 version of `Microsoft.Build` has an assembly reference to `System.Threading.Tasks.Dataflow` version `4.5.24.0`. However, we were incorrectly referencing the `4.6.0` of the `System.Threading.Tasks.Dataflow` NuGet package. That was due to the fact that the netstandard1.5 version of `Microsoft.Build` depends on version `4.6.0` of the same package. I suspect our dependency wasn't updated when I moved OmniSharp away from netstandard1.6 to net46 last year.
The issue here is that the embedded Mono won't locate the `System.Threading.Tasks.Dataflow` that `Microsoft.Build` requires. If the user happens to have Mono installed, it might find it there. However, it might not if the user is on OSX and has a different version of Mono installed than our embedded Mono. We can fix it by just …
=> Downgrade the System.Threading.Tasks.Dataflow dependency to the version actually needed by MSBuild

src/OmniSharp.MSBuild/ProjectManager.cs
The proposed changes allow OmniSharp not to stop processing projects when it encounters a file with CSProj extension that is not a C# project. At the moment I'm working with a repo where out of 736 CSProj files 229 are of this sort. They typically are TypeScript projects, projects that copy files into final release folder and project files used only as data inputs for test cases. With my changes, OmniSharp invoked from VSCode was able to successfully process all valid C# projects while ignoring the rest.
=> Handle CSProj files that are not C# projects that 

CHANGELOG.md, src/OmniSharp.Script/ScriptProjectSystem.cs
Fixes #1184 
Rather than trying to resolve them from `OmniSharp.deps.json` with `Microsoft.Extensions.DependencyModel`, we just grab them from the current AppDomain. This is much simpler and much more reliable, because we have seen now that it's possible for `Microsoft.Extensions.DependencyModel` to throw on non-Windows platforms.
This is impossible to test from unit tests. In fact we have a unit test that check the correct behavior of the script host object (which is really the case here) but as mentioned in #1184, the problem only manifested itself in certain situation.
=> in scripting, load inherited assemblies from the current AppDomain

CHANGELOG.md, src/OmniSharp.Host/MSBuild/Discovery/Providers/DevConsoleInstanceProvider.cs
Fixes #1188
This fixes a null-reference extension that can be thrown if the "VSINSTALLDIR" environment variable exists but "VSCMD_VER" does not.
=> Fix potential null-ref in MSBuild discovery

build.json, src/OmniSharp.MSBuild/ProjectLoader.cs, test-assets/test-projects/ProjectWithMultiTFMLib/App/App.csproj, test-assets/test-projects/ProjectWithMultiTFMLib/App/Program.cs, test-assets/test-projects/ProjectWithMultiTFMLib/Lib/Class1.cs, test-assets/test-projects/ProjectWithMultiTFMLib/Lib/Lib.csproj, test-assets/test-projects/ProjectWithMultiTFMLib/ProjectWithMultiTFMLib.sln, tests/OmniSharp.MSBuild.Tests/WorkspaceInformationTests.cs
Fixes https://github.com/OmniSharp/omnisharp-vscode/issues/2295
When OmniSharp loads a project reference outside the OmniSharp path, it does not attempt to do a full design-time build of the project. Instead, it just uses the MSBuild project evaluation. However, an important code path was being skipped where a target framework is selected in the case that the project has multiple target frameworks. Later, this causes an exception to be thrown because several properties did not evaluate properly. This change ensures that a target framework is selected in this case.
=> Fix bug when multi-TFM project reference is outside OmniSharp's target path

src/OmniSharp.Script/ScriptHelper.cs, src/OmniSharp.Script/ScriptOptions.cs, src/OmniSharp.Script/ScriptProjectSystem.cs, tests/TestUtility/TestHelpers.cs
Fixes #1024 
This PR introduces the ability to configure a path to RSP file which is picked up by the scripting project system.
The RSP is not supported in the compiler-specific traditional way (where it can configure almost all of the compilation options) but rather is just a vessel to provide custom assembly references (`/r:...`) and global namespaces (`/u:...`). This is consistent with CSI behavior, which also uses RSP files only for these two types of input (when it comes to compilation options at least).
The obvious user benefit of all of this is, if I built my own custom script runner using Roslyn Scripting Engine, I could use OmniSharp for intellisense and language services against it (or at least to certain degree). That's due to the fact that I'd be able to predefine my …
=> Support RSP-based configuration for scripting project system

README.md
Fixes: https://github.com/OmniSharp/omnisharp-vscode/issues/2204
Update the readme to enable the usage of the vscode -" Use latest OmniSharp option" : https://github.com/OmniSharp/omnisharp-vscode/blob/master/CHANGELOG.md#specify-omnisharp-version
Please review : @rchande @TheRealPiotrP @DustinCampbell
=> Update readme for vscode "latest" option

build.json, src/OmniSharp.Abstractions/Services/IDotNetCliService.cs, src/OmniSharp.DotNet/DotNetProjectSystem.cs, src/OmniSharp.DotNetTest/Legacy/LegacyTestManager.cs, src/OmniSharp.DotNetTest/Services/BaseTestService.cs, src/OmniSharp.DotNetTest/Services/BaseTestService`2.cs, src/OmniSharp.DotNetTest/Services/DebugTestClassService.cs, src/OmniSharp.DotNetTest/Services/DebugTestService.cs, src/OmniSharp.DotNetTest/Services/GetTestStartInfoService.cs, src/OmniSharp.DotNetTest/Services/RunTestService.cs, src/OmniSharp.DotNetTest/Services/RunTestsInClassService.cs, src/OmniSharp.DotNetTest/TestManager.cs, src/OmniSharp.DotNetTest/VSTestManager.cs, src/OmniSharp.Host/CompositionHostBuilder.cs, src/OmniSharp.Host/MSBuild/Discovery/MSBuildLocator.cs, src/OmniSharp.Host/Services/DotNetCliService.cs, src/OmniSharp.Http/Startup.cs, src/OmniSharp.LanguageServerProtocol/LanguageServerHost.cs, src/OmniSharp.MSBuild/Options/MSBuildOptions.cs, src/OmniSharp.MSBuild/PackageDependencyChecker.cs, src/OmniSharp.MSBuild/ProjectSystem.cs, src/OmniSharp.MSBuild/SdksPathResolver.cs, src/OmniSharp.Stdio.Driver/Program.cs, tests/OmniSharp.DotNetTest.Tests/AbstractGetTestStartInfoFacts.cs, tests/OmniSharp.Http.Tests/EndpointMiddlewareFacts.cs, tests/OmniSharp.Stdio.Tests/StdioServerFacts.cs, tests/OmniSharp.Tests/DotNetCliServiceFacts.cs, tests/TestUtility/OmniSharpTestHost.cs, tests/TestUtility/TestServiceProvider.cs
Fixes #1190
This change ended up being a bit larger than I'd intended. If you're reviewing, I recommend walking through each commit at a time.
At it's core, this change removes an old hack that set the `MSBuildSDKsPath` environment variable to a path that was computed by launching `dotnet` in the project folder. This hack is an override that blocks MSBuild's SDK resolvers, which is the system that *should* be used to locate the SDK(s) for a project. However, when we tried removing this hack in the past, we were bit by the fact that the base MSBuild SDK resolve doesn't work with .NET Core SDKs <= 1.0.3. So, we added the hack back. Since there weren't really any custom MSBuild SDK resolvers out there, the override really didn't have much of an impact.
Now that MSBuild has shipped the …
=> Remove MSBuildSDKsPath hack that blocks MSBuild SDK resolvers

OmniSharp.sln, src/OmniSharp.Script/ScriptProjectSystem.cs, test-assets/test-scripts/DotnetCoreScriptSimple/main.csx, test-assets/test-scripts/DotnetCoreScriptWithNuget/main.csx, test-assets/test-scripts/SingleCsiScript/main.csx, test-assets/test-scripts/TwoCsiScripts/main.csx, test-assets/test-scripts/TwoCsiScripts/users.csx, tests/OmniSharp.Script.Tests/OmniSharp.Script.Tests.csproj, tests/OmniSharp.Script.Tests/WorkspaceInformationTests.cs, tests/TestUtility/OmniSharpTestHost.cs, tests/TestUtility/TestAssets.cs
This PR - as suggested by @rchande on Slack 😀- adds several tests for the CSX project system (a simple CSI script, 2 CSI scripts together, a simple .NET Core script, a .NET Core script with a Nuget reference). 
The tests mimic some of the project tests done by the MsBuild project system - the workspace gets initialized, and then we use `WorkspaceInformationRequest` to retrieve the project system info about what OmniSharp has found there.
This gives us a long, long overdue (I know 😓) "first level" of an automated check - in case some change in the future breaks the project system. 
Irrespective of this PR, I'd still like to add an integration test in the VS Code extension repo.
=> Added tests for CSX project system

CHANGELOG.md, src/OmniSharp.Cake/CakeProjectSystem.cs, tests/OmniSharp.Cake.Tests/CakeProjectSystemFacts.cs
[Spotted by](https://gitter.im/cake-build/cake?at=5b056ecbfb0f4a0bfe643904) @mholo65.
This is needed upstream to fix https://github.com/cake-build/bakery/issues/104.
What's the best way to put a test on this change?
=> Enable latest C# features in Cake files to match runtime behavior

src/OmniSharp.DotNetTest/Models/DotNetTestResult.cs, src/OmniSharp.DotNetTest/VSTestManager.cs, test-assets/test-projects/MSTestProject/TestProgram.cs, test-assets/test-projects/NUnitTestProject/TestProgram.cs, test-assets/test-projects/XunitTestProject/TestProgram.cs, tests/OmniSharp.DotNetTest.Tests/RunTestFacts.cs, tests/OmniSharp.DotNetTest.Tests/TestDiscoveryFacts.cs
dotnet test also prints the stdout messages. So added a property to `DotNetTestResult` to return an array of these messages.
omnisharp-vscode side : https://github.com/OmniSharp/omnisharp-vscode/pull/2343
Please review : @rchande @DustinCampbell
=> Return the stdout messages to improve test logging

CHANGELOG.md, src/OmniSharp.Cake/Services/MonoScriptGenerationProcess.cs, src/OmniSharp.Cake/Services/RequestHandlers/Diagnostics/CodeCheckHandler.cs, test-assets/test-projects/CakeProject/error.cake, test-assets/test-projects/CakeProject/tools/packages.config, tests/OmniSharp.Cake.Tests/CakeProjectSystemFacts.cs, tests/OmniSharp.Cake.Tests/CodeCheckFacts.cs
Fixes issue reported [here](https://github.com/cake-build/bakery/issues/90)
=> Fix diagnostics from loaded cake files shown in the current file

CHANGELOG.md, src/OmniSharp.Abstractions/Services/IProjectSystem.cs, src/OmniSharp.Cake/CakeProjectSystem.cs, src/OmniSharp.DotNet/DotNetProjectSystem.cs, src/OmniSharp.Host/WorkspaceInitializer.cs, src/OmniSharp.MSBuild/ProjectSystem.cs, src/OmniSharp.Plugins/Plugin.cs, src/OmniSharp.Script/ScriptProjectSystem.cs, tests/OmniSharp.DotNet.Tests/WorkspaceInformationTests.cs, tests/OmniSharp.DotNetTest.Tests/AbstractGetTestStartInfoFacts.cs, tests/OmniSharp.DotNetTest.Tests/AbstractRunTestFacts.cs, tests/OmniSharp.DotNetTest.Tests/AbstractTestFixture.cs, tests/OmniSharp.DotNetTest.Tests/GetTestStartInfoFacts.cs, tests/OmniSharp.DotNetTest.Tests/LegacyGetTestStartInfoFacts.cs, tests/OmniSharp.DotNetTest.Tests/LegacyRunTestFacts.cs, tests/OmniSharp.DotNetTest.Tests/TestDiscoveryFacts.cs, tests/OmniSharp.Http.Tests/EndpointMiddlewareFacts.cs
This change threads through a new `IProjectSystem.EnabledByDefault` property and sets it to false for the legacy project.json project system.
=> Disable DotNetProjectSystem by default

CHANGELOG.md, src/OmniSharp.Cake/Extensions/ResponseExtensions.cs, src/OmniSharp.Cake/Services/RequestHandlers/CakeRequestHandler.cs, src/OmniSharp.Cake/Services/RequestHandlers/Diagnostics/CodeCheckHandler.cs, src/OmniSharp.Cake/Services/RequestHandlers/Refactoring/V2/BaseCodeActionHandler.cs, src/OmniSharp.Cake/Services/RequestHandlers/Refactoring/V2/GetCodeActionsHandler.cs, src/OmniSharp.Cake/Services/RequestHandlers/Refactoring/V2/RunCodeActionsHandler.cs, tests/OmniSharp.Cake.Tests/CodeActionsV2Facts.cs
=> GH1205: Add support for code actions in Cake

src/OmniSharp.Roslyn.CSharp/Services/Refactoring/V2/BaseCodeActionService.cs, src/OmniSharp.Roslyn/Extensions/TextExtensions.cs, tests/OmniSharp.Tests/ZeroBasedIndexConverterFacts.cs, tests/TestUtility/TextPoint.cs
I apparently lost my mind the other day and added code to increment zero-based indeces to one-based indeces in the `OmniSharp.Models.V2.Point` type. Thankfully, @mholo65 found this while battling some other code and pointed it out. I've fixed this, added a few more helper extension methods for converting lines, offsets, spans, ranges and points, and added several tests for the `ZeroBasedIndexConverter` using specific OmniSharp protocol types.
=> Fix zero/one-based range and point models

CHANGELOG.md, OmniSharp.sln, src/OmniSharp.Cake/Utilities/LineIndexHelper.cs, src/OmniSharp.Roslyn/Extensions/TextLineExtensions.cs, tests/OmniSharp.Cake.Tests/LineIndexHelperFacts.cs, tests/OmniSharp.Cake.Tests/TestAssets/multi.cake.g.txt, tests/OmniSharp.Cake.Tests/TestAssets/single.cake.g.txt
Some performance improvements noted by @DustinCampbell while he was looking through the Cake line mapping code.
=> Performance improvements to Cake line mappings

CHANGELOG.md, src/OmniSharp.Cake/Extensions/ResponseExtensions.cs, src/OmniSharp.Cake/Services/RequestHandlers/Structure/CodeStructureHandler.cs, tests/OmniSharp.Cake.Tests/CodeStructureFacts.cs
=> GH1214: Add cake handler for /codestructure endpoint.

src/OmniSharp.DotNetTest/Services/DebugTestService.cs
Fixes: https://github.com/OmniSharp/omnisharp-vscode/issues/2400
If there is a Build failure the test manager fails to connect and the required variables for the debug process are not initialized. However since there is no check that the TestManager is connected or not, we go ahead with the debug request and the system fails with the exception `_writer is null`. However, since we entered the `StartSession` method, the required variables are set and it appears to omnisharp-roslyn that a debug session has started whereas there is no such session. Hence any subsequent debug request is rejected with the error - `Debug session started`.
Hence the fix is to verify whether the testManager is connected before we call the StartSession ,else fail with the relevant exception.
=> Debug only when test manager is connected

build.cake, build.json, mono-packaging/copy-mono.sh, mono-packaging/copy-msbuild.sh, mono-packaging/run, scripts/common.cake
This change adds two scripts, `copy-mono.sh` and `copy-msbuild.sh`, that can be used to create embedded Mono and MSBuild packages for the operating system that they're run on (macOS, linux-x64 and linux-x86).
Note that I've gone ahead and included the binary that was causing trouble with the `McMaster.Extensions.CommandLineUtils` package.
=> Add packaging scripts for embedded Mono and MSBuild bits

src/OmniSharp.Roslyn/OmniSharpWorkspace.cs
Looks like https://github.com/OmniSharp/omnisharp-roslyn/pull/1252 had an intent to create one project for misc files per language, but bug caused it to create new project for each file, causing a skyrocket of memory consumption in larger projects. This should fix the issue
=> Fix MiscFile system creating new project for each file

src/OmniSharp.Roslyn.CSharp/Services/Structure/CodeStructureService.cs, tests/OmniSharp.Cake.Tests/CodeStructureFacts.cs
Noticed today enum members were missing from code outline / codeLens / find reference doesn't work on enum members, and I am sure it used to work in the past. 
Looks like CodeCheckService omitted to handle "EnumMemberDeclarationSyntax" and never created code elements for enum members. I added additional checks in the existing CodeStructure test to assure enum members are there.
After the changes enum members reappeared in code outline / code lens:
=> Fix enum members missing in code structure response

src/OmniSharp.Cake/Services/RequestHandlers/Navigation/FindSymbolsHandler.cs, src/OmniSharp.Roslyn.CSharp/Services/Navigation/FindSymbolsService.cs, src/OmniSharp.Roslyn/Extensions/SolutionExtensions.cs, src/OmniSharp.Roslyn/OmniSharpWorkspace.cs, tests/OmniSharp.Cake.Tests/FindSymbolsFacts.cs
Fixes https://github.com/OmniSharp/omnisharp-roslyn/issues/1281
=> Don't duplicate find symbols results from C# files

tools/packages.config
This created a whole mess of problems due to NuGet.Build.Tasks requiring difference dependencies in 4.8.0. Rolling them back until we can take a look at what new dependencies are needed.
cc @rchande
=> Rollback NuGet.Build.Tasks

src/OmniSharp.Abstractions/Logging/BaseLogger.cs, src/OmniSharp.Host/CompositionHostBuilder.cs, src/OmniSharp.Host/HostHelpers.cs, src/OmniSharp.Http/Startup.cs, src/OmniSharp.LanguageServerProtocol/LanguageServerLoggerFactory.cs, src/OmniSharp.Stdio.Driver/Program.cs, src/OmniSharp.Stdio/Host.cs, src/OmniSharp.Stdio/Logging/StdioLogger.cs, src/OmniSharp.Stdio/Logging/StdioLoggerExtensions.cs, src/OmniSharp.Stdio/Logging/StdioLoggerProvider.cs, tests/OmniSharp.Tests/LoggingTests.cs
When the logging packages were updated from 1.1 to 2.1, we took a breaking change (https://github.com/aspnet/Announcements/issues/238) that caused the `--loglevel` switch to no longer work properly. So, passing `--loglevel debug` doesn't do anything.
This change uses the new APIs for configuring logging and centralizes the filter. Note that I didn't change the LSP implementation because it looks to me like LSP is using loggers differently.
=> Fix OmniSharp log filtering

src/OmniSharp.MSBuild/ProjectManager.cs, src/OmniSharp.Roslyn/OmniSharpWorkspace.cs, src/OmniSharp.Roslyn/Properties/AssemblyInfo.cs, tests/OmniSharp.Roslyn.CSharp.Tests/OmniSharpWorkspaceFacts.cs
- Once a project has loaded we now evaluate all miscellaneous documents and try to lift them into the loaded project. This ensures that any document in the system gets properly promoted into a project once a project has been loaded. Before this virtual C# documents would not get promoted into a proper project because they didn't exist as part of the projects MSBuild compile items (which usually forces the promotion).
- Added tests to verify the two methods I added to OmnisharpWorkspaceFacts
aspnet/Razor.VSCode#148
@DustinCampbell @rchande
=> Promote misc documents to projects after project load.

CHANGELOG.md, src/OmniSharp.Host/Services/OmniSharpEnvironment.cs
At the moment, OmniSharp home directory is in user profile - `%USERPROFILE%\.omnisharp` or ` ~/.omnisharp`.
This PR introduces an `OMNISHARPHOME` environment variable which can be used to set a custom "home" path.
I mentioned this a while ago https://github.com/OmniSharp/omnisharp-roslyn/issues/953#issuecomment-325577768 and this should be enough to close that issue from OmniSharp server perspective (the remaining aspects are related to VS Code extension).
=> allow setting a custom OmniSharp home directory

src/OmniSharp.Cake/Services/RequestHandlers/Navigation/FindSymbolsHandler.cs, src/OmniSharp.Roslyn.CSharp/Services/Navigation/FindSymbolsService.cs, src/OmniSharp.Roslyn/Extensions/SolutionExtensions.cs, tests/OmniSharp.Roslyn.CSharp.Tests/FindSymbolsFacts.cs
I've noticed symbol search seems much less powerful than VS's one, which always seems to return nice fuzzy searches. 
o# uses "SymbolFinder.FindSourceDeclarationsAsync" with a custom matching algorithm passed in, while there is "SymbolFinder.FindSourceDeclarationsWithPatternAsync", which seems to the right thing when the search filter is passed in. 
After this change "#ProjMana" is able to find **Proj**ect**Mana**ger
So far it works as I expected, but somebody who know this API better should check if this makes sense. 
btw, when request.filter is not specified, full symbol list should be returned, which used to be done with (x => true). It seems funny, but I couldn't find a better way.
=> Use FindSourceDeclarationsWithPatternAsync to have nice fuzzy search

CHANGELOG.md, src/OmniSharp.Roslyn.CSharp/Services/Navigation/FindSymbolsService.cs, tests/OmniSharp.Roslyn.CSharp.Tests/FindSymbolsFacts.cs
This PR fixes a regression introduced in https://github.com/OmniSharp/omnisharp-roslyn/pull/1282 that broke symbol search for CSX.
I also enabled the FindSymbolsFacts to specifically run twice - once for both regular C# and once for CSX to prevent this in the future (we have same pattern on most tests, but it wasn't there on this one though).
This is quite critical so it would be great to merge this ASAP.
=> Fixed a regression that broke FindSymbols for CSX

CHANGELOG.md, src/OmniSharp.Roslyn.CSharp/Helpers/QuickFixExtensions.cs, src/OmniSharp.Roslyn.CSharp/Services/Navigation/FindImplementationsService.cs, src/OmniSharp.Roslyn/Extensions/SymbolExtensions.cs, tests/OmniSharp.Roslyn.CSharp.Tests/FindImplementationFacts.cs
This PR fixes the issue where "find implementation" OmniSharp would not find symbol overrides in child types. We were missing the look up of overrides on the symbols returned from `SymbolFinder.FindImplementationsAsync`.
Consider the following:
```csharp
interface IFoo
{
string Hi();
}
public class Bar : IFoo
{
public virtual string Hi() => "hi";
}
public class Baz : Bar
{
public override string Hi() => "hello";
}
```
In Visual Studio, trying to go to implementation of `Hi()`, from the interface declaration, would find both `Bar.Hi()` and `Baz.Hi()`. However, OmniSharp would find only `Bar.Hi()`.
This is with the fix applied:
=> Fixed issue with "go to implementation" and symbol overrides

src/OmniSharp.Roslyn.CSharp/Services/Signatures/SignatureHelpService.cs, tests/OmniSharp.Roslyn.CSharp.Tests/SignatureHelpFacts.cs
A fix for https://github.com/OmniSharp/omnisharp-vscode/issues/2495. Provides missing signature help for compiler literals and typeof(T)... expressions. Added two tests for those cases.
bonus question: will roslyn cover the whole signature service soon? it sounds like something that should be handled out-of-the-box
=> Fix missing signatures for some cases

src/OmniSharp.MSBuild/ProjectSystem.cs
This PR fixes omnisharp crash when the directory has '*.slnxxx' file.
* windows8.1-x64
* omnisharp-vscode: 1.16.2
* vscode: 1.28.2
1. create new console project in empty directory
2. create 'x.slnproj' and edit `<Project Sdk="MSBuild.SolutionSdk/0.1.0"></Project>`
* This is [MSBuild.SolutionSdk](https://github.com/JeffCyr/MSBuild.SolutionSdk) format
3. Restart Omnisharp
Omnisharp start to watch the project folder.
Omnisharp throw the following exception and stop to watch the project.
```The project system 'OmniSharp.MSBuild.ProjectSystem' threw exception during initialization.
OmniSharp.MSBuild.SolutionParsing.InvalidSolutionFileException: Solution header should be on first or second line.
場所 OmniSharp.MSBuild.SolutionParsing.SolutionFile.ParseHeaderAndVersion(Scanner scanner)
場所 …
```
=> fix collecting unexpected solution file like 'sln*'

src/OmniSharp.Roslyn.CSharp/Helpers/QuickFixExtensions.cs, src/OmniSharp.Roslyn.CSharp/Services/Navigation/FindImplementationsService.cs, tests/OmniSharp.Roslyn.CSharp.Tests/FindImplementationFacts.cs
Currently, when you use "Find Implementations" on a partial class, it appears to randomly select one of the definitions instead of returning all of them (like VS does). Looks like this was unintentionally broken in order to handle partialMethod case (guess there is makes sense to take symbol.Locations.First() instead of symbol.Locations).
Should be easy to merge with @filipw fix for separate bug fix in the same service.
=> Fix FindImplementationService not finding all implementations of the partial class

omnisharp.json
When working on OmniSharp code using OmniSharp (i.e. in VS Code) we have 2 errors reported from CSX filesystem about missing assembly references. This is caused by the fact that we run in "CSI" scripting mode by default, but we have CSX files that use the "dotnet-script"/.NET Core scripting mode in the source of OmniSharp (in tests). Since the "CSI" mode can't parse NuGet references used there, we report 2 diagnostics.
This has caused some confusion i.e here from @NTaylorMullen https://github.com/OmniSharp/omnisharp-roslyn/issues/1310#issuecomment-427174083
I have updated the `omnisharp.json` in OmniSharp to use "dotnet-script"/.NET Core scripting mode as the default behavior when working with OmniSharp source code.
=> updated the omnisharp.json file to not report CSI-specifc errors

src/OmniSharp.Host/MSBuild/Discovery/MSBuildInstanceProvider.cs, src/OmniSharp.Host/MSBuild/Discovery/Providers/DevConsoleInstanceProvider.cs, src/OmniSharp.Host/MSBuild/Discovery/Providers/MonoInstanceProvider.cs, src/OmniSharp.Host/MSBuild/Discovery/Providers/VisualStudioInstanceProvider.cs, src/OmniSharp.MSBuild/Options/MSBuildOptions.cs, src/OmniSharp.MSBuild/ProjectLoader.cs
This change fixes MSBuild discovery to handle scenarios where the MSBuild tools path is not included in a "15.0" folder. In future releases of Visual Studio, MSBuild will move to a folder named "Current" and OmniSharp should support that. In addition, I've added some extra logging during discovery to help indicate why a particular MSBuild instance isn't chosen. Finally, this change introduces a new option that causes OmniSharp to produce MSBuild binary logs when loading projects. This should be a big help for MSBuild debugging. It can be enabled in an omnisharp.json file like so:
```JSON
{
"MSBuild": {
"GenerateBinaryLogs": true
}
}
```
=> Improve MSBuild discovery for future scenarios

src/OmniSharp.Roslyn/BufferManager.cs
- Prior to this change there were times when a transient document had not been fully removed from the buffer manager's list tracking before trying to add it again.
- I initially based this branch off of the `v1.32.6` tag but looks like I can't represent that in the PR.
@rchande @akshita31 For a mid-november patch release would we grab everything from master in omnisharp-roslyn or would we build a separate branch? Either way, this can go into either one, just want to follow the same guidelines that you have always used.
Also, I and @ajaybhargavb tried this out locally and couldn't reproduce the exceptions.
aspnet/Razor.VSCode#214
=> Make adding transient documents more reliable.

src/OmniSharp.Host/MSBuild/Discovery/Providers/VisualStudioInstanceProvider.cs
My recent change to support VS MSBuild discovery for future versions of VS accidentally broke VS discovery altogether be leaving "MSBuild" out of the path. Oops!
=> Fix VS MSBuild discovery

CHANGELOG.md, src/OmniSharp.Abstractions/Options/FormattingOptions.cs, src/OmniSharp.Roslyn.CSharp/Services/CSharpWorkspaceOptionsProvider.cs
Fixes #1351 
As pointed out by @DustinCampbell, we missed this setting. I actually went through all of the `FormattingOptions` we expose and compared them to Roslyn's `CSharpFormattingOptions` and this was actually the only one we were missing 😀
This also fixes the default formatting behavior, since the default value is set to true.
=> expose IndentSwitchCaseSectionWhenBlock in OmniSharp FormattingOptions

src/OmniSharp.MSBuild/ProjectManager.cs
fixes https://github.com/OmniSharp/omnisharp-roslyn/issues/1356
Context of what happens:
1) When you edit file before projects get loaded, o# puts them in "Misc" project, because that's the best it can do at the moment.
2) On project load, MSBuildProjectManager creates a real Document on the same path, which kills the "Misc" document
3) **Problem is**: there is a bit of code that tries to "promote" misc documents into the newly loaded project, and this happens before step 2.
This unfortunate timing means that both "TryPromote" and "ProjectLoad" create each their own version of non-misc document (and ambiguity errors follow).
Moving "TryPromote" after actual project load, lets MSBuild properly delete misc files, so unnecessary document creating in "TryPromote" is avoided
cc @akshita31 …
=> Fix "Ambiguity" errors appearing when files are modified during project load

src/OmniSharp.Stdio/StdioCommandLineApplication.cs
Command line arguments were checked in an incorrect way.
=> Fixes #1269.

.travis.yml
Since a few days ago, all OSX builds fail with a brew error.
=> Fixed brew on Travis OSX

CHANGELOG.md, src/OmniSharp.Stdio/StdioCommandLineApplication.cs
The STDIO application has an unnecessary flag "stdio" exposed, which is not used for anything. This is a leftover from the days where both HTTP and STDIO could be launched from the same entry point.
=> removed unused stdio flag

CHANGELOG.md, src/OmniSharp.LanguageServerProtocol/LanguageServerHost.cs
Send cancellation token when the server shuts down so we terminate the process.
=> Solve issue #1113.

CHANGELOG.md, build/Packages.props
=> updated to Roslyn 3.0.0-beta4-19126-05

src/OmniSharp.Roslyn.CSharp/Workers/Refactoring/FixUsingsWorker.cs, tests/OmniSharp.Roslyn.CSharp.Tests/FixUsingsFacts.cs
the potential using statements are added to the Text of the QuickFix response, allowing the user manually choose which using statement to employ.
=> when fixing usings, return namespaces associated with ambiguous result

build.cake, src/OmniSharp.Host/MSBuild/Discovery/MSBuildInstanceProvider.cs
In MSBuild 16, the current omnisharp standalone msbuild path gets detected as belonging to Visual Studio, resulting in incorrect build behavior.
=> Rename msbuild directory to .msbuild

azure-pipelines.yml
At the moment the CI builds are broken on Linux because we pull `preview-xenial`. That resolves to an early preview of Mono 6 now and is broken.
This PR switches us back to `stable-xenial`.
This should be merged with high priority since no other Linux CI build works at the moment at ADO.
=>  switch to stable-xenial for linux CI builds on AzureDevOps

src/OmniSharp.Http/Startup.cs
As described in #1446, the HTTP version of OmniSharp-roslyn does not log any output.
I managed to find the commit where the logging stopped working, it was 4f9fb4d5 by @DustinCampbell. In that commit the `HostHelpers.LogFilter()` functionality was refactored into `CompositionHostBuilder.CreateDefaultServiceProvider()`, which has a `configureLogging` callback argument.
The problem here is that in the HTTP `configureLogging` callback, `ExceptionHandlerMiddleware` is included in a filter like this:
```cs
var exceptionHandlerMiddlewareName = typeof(ExceptionHandlerMiddleware).FullName;
builder.AddFilter(
(category, logLevel) => category.Equals(exceptionHandlerMiddlewareName, StringComparison.OrdinalIgnoreCase));
```
This filter is applied _on top_ of the filter already added in …
=> Fix HTTP logging

CHANGELOG.md, README.md, build.json
Changelog and readme tweaks. Also removed the travis/appveyor badges and replaced with Azure DevOps.
=> Small 📚updates to bring them up to date

src/OmniSharp.MSBuild/ProjectFile/PropertyConverter.cs
This should fix #1487.
I wasn't able to run the build.sh script to run the unit tests for some reason, as I was getting this response:
```
$ ./build.sh
Index was outside the bounds of the array.
Could not restore NuGet packages.
```
I'm not entirely sure why I was getting this, but I'm pretty certain I installed Mono correctly, as the snippets they gave to test the installation ran correctly.
=> Replace ToLanguageVersion switch with TryParse

src/OmniSharp.Roslyn.CSharp/Services/Intellisense/CompletionItemExtensions.cs
This was missed when we merged https://github.com/OmniSharp/omnisharp-roslyn/pull/1479
=> fixed logical typo in CompletionItemExtensions

src/OmniSharp.Host/Services/AnalyzerAssemblyLoader.cs
Double checked implementation based on original from roslyn and found important bit that was missing, this may fix issue #1496
=> Fixed mistake on shadow copying assembly loader.

azure-pipelines.yml
At the moment the CI builds use Mono 5.18.1 (macOS) and stable-xenial (Linux). 
The problem with this is that `stable-xenial` is a moving target as it points to latest stable Mono - it was 5.16 recently, and now it's actually 5.20.1 already. 
There is also `stable-vs` which is pinned to correspond to the VS for Mac version and currently resolves to 5.18.1 but it is also changing as new releases are done.
It makes sense for us to pin a Mono version instead - this way we can always make sure we work on our *minimal* required Mono version - https://github.com/OmniSharp/omnisharp-roslyn/blob/master/build.json#L9 instead of building in CI against what is the latest.
With this PR we will now run on Mono 5.18.1 on both macOS and Linux.
=> pin CI builds to use Mono 5.18.1

CHANGELOG.md, build/Packages.props, src/OmniSharp.Roslyn.CSharp/OmniSharp.Roslyn.CSharp.csproj, tests/OmniSharp.Roslyn.CSharp.Tests/BufferManagerFacts.cs, tests/OmniSharp.Roslyn.CSharp.Tests/IntellisenseFacts.cs, tests/OmniSharp.Tests/UpdateBufferFilterFacts.cs, tests/TestUtility/OmniSharpTestHost.cs
With one of the recent Roslyn betas, we have (or rather Roslyn has) regressed on declaration name completion - it doesn't work for us anymore at all. 
There was no test for that, so it went unnoticed - the test is added in this PR now.
The root cause is here http://source.roslyn.io/#Microsoft.CodeAnalysis.CSharp.Features/Completion/CompletionProviders/DeclarationNameCompletionProvider.cs,70 Roslyn actually swallows all exceptions for `DeclarationNameCompletionProvider`. With the current beta, Roslyn actually throws as it can't find a reference to `Humanizer`. It is a bug in Roslyn since this package is required at runtime but not listed as dependency of the Roslyn Nuget. 
Adding the package directly restores our old behavior and the declaration name completion works again (I tested in the …
=> Fixed declaration name completion regression

CHANGELOG.md, NuGet.Config, build/Packages.props, src/OmniSharp.Roslyn.CSharp/OmniSharp.Roslyn.CSharp.csproj
This allows us to get rid of the workaround added in https://github.com/OmniSharp/omnisharp-roslyn/commit/8bccccfa2dd2dade7db3d595515c471dbf5de492 - thanks to the upstream fix in Roslyn [here](https://github.com/dotnet/roslyn/commit/06927469eaa4b31921aa6da99a52917b7e2e8b28)
=> updated Roslyn to 3.2.0-beta4-19319-04

CHANGELOG.md
I added all the recent missing changes to the changelog and bumped the version to 1.33.0. We have lots of nice features coming in so it's time to move the minor version 😀
Whoever ends up triggering the next release, please use 1.33.0 too.
=>  changelog updates for recent merges + bump to 1.33.0

CHANGELOG.md, build.cake, build/Packages.props, src/OmniSharp.Roslyn.CSharp/Services/Formatting/EditorConfig/EditorConfigOptionsApplier.cs, src/OmniSharp.Roslyn.CSharp/Workers/Intellisense/SnippetGenerator.cs, src/OmniSharp.Roslyn/Extensions/SymbolExtensions.cs, tests/OmniSharp.Roslyn.CSharp.Tests/CustomRoslynAnalyzerFacts.cs
branched from #1533 where I fixed editorconfig to adapt to https://github.com/dotnet/roslyn/pull/27942
=> Update Roslyn for Preview 7 

build.cake
At the moment the `omnisharp-mono` archives we publish as part of the releases do not work (only `omnisharp-linux` and `omnisharp-osx` work), due to missing SQLite dependencies. The problem was the archive was created before the extra dependencies were copied.
Fixes #1536 ravi
=> ensure SQLite dependencies are included in the mono archive

CHANGELOG.md, src/OmniSharp.Abstractions/Plugins/Plugin.cs, src/OmniSharp.Abstractions/Services/IProjectSystem.cs, src/OmniSharp.Cake/CakeProjectSystem.cs, src/OmniSharp.DotNet/DotNetProjectSystem.cs, src/OmniSharp.Host/Endpoint/LanguagePredicateHandler.cs, src/OmniSharp.MSBuild/ProjectSystem.cs, src/OmniSharp.Roslyn/ProjectEventForwarder.cs, src/OmniSharp.Roslyn/ProjectInformationService.cs, src/OmniSharp.Roslyn/WorkspaceInformationService.cs, src/OmniSharp.Script/ScriptProjectSystem.cs, tests/OmniSharp.Cake.Tests/CakeProjectSystemFacts.cs, tests/OmniSharp.Http.Tests/EndpointMiddlewareFacts.cs, tests/OmniSharp.MSBuild.Tests/WorkspaceInformationTests.cs, tests/OmniSharp.Script.Tests/WorkspaceInformationTests.cs, tests/TestUtility/TestHostExtensions.cs
At the moment we can disable any project system via the config, which causes it to be skipped upon initialization.
However, some services such as `WorkspaceInformationService` or `ProjectInformationService` didn't respect the flag and still reached into the project systems for some information when invoked.
This PR fixes that.
=> Respect the disabling of a project system in services

CHANGELOG.md, src/OmniSharp.Roslyn.CSharp/Services/EditorConfigWorkspaceOptionsProvider.cs, tests/OmniSharp.Roslyn.CSharp.Tests/EditorConfigFacts.cs
fixes #1558 
At the moment we run `.editorconfig` options provider before the formatting options provider (formatting options from `omnisharp.json` + config params).
It doesn't work, because the result is we load formatting settings from `.editorconfig` and then *override them all* (not just the "changed" ones) with defaults from [here](https://github.com/OmniSharp/omnisharp-roslyn/blob/master/src/OmniSharp.Shared/Options/FormattingOptions.cs). This only applies to formatting rules, not other settings like naming conventions and code style.
Now, on our formatting endpoints it doesn't matter, since we reapply `.editorconfig` options on the fly again then - that's why the bug doesn't manifest itself on "normal" formatting, but for external code fixes, the formatting options do not correctly …
=>  Run editor config options provider last

src/OmniSharp.LanguageServerProtocol/Handlers/HoverHandler.cs, src/OmniSharp.LanguageServerProtocol/Helpers.cs
Fixes #1556.  Omnisharp is returning plaintext and assigning to MarkedString, which, according to the LSP spec, is a markdown formatted string.  Add a function to escape the text to prevent parsing errors.
=> Escape markdown to fix plaintext returns.

CHANGELOG.md, src/OmniSharp.MSBuild/ProjectFile/ProjectFileInfoExtensions.cs, test-assets/test-projects/AllowUnsafe/AllowUnsafe.csproj, test-assets/test-projects/AllowUnsafe/Program.cs, tests/OmniSharp.MSBuild.Tests/ProjectFileInfoTests.cs
accidentally, `AllowUnsafe` also behaved like `TreatWarningsAsErrors` 😂
fixes #1565
=> fixed AllowUnsafe regression

src/OmniSharp.Roslyn.CSharp/Workers/Diagnostics/CSharpDiagnosticWorkerWithAnalyzers.cs
Hello.  
I think that the cause of this [timeout issue](https://github.com/OmniSharp/omnisharp-roslyn/issues/1552) is in [GetAnalyzerSemanticDiagnosticsAsync](https://github.com/OmniSharp/omnisharp-roslyn/blob/61d7b82b79058d6250afe4d4db0d9e6bf7ffeac7/src/OmniSharp.Roslyn.CSharp/Workers/Diagnostics/CSharpDiagnosticWorkerWithAnalyzers.cs#L240).  
This function may not return a response.  
I checked the difference with [AnalyzerRunner](https://github.com/dotnet/roslyn/blob/version-3.1.0/src/Tools/AnalyzerRunner/Program.cs#L211) and made a correction.  
And it seems like it worked.
I'm glad if this information helps a little.
=> Fixed analyzer timeout issue.

build.json, src/OmniSharp.Script/ScriptProjectSystem.cs, test-assets/test-scripts/SingleCsiScriptWithCustomRsp/test.rsp, tests/OmniSharp.Script.Tests/WorkspaceInformationTests.cs
This is discovered as investigation of https://github.com/OmniSharp/omnisharp-roslyn/pull/1568#discussion_r306826127
Turns out the build script has never executed scripting tests 🙈😂
One test was broken since https://github.com/OmniSharp/omnisharp-roslyn/pull/1543 - but it never showed up in the build script, cause that skipped scripting tests...
This PR adds scripting tests to the builds script and fixes the initialization logic that made the test fail.
=>  run script tests as part of the build script

build/Packages.props, src/OmniSharp.Abstractions/Configuration.cs, src/OmniSharp.Http.Driver/app.config, src/OmniSharp.MSBuild/ProjectFile/ProjectFileInfo.ProjectData.cs, src/OmniSharp.MSBuild/ProjectFile/ProjectFileInfo.cs, src/OmniSharp.MSBuild/ProjectFile/ProjectFileInfoExtensions.cs, src/OmniSharp.MSBuild/ProjectFile/PropertyNames.cs, src/OmniSharp.MSBuild/ProjectManager.cs, src/OmniSharp.Roslyn.CSharp/Services/Refactoring/V2/RunCodeActionService.cs, src/OmniSharp.Roslyn.CSharp/Services/Signatures/SignatureHelpService.cs, src/OmniSharp.Roslyn/BufferManager.cs, src/OmniSharp.Roslyn/MetadataHelper.cs, src/OmniSharp.Roslyn/OmniSharpWorkspace.cs, src/OmniSharp.Shared/FileSystem/FileSystemHelper.cs, src/OmniSharp.Stdio.Driver/app.config, tests/OmniSharp.Cake.Tests/CodeActionsV2Facts.cs, tests/OmniSharp.Roslyn.CSharp.Tests/CodeActionsV2Facts.cs, tests/OmniSharp.Roslyn.CSharp.Tests/FilesChangedFacts.cs, tests/OmniSharp.Roslyn.CSharp.Tests/SignatureHelpFacts.cs, tests/OmniSharp.Roslyn.CSharp.Tests/SyncNamespaceFacts.cs, tests/TestUtility/AbstractCodeActionsTestFixture.cs, tests/TestUtility/AbstractTestFixture.cs, tests/TestUtility/OmniSharpTestHost.cs, tests/TestUtility/TestHelpers.cs, tests/app.config
Fixes #1475 
Demo (first from within a folder, and then from the root of the project):
We have actually PR-ed into Roslyn a change that opened up the necessary APIs to public https://github.com/dotnet/roslyn/pull/35486 to make it work.
This PR introduces a bump to Roslyn `3.3.0-beta1-19365-07` to have access to them - this is a build for the `dev16.3` release train. 
We also now track "folders" of the documents added to the workspace (the refactoring works off that) - which is basically a relative path.
Default namespace is, by default, the assembly name, unless overwritten by `<RootNamespace>` MsBuild property. A change in MsBuild project file is respected by us in real time (no need to restart OmniSharp), by updating the workspace accordingly. Unfortunately there is still a bug in …
=> Added support for "sync namespace" refactoring

CHANGELOG.md, build/Packages.props
With the update to Roslyn `3.3.0-beta2-19376-02` we introduced a critical `StackOverflowException` when performing code analysis on partial classes.
This is a bug described in https://github.com/dotnet/roslyn/issues/37567
It was fixed in https://github.com/dotnet/roslyn/pull/37623 and is available in `3.3.0-beta2-19401-05`.
We should merge this and release 1.34.2 soonest as the current version is unusable with analyzers+partial classes.
cc @akshita31 @jonsequitur who lured us into updating to that specific build in the first place 😀
=>  updated to Roslyn 3.3.0-beta2-19401-05 to address a StackOverflowException

CHANGELOG.md, src/OmniSharp.MSBuild/ProjectFile/ProjectFileInfo.ProjectData.cs, src/OmniSharp.MSBuild/ProjectFile/PropertyNames.cs, test-assets/test-projects/CSharp8AndNullableContext/CSharp8AndNullableContext.csproj, tests/OmniSharp.MSBuild.Tests/ProjectFileInfoTests.cs
since vs 16.2p1 the msbuild property to enable nullable reference types is called `Nullable` instead of `NullableContextOptions` (this is LDM decision).
see related PRs here: https://github.com/dotnet/roslyn/pull/35516 and here https://github.com/dotnet/docs/pull/12497
issue reported by @shoe-diamente - thanks!
=> renamed NullableContextOptions to Nullable

build.cake, build.json, scripts/common.cake, test-assets/test-projects/DeepProjectTransitiveReference/App/App.csproj, test-assets/test-projects/HelloWorldSlim/HelloWorldSlim.csproj, test-assets/test-projects/MSTestProject/MSTestProject.csproj, test-assets/test-projects/NUnitTestProject/NUnitTestProject.csproj, test-assets/test-projects/NetStandardAndNetCoreApp/NetStandardAndNetCoreApp.csproj, test-assets/test-projects/ProjectAndSolution/ProjectAndSolution.csproj, test-assets/test-projects/ProjectAndSolutionWithProjectSection/ProjectAndSolutionWithProjectSection.csproj, test-assets/test-projects/ProjectWithGeneratedFile/ProjectWithGeneratedFile.csproj, test-assets/test-projects/ProjectWithMismatchedFileName/ProjectWithMismatchedFileName.csproj, test-assets/test-projects/ProjectWithMissingType/ProjectWithMissingType.csproj, test-assets/test-projects/ProjectWithMultiTFMLib/App/App.csproj, test-assets/test-projects/TwoProjectsWithSolution/App/App.csproj, test-assets/test-projects/XunitTestProject/XunitTestProject.csproj, tests/OmniSharp.Cake.Tests/TestAssets/multi.cake.g.txt, tests/OmniSharp.Cake.Tests/TestAssets/single.cake.g.txt, tests/OmniSharp.DotNetTest.Tests/GetTestStartInfoFacts.cs, tests/OmniSharp.DotNetTest.Tests/RunTestFacts.cs, tests/OmniSharp.MSBuild.Tests/ProjectFileInfoTests.cs, tests/OmniSharp.MSBuild.Tests/WorkspaceInformationTests.cs
We dropped .NET Core 1.x support a while ago (#1539) however some of the test projects were still targeting 1.x (!).
The result was the test suite was testing something we didn't support 😂
This PR moves test projects to 2.1 LTS and updates the build accordingly (build should be faster now too).
=> retarget test projects to .NET Core 2.1 (LTS)

tests/OmniSharp.MSBuild.Tests/ProjectWithComplexAnalyzersTests.cs, tests/TestUtility/ConditionalFactAttribute.cs
This is a follow up to https://github.com/OmniSharp/omnisharp-roslyn/pull/1562#issuecomment-522892213
While everything seemed fine in the PR/branch builds, we ran into the same thread starvation/deadlock issue on master build on MacOS.
Let's change the test to run on Windows for now and see if it helps.
=> run the complex analyzer test only on Windows

CHANGELOG.md, src/OmniSharp.MSBuild/ProjectFile/ProjectFileInfo.ProjectData.cs, src/OmniSharp.MSBuild/ProjectFile/ProjectFileInfo.cs, src/OmniSharp.MSBuild/ProjectFile/ProjectFileInfoExtensions.cs, src/OmniSharp.MSBuild/ProjectFile/PropertyNames.cs, test-assets/test-projects/HelloWorld/HelloWorld.csproj, tests/OmniSharp.MSBuild.Tests/ProjectFileInfoTests.cs
We now respect `<CheckForOverflowUnderflow>` setting when constructing compilation options.
This is equivalent to passing `/checked` switch to csc.
=>  added support for CheckForOverflowUnderflow in csproj

mono-packaging/copy-mono.sh, mono-packaging/copy-msbuild.sh
Mono/msbuild has facade assemblies for
`Microsoft.Build.{Tasks,Utilities}.v{4,12}.0` which typeforward to the
newer `*Core*` assemblies. Without these available in the msbuild bin
dir, mono will load the older (incomplete and deprecated) xbuild
versions of these from the gac, which can cause projects to break.
Here is mono loading the v4 assembly from gac:
```
Mono: Assembly Loader loaded assembly from location: '/Users/radical/.nuget/packages/grpc.tools/1.22.0-pre1/build/_protobuf/net45/Protobuf.MSBuild.dll'.
Mono: Loading reference 1 of /Users/radical/.nuget/packages/grpc.tools/1.22.0-pre1/build/_protobuf/net45/Protobuf.MSBuild.dll asmctx LOADFROM, looking for Microsoft.Build.Utilities.v4.0, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
Mono: Domain OmniSharp.exe …
```
=> Fix using task assemblies which reference older v4/v12 msbuild assemblies

BUILD.md, doc/Using-Omnisharp.md, src/OmniSharp.Host/MSBuild/Discovery/Providers/MonoInstanceProvider.cs, src/OmniSharp.Roslyn.CSharp/Services/Refactoring/V2/CachingCodeFixProviderForProjects.cs, src/OmniSharp.Roslyn.CSharp/Workers/Diagnostics/CSharpDiagnosticWorkerWithAnalyzers.cs, src/OmniSharp.Script/ScriptProjectSystem.cs, tests/OmniSharp.Roslyn.CSharp.Tests/AnalyzerWorkerQueueFacts.cs
A wrong `it's` was coming through in a VS Code debug window, fixing usage throughout the repo
=> Fix possessives of its

build/Settings.props
since the packages are now published to public nuget feed (i.e. https://www.nuget.org/packages/OmniSharp.Abstractions/) we need better metadata:
- license
- logo
- keywords
- repository information
=> updated metadata on the nuget packages

NuGet.Config, build/Packages.props, src/OmniSharp.Host/MSBuild/Discovery/MSBuildLocator.cs, tools/packages.config
I was able to reproduce the issue from https://github.com/OmniSharp/omnisharp-vscode/issues/3290 on my machine
This hopefully should fix it.
There is a separate issue where the "unresolved dependencies" pop up shows up continuously because of `Microsoft.NetCore.App` not being there in assets.json file anymore but we will handle this separately.
=> upgrade msbuild to 16.3

azure-pipelines.yml, scripts/common.cake
This fixes the build crash with GitVersion on Ubuntu 18.04
fixes https://github.com/OmniSharp/omnisharp-roslyn/issues/1548
fixes https://github.com/OmniSharp/omnisharp-roslyn/issues/1500
fixes https://github.com/OmniSharp/omnisharp-roslyn/issues/1251
fixes https://github.com/OmniSharp/omnisharp-roslyn/issues/1202
fixes https://github.com/OmniSharp/omnisharp-roslyn/issues/1048
=> upgrade GitVersion to 5.0.1 (fixes build on Ubuntu 18.04 and other distros)

azure-pipelines.yml, build.cake, build.json, tests/OmniSharp.MSBuild.Tests/ProjectWithAnalyzersTests.cs
This is a follow up to #1606
We now copy the MsBuild 16.3 from Mono 6.4.0, rather than the custom package we had in the past.
=> use msbuild from Mono 6.4.0 on linux/macos

azure-pipelines.yml, build.cake
This should finally allow us to close the famous issue https://github.com/OmniSharp/omnisharp-vscode/issues/3290
This is a follow up to #1606 which fixed the problem on Windows (confirmed by users) and follow up to #1607 which fixed the problem on Mac (also confirmed by users.
We still had the issue on Linux even though I wasn't able to initially reproduce it locally. Turns out, when we run on Azure DevOps we have Mono 6.0.0 (MSBuild 16.3) and Mono 6.4.0 (MSBuild 16.3) side by side and we copied from a wrong place... 😇 Also changed the distro from stable-xenial to vs-xenial.
=> Make sure we include msbuild 16.3 in Linux distro

azure-pipelines.yml
It appears the latest azure devops doesn't trigger off the old configuration (was used be done through the UI like 8 months ago).
cc @rchande @filipw @mholo65
=> Codify azure devops branch based triggers and pr configuration

NuGet.Config, build/Packages.props, src/OmniSharp.Script/ScriptContext.cs, src/OmniSharp.Script/ScriptContextProvider.cs, src/OmniSharp.Script/ScriptOptions.cs, src/OmniSharp.Script/ScriptProjectProvider.cs, src/OmniSharp.Script/ScriptProjectSystem.cs
This PR bumps the `Dotnet.Script.DependencyModel` and `Dotnet.Script.DependencyModel.NuGet` packages to version `0.50.0` adding support for .Net Core 3.0 based scripts.
=> Bump Dotnet.Script.DependencyModel to version 0.50.0

CHANGELOG.md, src/OmniSharp.Abstractions/Models/v1/GotoDefinition/GotoDefinitionResponse.cs, tests/OmniSharp.Roslyn.CSharp.Tests/GoToDefinitionFacts.cs
Unfortunately https://github.com/OmniSharp/omnisharp-roslyn/pull/1582 introduced a pretty bad regression - as it broke "go to metadata".
This then shipped with 1.34.4. 😩
This PR fixes it and introduces an extra assert that would have caught the regression.
Fixes #1624
=> Fixed "go to metadata"

src/OmniSharp.Roslyn/Utilities/CompilationOptionsHelper.cs, src/OmniSharp.Script/ScriptProjectProvider.cs
Follow up to #1609 
The diagnostics were inadvertently overridden instead of merged.
cc @seesharper
=> fixed default diagnostic suppressions for script project system

build.json, src/OmniSharp.Host/MSBuild/Discovery/Providers/MonoInstanceProvider.cs, src/OmniSharp.Host/MSBuild/Discovery/Providers/StandAloneInstanceProvider.cs, tests/OmniSharp.MSBuild.Tests/MSBuildSelectionTests.cs
It is required for netcoreapp3.0 as it comes with MSBuild 16.3.
Since we don't discover Mono per-project type but globally at OmniSharp start, the only reasonable choice at the moment - to avoid lots of error reports from users, which we do have these days - is to raise the minimum discovered version to 6.4.0.
=> raise minimum Mono version to 6.4.0

src/OmniSharp.Cake/CachingScriptMetadataResolver.cs, src/OmniSharp.Script/CachingScriptMetadataResolver.cs
This PR fixes a bug that was caused by multiple threads accessing the `DirectReferenceCache` and the `MissingReferenceCache` inside the `CachingScriptMetadataResolver` 
Occasionally, OmniSharp would fail to initialize for `csx` files with the following output from the `OmniSharp` log
```
"Message": "\"System.InvalidOperationException: Operations that change non-concurrent collections must have exclusive access. A concurrent update was performed on this collection and corrupted its state. The collection's state is no longer correct.\\n  at System.Collections.Generic.Dictionary`2[TKey,TValue].FindEntry (TKey key) [0x00105] in <0523ad94f2e04325802cd231c518c8d9>:0 \\n  at System.Collections.Generic.Dictionary`2[TKey,TValue].ContainsKey (TKey key) [0x00000] in …
```
=> Use ConcurrentDictionary in CachingScriptMetadataResolver

CHANGELOG.md, src/OmniSharp.Roslyn/MetadataHelper.cs
`GetAndAddDocumentFromMetadata` doesn't respect the passed-in cancellation token.
=> correctly use cancellation token in Metadata service

src/OmniSharp.Roslyn.CSharp/Helpers/DiagnosticExtensions.cs, tests/OmniSharp.MSBuild.Tests/ProjectWithAnalyzersTests.cs, tests/OmniSharp.MSBuild.Tests/ProjectWithComplexAnalyzersTests.cs, tests/OmniSharp.Roslyn.CSharp.Tests/BufferManagerMiscFilesFacts.cs, tests/OmniSharp.Roslyn.CSharp.Tests/CustomRoslynAnalyzerFacts.cs, tests/OmniSharp.Roslyn.CSharp.Tests/DiagnosticsFacts.cs, tests/OmniSharp.Roslyn.CSharp.Tests/EditorConfigFacts.cs, tests/OmniSharp.Roslyn.CSharp.Tests/ReAnalysisFacts.cs
Relates to https://github.com/OmniSharp/omnisharp-roslyn/issues/1622
In VSCode, the diagnostic id should better be passed in the `code` attribute. Having it also in the message lead to duplication in the UI.
=> Remove diagnostic id from message

CHANGELOG.md, build/Packages.props, src/OmniSharp.Roslyn.CSharp/Services/Signatures/SignatureHelpService.cs, src/OmniSharp.Roslyn.CSharp/Workers/Intellisense/SnippetGenerator.cs, src/OmniSharp.Roslyn/Extensions/SymbolExtensions.cs, tests/OmniSharp.Roslyn.CSharp.Tests/DiagnosticsFacts.cs
We have fallen behind the schedule a bit (especially with .NET Core 3.1 Preview 1 out already). We had consumed `3.4.0-beta1-19460-02` over a month ago but even Nuget publicly has a newer version now.
This PR pulls in the latest build intended for VS 16.4.
=> updated to Roslyn 3.4.0-beta3-19516-01

CHANGELOG.md, build/Packages.props
Update Roslyn to align with the upcoming .NET Core 3.1 Preview 3
=> Update Roslyn to 3.4.0-beta3-19551-02

CHANGELOG.md, build/Packages.props, src/OmniSharp.Abstractions/Configuration.cs, src/OmniSharp.Http.Driver/app.config, src/OmniSharp.Stdio.Driver/app.config, tests/app.config
contains a useful fix for us https://github.com/dotnet/roslyn/pull/39258
improved .net core 3.1 support
=> updated to Roslyn 3.5.0-beta1-19564-02

CHANGELOG.md, build/Packages.props
This updates Roslyn to the build we expect to ship in 16.5 preview 1.
=> Update Roslyn to 3.5.0-beta1-19571-01

src/OmniSharp.Host/MSBuild/Discovery/MSBuildLocator.cs, src/OmniSharp.Host/MSBuild/Discovery/Providers/StandAloneInstanceProvider.cs, tests/OmniSharp.MSBuild.Tests/AbstractMSBuildTestFixture.cs, tests/TestUtility/TestServiceProvider.cs
Since we now run in stand alone mode on top of mono 6.4.0 and raised the global mono minimum version to 6.4.0, we should not need to set mono paths in stand alone mode anymore. 
This fixes https://github.com/OmniSharp/omnisharp-vscode/issues/3410 and fixes https://github.com/OmniSharp/omnisharp-vscode/issues/3340 and a couple of other issues that I need to dig up (also lots of errors were reported as comments under old closed issues). In short the problem was, if you have old Mono (say 5.4.0) installed, we don't pick it as global Mono as it's < 6.4.0 and run in standalone mode. However we still set:
```
TargetFrameworkRootPath = /Library/Frameworks/Mono.framework/Versions/5.4.0/lib/mono/xbuild-frameworks
MSBuildExtensionsPath = /Library/Frameworks/Mono.framework/Versions/5.4.0/lib/mono/xbu …
```
=> do not set mono paths in standalone mode

tests/OmniSharp.Roslyn.CSharp.Tests/GoToDefinitionFacts.cs
In some cases GoToDefinitionFacts were already running for standard C# and for C# scripts, this PR enables more tests to run in both variants.
=> enabled some GoToDefinitionFacts for CSX

CHANGELOG.md, src/OmniSharp.Host/CommandLineApplication.cs, tests/OmniSharp.Tests/CommandLineApplicationFacts.cs, tests/OmniSharp.Tests/OmniSharpEnvironmentFacts.cs
Fixes https://github.com/OmniSharp/omnisharp-vscode/issues/3436
=> do not crash on "=" in solution path

CHANGELOG.md, src/OmniSharp.Roslyn.CSharp/Helpers/LocationExtensions.cs, tests/OmniSharp.Roslyn.CSharp.Tests/FindReferencesFacts.cs
Fixes #1649 
If the mapping goes to an external file, we assume column 0,0
=> Support #line directive in find references

CHANGELOG.md, build/Packages.props, tools/packages.config
stable releases are public so we can drop the pre-release references
please note that on *nix we copy msbuild from Mono so until 6.6.0 is released, we still use 6.4.0 which has msbuild 16.3
=> updated to msbuild 16.4.0 and Microsoft.NETFramework.ReferenceAssemblies 1.0.0

CHANGELOG.md, build/Packages.props, tests/OmniSharp.Cake.Tests/CodeActionsV2Facts.cs, tests/OmniSharp.Roslyn.CSharp.Tests/CodeActionsV2Facts.cs, tests/OmniSharp.Roslyn.CSharp.Tests/CodeActionsWithOptionsFacts.cs, tools/packages.config
Updates to a 16.5 Preview2 build of roslyn
[View Complete Diff of Changes](https://www.github.com/dotnet/roslyn/compare/fb3f812...e8ab154)
- [More tests for [MaybeNull] (39983)](https://www.github.com/dotnet/roslyn/pull/39983)
- [Nullable collections (40029)](https://www.github.com/dotnet/roslyn/pull/40029)
- [Make finding checksum async (40091)](https://www.github.com/dotnet/roslyn/pull/40091)
- [Fix AllowNull/DisallowNull in object initializers (40127)](https://www.github.com/dotnet/roslyn/pull/40127)
- [Convert operand expressions in an error case (40093)](https://www.github.com/dotnet/roslyn/pull/40093)
- [Remove the nullable wrappers from the Workspaces layer (40030)](https://www.github.com/dotnet/roslyn/pull/40030)
- [Diagnostics refactoring …
=> Update Roslyn to 3.5.0-beta2-19606-01

CHANGELOG.md, azure-pipelines.yml, build.json
Mono 6.6.0 is now stable and it comes with MSBuild 16.4.0
Since we copy MsBuild from global Mono at build time, updated the build steps to use Mono 6.6.0.
This follows up to #1662 which moved us to MsBuild 16.4.0 on Windows,  but on *nix we stayed on 16.3 since we copied it at package time from Mono 6.4.0.
=> Updated build process to use Mono 6.6.0

CHANGELOG.md, src/OmniSharp.Roslyn.CSharp/Services/Intellisense/CompletionItemExtensions.cs, tests/OmniSharp.Roslyn.CSharp.Tests/IntellisenseFacts.cs
This got broken a while ago - around these changes https://github.com/OmniSharp/omnisharp-roslyn/commit/1f10506972481e5db2b44caa117e94f54e7f17be. It was fragile, as it's reflection.
It impacts the quality of some of the completion item driven completions, which we don't use a lot but nevertheless - i.e. object initializer, which were missing symbol information.
fixes https://github.com/OmniSharp/omnisharp-vscode/issues/3465
=> fixed symbol decoding from completion items

src/OmniSharp.Roslyn.CSharp/Services/Refactoring/V2/CachingCodeFixProviderForProjects.cs
Also, do not report code fix providers that are missing `ExportCodeFixProviderAttribute` as INFO - this leads to confusing messages in the logs like:
```
[info]: OmniSharp.Roslyn.CSharp.Services.Refactoring.V2.CachingCodeFixProviderForProjects
Skipping code fix provider 'Microsoft.CodeQuality.Analyzers.QualityGuidelines.MarkMembersAsStaticFixer' because its language doesn't match 'C#'.
```
This happens for all base types used by code fixes, which are not intended for discovery in the first place.
From now on, we should only attempt to instantiate non-abstract code fixes marked with `ExportCodeFixProviderAttribute`.
cc @savpek
=> Do not discover abstract types as candidates for code fix providers

src/OmniSharp.Roslyn.CSharp/Services/ImplementTypeWorkspaceOptionsProvider.cs, src/OmniSharp.Shared/Options/ImplementTypeOptions.cs, src/OmniSharp.Shared/Options/OmniSharpOptions.cs, tests/OmniSharp.Roslyn.CSharp.Tests/ImplementTypeFacts.cs
Similar to #1495 except for implement type options.
This allows users to set i.e. property generation style (see https://github.com/OmniSharp/omnisharp-vscode/issues/2392).
This can be configured in Visual Studio so makes sense that we expose it too. The defaults remain like in Roslyn.
=> added implement type options

CHANGELOG.md, build/Packages.props, src/OmniSharp.Roslyn.CSharp/OmniSharp.Roslyn.CSharp.csproj
Since https://github.com/dotnet/roslyn/pull/36237 was merged into Roslyn, we can now remove the hack where we needed to reference Humanizer.
=> Upgraded to Roslyn 3.5.0-beta3-20058-03 and removed Humanizer

src/OmniSharp.Roslyn.CSharp/Workers/Formatting/FormattingWorker.cs, src/OmniSharp.Shared/Options/FormattingOptions.cs, tests/OmniSharp.Roslyn.CSharp.Tests/FormattingFacts.cs
The organize imports formatting feature is now public in Roslyn.
Added as a flag since we have an approach to make all these things configurable and opt-in.
=> Added support for organizing imports in formatting

tools/packages.config
Fixes the build failure on linux.
I came up with the fix on my own 😀
The old version doesn't work anymore on Linux build agents and all builds fail.
=> updated to Cake 0.37.0

NuGet.Config, build.cake, tools/packages.config
Fixes https://github.com/OmniSharp/omnisharp-roslyn/issues/1678
Tested with dotnet/format repo which relies on the 'Microsoft.DotNet.Arcade.Sdk'
=> Add NuGetSdkResolver to minimal msbuild

CHANGELOG.md
https://github.com/OmniSharp/omnisharp-roslyn/pull/1697 and https://github.com/OmniSharp/omnisharp-roslyn/pull/1696
=> added latest changes to changelog

src/OmniSharp.Roslyn.CSharp/Helpers/LocationExtensions.cs, tests/OmniSharp.Roslyn.CSharp.Tests/FindReferencesFacts.cs
Fixes https://github.com/OmniSharp/omnisharp-vscode/issues/3485
Also added more comprehensive tests.
Here is the summary of the logic:
- correct mapping within a file - then we return the mapped line and mapped text
- incorrect mapping within a file - then we return the mapped line (even though it's incorrect) and the original (unmapped) text since there is no way to fetch the mapped text as it's out of bounds
- correct mapping into a file that exists in a workspace - then we return the mapped line and mapped text from that file
- incorrect mapping into a file that exists in a workspace - then we return the mapped line and the original (unmapped) text since there is no way to fetch the mapped text as it's out of bounds
- mapping into a file that does not exist in a workspace - then we …
=> fixed out of bounds in line mapping

CHANGELOG.md
=> PRs #1707 and #1701 in changelog

CHANGELOG.md, src/OmniSharp.Host/MSBuild/Discovery/Extensions.cs, src/OmniSharp.Host/MSBuild/Discovery/Providers/MonoInstanceProvider.cs, src/OmniSharp.Host/MSBuild/Discovery/Providers/StandAloneInstanceProvider.cs, tests/OmniSharp.MSBuild.Tests/MSBuildSelectionTests.cs
As discussed before.
Fixes #1700
=> Raised the minimum picked up VS version to 16.3

CHANGELOG.md, src/OmniSharp.Roslyn.CSharp/Workers/Formatting/FormattingWorker.cs, tests/OmniSharp.Roslyn.CSharp.Tests/EditorConfigFacts.cs
when organize usings was enabled, it prevented the regular formatting from working since it passed in the original document... 🙈
@JoeRobich after this is merged, let's release again so that you don't ship the buggy version in VS Code
=> Fixed a bug where organizing usings clashed with other formatting settings

src/OmniSharp.DotNetTest/DebugSessionManager.cs, src/OmniSharp.DotNetTest/Models/BaseTestClassRequest.cs, src/OmniSharp.DotNetTest/Models/DebugTestGetStartInfoRequest.cs, src/OmniSharp.DotNetTest/Models/GetTestStartInfoRequest.cs, src/OmniSharp.DotNetTest/Models/RunTestRequest.cs, src/OmniSharp.DotNetTest/Services/DebugTestClassService.cs, src/OmniSharp.DotNetTest/Services/DebugTestService.cs, src/OmniSharp.DotNetTest/Services/GetTestStartInfoService.cs, src/OmniSharp.DotNetTest/Services/RunTestService.cs, src/OmniSharp.DotNetTest/Services/RunTestsInClassService.cs, src/OmniSharp.DotNetTest/TestManager.cs, src/OmniSharp.DotNetTest/VSTestManager.cs, test-assets/test-projects/MSTestProject/TestProgram.cs, test-assets/test-projects/MSTestProject/TestRunSettings.runsettings, tests/OmniSharp.DotNetTest.Tests/AbstractRunTestFacts.cs, tests/OmniSharp.DotNetTest.Tests/RunTestFacts.cs
Currently, the RunSettings are sent to Omnisharp as a a path, and then loaded. Alternatively, we could load the runsettings in the extension, and then send XML with the request.
Related PR to omnisharp-vscode: https://github.com/OmniSharp/omnisharp-vscode/pull/3573
=> Add ability to use custom runsettings for tests

CHANGELOG.md, src/OmniSharp.MSBuild/ProjectFile/PropertyConverter.cs
=> added support for "annotations" in nullable context options

src/OmniSharp.Roslyn.CSharp/Services/Highlighting/HighlightingService.cs, tests/OmniSharp.Roslyn.CSharp.Tests/HighlightFacts.cs
Currently the behavior of the "/highlight" request is not deterministic for static symbols. This is because the Classifier class returns two ClassifiedSpans for static symbols (one with the actual kind and one with kind "static symbol"). And depending on which of the two spans is returned first in the result we get a different highlight span.
I propose a change where we remove these "additive" kinds from the result, only returning the actual kind of the span.
Fixes #1576
=> Exclude additive classifications from "/highlight" requests

CHANGELOG.md, build/Packages.props
new version was released yesterday
this is needed to support .net core 3.1 based scripting refs
=> updated to dotnet script 0.51

mono-packaging/run
Reported in https://github.com/OmniSharp/omnisharp-vscode/issues/3608
Other use of `{mono_cmd}` were already quoted just looks like this one was missed.
=> Quote the path to mono in run script

CHANGELOG.md, build/Packages.props, src/OmniSharp.Abstractions/Configuration.cs, src/OmniSharp.Host/WorkspaceInitializer.cs, src/OmniSharp.Http.Driver/app.config, src/OmniSharp.Roslyn.CSharp/Services/Formatting/EditorConfig/EditorConfigOptionsApplier.cs, src/OmniSharp.Roslyn.CSharp/Workers/Diagnostics/CSharpDiagnosticWorkerWithAnalyzers.cs, src/OmniSharp.Stdio.Driver/app.config, test-assets/test-projects/ProjectWithComplexAnalyzers/ProjectWithComplexAnalyzers.csproj, tests/OmniSharp.Roslyn.CSharp.Tests/FormattingFacts.cs, tests/app.config
there were some internal breaking changes that I needed to address
=> Updated to Roslyn 3.6.0

src/OmniSharp.Roslyn.CSharp/Services/DocumentationConverter.cs, tests/OmniSharp.Roslyn.CSharp.Tests/DocumentationConverterFacts.cs
Handle typeparam doc comment similar to param. Instead of `{Name}: Description` list them as `<{Name}>: Description`.
Resolves https://github.com/OmniSharp/omnisharp-vscode/issues/3516
=> Add typeparam to description text

CHANGELOG.md, src/OmniSharp.Roslyn.CSharp/Services/BlockStructureWorkspaceOptionsProvider.cs, src/OmniSharp.Roslyn.CSharp/Services/Structure/BlockStructureService.cs, tests/OmniSharp.Roslyn.CSharp.Tests/BlockStructureFacts.cs
For Roslyn to tag Region blocks, options in BlockStructureOptions need to be set to true. We also need to convert from the type PreprocessorRegion to Region in the BlockStructureService.
Resolves https://github.com/OmniSharp/omnisharp-vscode/issues/2621
=> Include Region blocks in code folding

CHANGELOG.md, src/OmniSharp.Roslyn.CSharp/OmniSharp.Roslyn.CSharp.csproj, src/OmniSharp.Roslyn.CSharp/Services/Decompilation/DecompilationExternalSourceService.cs, src/OmniSharp.Roslyn.CSharp/Services/Decompilation/OmniSharpCSharpDecompiledSourceService.cs
See the discussion here https://github.com/icsharpcode/ilspy-vscode/issues/45#issuecomment-613473929
Long story short, searching for ref assemblies in GAC results in no-definition found - Not Supported exception on Mono. This means that we can't decompile into BCL types on Mono. On Windows it "works" - as in, it doesn't crash, but it doesn't find implementation assemblies anyway.
This PR removes any attempt to handle ref assemblies; this means things should always decompile fine, but we won't find implementation assemblies. This is consistent with VS experience where ref assemblies are decompiled instead of implementation assemblies.
It's a super complex topic, and we can improve on that gradually in the future (or maybe VS implementation will improve).
=> removed any attempt to handle ref assemblies via GAC when decompiling

src/OmniSharp.DotNetTest/VSTestManager.cs, test-assets/test-projects/NUnitTestProject/TestProgram.cs, tests/OmniSharp.DotNetTest.Tests/RunTestFacts.cs, tests/OmniSharp.DotNetTest.Tests/TestDiscoveryFacts.cs
Resolves https://github.com/OmniSharp/omnisharp-vscode/issues/3722
=> Update test method matching to support generic classes

build.json, src/OmniSharp.MSBuild/ProjectManager.cs, src/OmniSharp.Roslyn/EditorConfig/EditorConfigFinder.cs, test-assets/test-projects/ProjectWithParentEditorConfig/.editorconfig, test-assets/test-projects/ProjectWithParentEditorConfig/Project/Program.cs, test-assets/test-projects/ProjectWithParentEditorConfig/Project/Project.csproj, test-assets/test-projects/ProjectWithParentEditorConfig/ProjectWithParentEditorConfig.sln, tests/OmniSharp.MSBuild.Tests/ProjectWithAnalyzersTests.cs
As [mentioned here](https://github.com/OmniSharp/omnisharp-roslyn/pull/1771#discussion_r411989013), we should also be looking for changes to .editorconfig files in folders above the project folder.
=> Watch .editorconfig files in folders above the project folder.

NuGet.Config
It is no longer needed since we removed `Microsoft.VisualStudio.CodingConventions`
=> Removed vs-editor feed

CHANGELOG.md, src/OmniSharp.MSBuild/ProjectFile/ProjectFileInfo.ProjectData.cs, src/OmniSharp.MSBuild/ProjectFile/ProjectFileInfo.cs, src/OmniSharp.MSBuild/ProjectFile/ProjectFileInfoExtensions.cs, src/OmniSharp.MSBuild/ProjectFile/PropertyConverter.cs, src/OmniSharp.MSBuild/ProjectFile/PropertyNames.cs, test-assets/test-projects/WarningsAsErrors/Program.cs, test-assets/test-projects/WarningsAsErrors/WarningsAsErrors.csproj, tests/OmniSharp.MSBuild.Tests/ProjectFileInfoTests.cs
> WarningsAsErrors is a list of warnings that should be treated as errors.
> TreatWarningsAsErrors is the boolean that lifts all warnings to errors.
We never supported `WarningsAsErrors`, only `TreatWarningsAsErrors`
=> added support for WarningsAsErrors msbuild property

build/Packages.props, src/OmniSharp.LanguageServerProtocol/Handlers/OmniSharpTextDocumentSyncHandler.cs, src/OmniSharp.LanguageServerProtocol/LanguageServerHost.cs
See https://github.com/OmniSharp/csharp-language-server-protocol/pull/199
This is a more conservative version of my previous PR to fix LSP synchronisation issues:
- https://github.com/OmniSharp/omnisharp-roslyn/pull/1754
I'd consider this one for merge, as it does not require introducing ProgressManager as the PR for upgrade to 0.16.0 does.
=> Update OmniSharp.Extensions.LanguageServer to "0.14.2" to fix synchronisation

BUILD.md
Update the minimum version required when installing standalone Mono.
=> Update Mono minimum version to match README

CHANGELOG.md, src/OmniSharp.Host/MSBuild/Discovery/Extensions.cs, tests/OmniSharp.MSBuild.Tests/MSBuildSelectionTests.cs
Fixes #1783 
We should compare full versions rather than just major. Otherwise the selection is non deterministic, for example if 16.4 is discovered before 16.6, 16.4 would be used.
=> Improved msbuild discovery scoring

CHANGELOG.md, src/OmniSharp.LanguageServerProtocol/Handlers/OmniSharpCodeLensHandler.cs, src/OmniSharp.LanguageServerProtocol/Handlers/OmniSharpExecuteCommandHandler.cs, src/OmniSharp.LanguageServerProtocol/LanguageServerHost.cs
This exposes a custom `omnisharp/client/findReferences` command that is meant to be handled by LSP client to display references at given `Location`.
Since this is a custom command there needs to be changes made per-LSP client to handle this command, issue a `textDocument/references` request at given `Location` and display that on UI.
=> LSP: expose omnisharp/client/findReferences custom command for code lenses

azure-pipelines.yml
Last month Azure DevOps finally got Ubuntu 18.04 images - we should upgrade as we should be testing on this most popular version of Ubuntu.
=> upgraded build agent to ubuntu 18.04

src/OmniSharp.Abstractions/FileWatching/FileChangeType.cs, src/OmniSharp.Abstractions/FileWatching/IFileSystemWatcher.cs, src/OmniSharp.Host/FileWatching/ManualFileSystemWatcher.cs, src/OmniSharp.Roslyn/OmniSharpWorkspace.cs, tests/OmniSharp.Cake.Tests/LineIndexHelperFacts.cs, tests/OmniSharp.Roslyn.CSharp.Tests/FilesChangedFacts.cs
VSCode has issue (however by design at current version) where removed folders doesn't send any notifications of removed files because file watcher has some kind of performance optimizations to ignore them.
However watching folders removal is possible. This PR adds support for omnishar-roslyn side so clients can notify removed directory instead of single files if needed -> which can be impelemented properly with current VSCode file watcher.
This fixes one of most common issue that requires omnisharp restart on any directory rename/move/... operation.
Vscode side implementation: https://github.com/OmniSharp/omnisharp-vscode/pull/3829
=> Fix folder deletion with VSCode

CHANGELOG.md, src/OmniSharp.Abstractions/Plugins/PluginAssemblies.cs, src/OmniSharp.Abstractions/Services/IAssemblyLoader.cs, src/OmniSharp.Host/CompositionHostBuilder.cs
Fixes #1307 
The assembly loader returns null when an assembly cannot be loaded by name, which - at the moment - would lead to a null reference exception when starting OmniSharp.
=> Do not crash when plugin assembly cannot be found

BUILD.md
The Build-Readme still had Release as default.
=> The buildscript configuration parameter default value is is Debug

CHANGELOG.md, src/OmniSharp.Host/MSBuild/Discovery/Extensions.cs, tests/OmniSharp.MSBuild.Tests/MSBuildSelectionTests.cs
This is an aggressive change, similar to when we dropped VS < 16.3 to support .NET core better, one that I believe is necessary to improve user experience.
**We will no longer select MSBuild from VS instance, if that instance doesn't have .NET SDK resolvers**. The rationale is that vast majority of users want to use new SDK based projects, and not having it along the selected MSBuild instance currently leads into a broken state without much info of what went wrong. 
If someone is negatively affected - doesn't need .NET SDK (old style projects, unity) and now gets shifted to stand alone instance, they can still use the MSBuild override feature. This is similar to what we recommended to VS 2017 users back in the day. 
Additionally, I improved the warning messages:
- we now print a warning …
=> only select MSBuild from VS if .NET SDK Resolvers are present 

CHANGELOG.md, src/OmniSharp.MSBuild/ProjectLoader.cs
see: https://github.com/dotnet/runtime/issues/33427#issuecomment-597634844
fixes https://github.com/OmniSharp/omnisharp-roslyn/issues/1738
=> use global property when resetting TargetFramework

build.json, test-assets/test-projects/Net50Project/global.json, tests/OmniSharp.MSBuild.Tests/ProjectLoadListenerTests.cs
It was released at the end of June, we should be up to date
=> updated tests to .NET SDK 5.0.100-preview.6.20318.15

src/OmniSharp.Abstractions/Models/v1/FindSymbols/FindSymbolsRequest.cs, src/OmniSharp.Abstractions/Models/v1/FindSymbols/OmniSharpSymbolFilter.cs, src/OmniSharp.Cake/Services/RequestHandlers/Navigation/FindSymbolsHandler.cs, src/OmniSharp.Roslyn.CSharp/Services/Navigation/FindSymbolsService.cs, src/OmniSharp.Roslyn/Extensions/SolutionExtensions.cs, tests/OmniSharp.Roslyn.CSharp.Tests/FindSymbolsFacts.cs
FindSymbols Endpoint now exposes a `SymbolFilter` Property. This enables the Client to specify what Symbols he is interested in. Previously `SymbolFilter.TypeAndMember` was used by default. Especially in larger projects this results in poor performance.
=> Allow client to specify symbol filter for FindSymbols Endpoint.

azure-pipelines.yml, build.cake, build/Packages.props, tools/packages.config
Mono 6.10.0 is stable now. MsBuild 16.6 is also stable and the missing targets fix the currently broken build on Linux.
@JoeRobich after this is merged could you please also upgrade the embedded mono ZIPs that get downloaded at build time as dependencies? thanks
=> upgraded to Mono 6.10.0.105, msbuild 16.6 and added missing targets

build.json, test-assets/test-projects/Net50Project/global.json, tests/OmniSharp.MSBuild.Tests/ProjectLoadListenerTests.cs
It was released a couple of hours ago, we should be up to date
=> Updated .NET 5 tests to use 5.0.100-preview.7.20366.6

CHANGELOG.md, src/OmniSharp.MSBuild/ProjectFile/ProjectFileInfo.cs, src/OmniSharp.MSBuild/ProjectManager.cs, src/OmniSharp.MSBuild/ProjectSystem.cs, tests/OmniSharp.MSBuild.Tests/ProjectFileInfoTests.cs
Fixes https://github.com/OmniSharp/omnisharp-roslyn/issues/1844
Although each project *could* define their own global.json with differing sdks, in practice there is no need to request dotnet info for each loaded project.
=> Only request dotnet info once for the solution or directory

src/OmniSharp.DotNetTest/VSTestManager.cs
Fix getting TestProcessStartInfo for unit tests by not setting the DebuggingEnabled flag on the request message. See https://github.com/microsoft/vstest/issues/2468
Fixes https://github.com/OmniSharp/omnisharp-vscode/issues/3459
Creates `GetTestRunnerProcessStartInfo` method with message processing loop. This allows us to print TestMessages to help with troubleshooting in case there are problems in the future.
=> Fix getting ProcessStartInfo for tests

CHANGELOG.md, src/OmniSharp.Roslyn.CSharp/Services/Intellisense/CompletionItemExtensions.cs, src/OmniSharp.Roslyn.CSharp/Services/Intellisense/IntellisenseService.cs, tests/OmniSharp.Roslyn.CSharp.Tests/IntellisenseFacts.cs
This is quite new in Roslyn. It gives completion results for e.g. datetime string literals and regex patterns
=> added support for EmbeddedLanguageCompletionProvider

NuGet.Config, build/Packages.props, tools/packages.config
Not sure whether we would want the included build tools to match the .NET SDK tools or the latest VS preview tools.
=> Update Roslyn version and tools to match .NET 5 Preview8

src/OmniSharp.LanguageServerProtocol/Handlers/OmniSharpHoverHandler.cs, src/OmniSharp.LanguageServerProtocol/Helpers.cs, src/OmniSharp.Roslyn.CSharp/Services/QuickInfoProvider.cs, src/OmniSharp.Shared/Utilities/MarkdownHelpers.cs, tests/OmniSharp.Roslyn.CSharp.Tests/QuickInfoProviderFacts.cs
@david-driscoll this does what it says on the tin. Hopefully this will be another thing that we can get working in vscode. I'm unsure what the `Range` in LSP represents here, though: is it supposed to be full range of the thing being hovered over? If so, I'm not sure if we actually _want_ to implement that: I'm used to highlighting either getting every instance of a thing, or not highlighting it at all. If we do want to implement that, though, it would be very straightforward to add, as QuickInfo already has the info.
Fixes https://github.com/OmniSharp/omnisharp-roslyn/issues/1806.
=> Move the Hover LSP provider to use the new quickinfo service

build.cake, src/OmniSharp.Host/MSBuild/Discovery/MSBuildInstanceProvider.cs, src/OmniSharp.Host/MSBuild/Discovery/Providers/MonoInstanceProvider.cs, src/OmniSharp.Host/MSBuild/Discovery/Providers/StandAloneInstanceProvider.cs, src/OmniSharp.Host/MSBuild/Discovery/Providers/UserOverrideInstanceProvider.cs, tools/packages.config
Read the product version for the MSBuild that is discovered.
Makes https://github.com/OmniSharp/omnisharp-roslyn/pull/1875 more useful.
=> Use the real MSBuild version during discovery

src/OmniSharp.Abstractions/Services/DotNetInfo.cs, src/OmniSharp.Host/CompositionHostBuilder.cs, src/OmniSharp.Host/MSBuild/Discovery/Extensions.cs, src/OmniSharp.Http/Startup.cs, src/OmniSharp.LanguageServerProtocol/LanguageServerHost.cs, src/OmniSharp.Stdio/Host.cs, tests/OmniSharp.Http.Tests/EndpointMiddlewareFacts.cs, tests/OmniSharp.MSBuild.Tests/AbstractMSBuildTestFixture.cs, tests/OmniSharp.MSBuild.Tests/MSBuildSelectionTests.cs, tests/TestUtility/OmniSharpTestHost.cs
Provide a warning when the discovered MSBuild version is lower than the minimumMSBuildVersion supported by the configured SDK.
=> Check for MSBuild version is higher than required by the .NET SDK

build.cake, tools/packages.config
Instead of including the .target files from the Mono on the build machine. Overwrit those .target files with the versions from the MSBuild Runtime. Also, use the non-deprecated compiler toolset package.
=> Include version matched target files with minimal MSBuild

src/OmniSharp.Roslyn.CSharp/Helpers/MarkdownHelpers.cs, tests/OmniSharp.Roslyn.CSharp.Tests/QuickInfoProviderFacts.cs
When the section ended without a newline, we weren't correctly ending the italic section.
=> Fix lack of trailing italics

src/OmniSharp.Roslyn.CSharp/Helpers/MarkdownHelpers.cs, src/OmniSharp.Roslyn.CSharp/Services/Completion/CompletionService.cs, src/OmniSharp.Roslyn.CSharp/Services/QuickInfoProvider.cs, tests/OmniSharp.Roslyn.CSharp.Tests/QuickInfoProviderFacts.cs
Fixes https://github.com/OmniSharp/omnisharp-roslyn/issues/1899
=> Ensure that all quickinfo sections have linebreaks between them, and don't add unecessary duplicate linebreaks.

src/OmniSharp.Abstractions/Models/v1/Completion/CompletionItem.cs, src/OmniSharp.Roslyn.CSharp/Services/Completion/CompletionOptionsProvider.cs, src/OmniSharp.Roslyn.CSharp/Services/Completion/CompletionService.cs, src/OmniSharp.Roslyn.CSharp/Services/Intellisense/CompletionItemExtensions.cs, src/OmniSharp.Shared/Options/RoslynExtensionsOptions.cs, tests/OmniSharp.Roslyn.CSharp.Tests/CompletionFacts.cs
This needs to call a few internal overloads for completion, instead of the public versions, in order to determine whether any completions can be expanded (ie, imported) and to get the full change for these items, including the import. The public APIs do not provide this information currently.
Todo:
Preview of the change in vscode (watch the line numbers!):
Fixes https://github.com/OmniSharp/omnisharp-roslyn/issues/1482
=> Support completion of unimported types.

src/OmniSharp.Abstractions/Configuration.cs, src/OmniSharp.Roslyn.CSharp/Services/Completion/CompletionService.cs, src/OmniSharp.Roslyn.CSharp/Services/Intellisense/CompletionItemExtensions.cs, src/OmniSharp.Roslyn.CSharp/Workers/Diagnostics/CSharpDiagnosticWorker.cs, src/OmniSharp.Roslyn.CSharp/Workers/Diagnostics/CSharpDiagnosticWorkerWithAnalyzers.cs, src/OmniSharp.Roslyn/OmniSharpWorkspace.cs, tests/OmniSharp.Roslyn.CSharp.Tests/CompletionFacts.cs
The misc project for loose .cs files should not show up in InternalsVisibleTo suggestion.
cc @333fred
=> Exclude Misc project from InternalsVisibleTo completion

src/OmniSharp.Roslyn.CSharp/Services/Completion/CompletionService.cs, tests/OmniSharp.Roslyn.CSharp.Tests/CompletionFacts.cs
Prepend a '0' or '1' for already-imported and unimported things, respectively. This will ensure that things that are already imported will appear first in the list of completions, which is more likely to be what the user actually wants.
=> Ensure unimported things are sorted after imported things

build/Packages.props, src/OmniSharp.LanguageServerProtocol/Eventing/LanguageServerEventEmitter.cs, src/OmniSharp.LanguageServerProtocol/Helpers.cs, src/OmniSharp.LanguageServerProtocol/LanguageServerHost.cs, src/OmniSharp.Roslyn.CSharp/Helpers/DiagnosticExtensions.cs, src/OmniSharp.Roslyn.CSharp/Workers/Diagnostics/CSharpDiagnosticWorker.cs, tests/OmniSharp.Lsp.Tests/AbstractLanguageServerTestBase.cs, tests/OmniSharp.Lsp.Tests/OmnisharpPublishDiagnosticFacts.cs, tests/OmniSharp.Roslyn.CSharp.Tests/DiagnosticsFacts.cs
* Added LSP publish diagnostic tests
* Added diagnostic helper methods to `AbstractLanguageServerTestBase`
* OmniSharp events were not sending with the expected name (all lower case)
* Added Diagnostic tags
* Ensure LSP interop is always using parallel requests and responses - Avoids sending extra `Content Modified` errors,
LSP update Fixes: #1898
=> Upgrade lsp

build/Packages.props, src/OmniSharp.Roslyn.CSharp/Services/Decompilation/AssemblyResolver.cs, tests/OmniSharp.Roslyn.CSharp.Tests/GoToDefinitionFacts.cs
Similar to https://github.com/dotnet/roslyn/pull/46679
Release notes: https://github.com/icsharpcode/ILSpy/releases
Introduces some C# 9 feature support + plenty of C# 8 features
=> Updated to ILSpy 6.1.0.5902

build.json
This was mistakenly removed with a previous set of changes.
=> Add HTTP Driver back to build.json

build.cmd, scripts/common.cake
Using Bypass policy will avoid errors when running build.cmd on system that does not have ExecutionPolicy set in powershell.exe, or when running build.ps1 from PowerShell Core (pwsh.exe).
=> Use ExecutionPolicy Bypass when running powershell.exe

README.md
See https://lists.archlinux.org/pipermail/aur-requests/2020-August/043957.html .
=> Update the package that Arch Linux users need to install

src/OmniSharp.Host/CompositionHostBuilder.cs, src/OmniSharp.MSBuild/ProjectSystem.cs, tests/TestUtility/OmniSharpTestHost.cs
At the moment we run `dotnet --info` twice in the working directory when OmniSharp starts up.
This PR changes it to be once only, shaving about 300ms from the startup time (on my machine).
=> Only run dotnet --info once for the working directory

src/OmniSharp.Roslyn.CSharp/Services/Completion/CompletionService.cs
Namespace was set to Text kind in the #1877, but it should be set to Module kind. 
Fixes https://github.com/OmniSharp/omnisharp-vscode/issues/4051
=> Fix namespace icon

src/OmniSharp.Roslyn.CSharp/Services/Navigation/FindImplementationsService.cs, src/OmniSharp.Roslyn/Extensions/SymbolExtensions.cs
We don't need to call `FindImplementationsAsync` for every conceivable symbol.
=> improve find implementations

build.cmd, build.ps1
Use paths relative to the location of build.cmd and build.ps1 when looking for dependencies, this allows the build to be run from any current directory.
=> Allow build.cmd to run from any directory

CHANGELOG.md, src/OmniSharp.Cake/Extensions/ResponseExtensions.cs, src/OmniSharp.Cake/Services/RequestHandlers/Completion/CompletionHandler.cs, tests/OmniSharp.Cake.Tests/CompletionFacts.cs
=> Adds support for /completion and /completion/resolve endpoints for Cake.

src/OmniSharp.Roslyn.CSharp/Services/Completion/CompletionService.cs, src/OmniSharp.Roslyn.CSharp/Services/Intellisense/CompletionItemExtensions.cs, tests/OmniSharp.Roslyn.CSharp.Tests/CompletionFacts.cs
Depending on whether the context is a verbatim string or not, the regex provider will escape the text, so we need to realize it ahead of time. Fixes https://github.com/OmniSharp/omnisharp-roslyn/issues/1949.
=> Correct regex completion

src/OmniSharp.Roslyn.CSharp/Services/Intellisense/IntellisenseService.cs, tests/OmniSharp.Roslyn.CSharp.Tests/IntellisenseFacts.cs, tests/OmniSharp.Roslyn.CSharp.Tests/OmniSharp.Roslyn.CSharp.Tests.csproj
The clients should be switching to  `/completion` and `/completion/resolve`.
Additionally based on the conversation in https://github.com/OmniSharp/omnisharp-roslyn/pull/1950 I restored one deleted test as conditional on Windows only.
=> Marked /autocomplete as obsolete

build.cmd, build.ps1, src/OmniSharp.Roslyn.CSharp/Services/Completion/CompletionService.cs
When completion re-uses part of existing string the proposed change should re-use the part of the string in the original span and commit the change. 
Fix https://github.com/OmniSharp/omnisharp-vscode/issues/4063
=> Fix completion on part of existing string

src/OmniSharp.Http.Driver/app.config, src/OmniSharp.LanguageServerProtocol/app.config, src/OmniSharp.Stdio.Driver/app.config, tests/app.config
This is a best guess attempt to improve the behavior mentioned in https://github.com/OmniSharp/omnisharp-vscode/issues/4090
The error is vague but looks like somehow there are different versions of `CompletionList` loaded simultaneously. 
At the moment there are no binding redirects for its parent assembly `Microsoft.CodeAnalysis.Features` so it wouldn't hurt to add that.
cc @333fred
=> added binding redirects for Microsoft.CodeAnalysis.Features and Microsoft.CodeAnalysis.CSharp.Features

src/OmniSharp.MSBuild/ProjectFile/MetadataNames.cs, src/OmniSharp.MSBuild/ProjectFile/ProjectFileInfo.ProjectData.cs, src/OmniSharp.MSBuild/ProjectFile/ProjectFileInfo.cs, test-assets/test-projects/ProjectWithAnalyzersFromReference/Analyzer/Analyzer.csproj, test-assets/test-projects/ProjectWithAnalyzersFromReference/Analyzer/Class1.cs, test-assets/test-projects/ProjectWithAnalyzersFromReference/ConsumingProject/ConsumingProject.csproj, test-assets/test-projects/ProjectWithAnalyzersFromReference/ConsumingProject/Program.cs, test-assets/test-projects/ProjectWithAnalyzersFromReference/ProjectWithAnalyzersFromReference.sln, tests/OmniSharp.MSBuild.Tests/ProjectFileInfoTests.cs
<ProjectReference> elements can have metadata that specify what type of item to create, or that they shouldn't create items at all. The existing code that was processing references wasn't checking for this metadata, so you could end up with project references between projects that shouldn't be there.
The approach to take here is to never look at the <ProjectReference> items directly, rather only look at the ReferencePath items that are produced, and if we see metadata that indicates it came from a project, convert it to a project reference at that point.
=> Correctly handle <ProjectReferences> that don't produce references

src/OmniSharp.Stdio/Host.cs
At the moment an exception from an endpoint is only logged when debug level is enabled.
This leads to quite frustrating troubleshooting situations - when people experience errors on e.g. completion or code actions normally their log doesn't show any errors, until they enable debug level. On debug level, on the other hand, there is a ton of logs produced though, so often the error gets cropped anyway as it's tedious to copy the massive log stack.
This change adds automatic logging of unsuccessful (errored) endpoint responses at error level. 
This guarantees that any exceptions are automatically visible even at default logging level.
=> always log error responses with error level

build/Packages.props, tests/OmniSharp.Roslyn.CSharp.Tests/CodeActionsWithOptionsFacts.cs
This closely matches what will ship in VS 16.8 Preview 4
=> Bump Roslyn to 3.8.0-4.20503.2

src/OmniSharp.MSBuild/ProjectFile/ProjectFileInfoExtensions.cs, src/OmniSharp.MSBuild/ProjectManager.cs
Right now we just silently fail which isn't a good debugging experience. Ideally these would be shown in the error list but this is good enough when trying to track things down.
=> When an analyzer fails to load, log an error

tests/OmniSharp.Lsp.Tests/AbstractLanguageServerTestBase.cs
At the moment 12 LSP tests fail on a non-English machines with these types of errors (taken from my de-CH setup):
```
OmniSharp.Lsp.Tests.OmniSharpCodeActionHandlerFacts.Can_extract_method(roslynAnalyzersEnabled: False) [FAIL]
Assert.Contains() Failure
Not found: Extract Method
In value:  WhereSelectEnumerableIterator<CommandOrCodeAction, String> ["using System;", "System.Console", "Variable \"Console\" generieren -> Eigenschaft \"C"..., "Variable \"Console\" generieren -> Feld \"Class1.C"..., "Variable \"Console\" generieren -> Schreibgeschütz"..., ...]
```
The rest of the tests already resets the culture for the purpose of tests to `en-US`, this PR fixes it for LSP tests too.
=> fixed localization of LSP tests

src/OmniSharp.LanguageServerProtocol/Handlers/OmniSharpImplementationHandler.cs, src/OmniSharp.LanguageServerProtocol/LanguageServerHost.cs, src/OmniSharp.Roslyn.CSharp/Services/Navigation/FindImplementationsService.cs, tests/OmniSharp.Lsp.Tests/OmniSharpImplementationHandlerFacts.cs
This change adds the LSP handler for the `textDocument/implementation` feature (resolves #1853) and tests to go along with it. I tried the feature in Emacs using the `lsp-mode` package with success.
Writing the handler seemed straightforward. I based the new test class on ReferenceHandlerFacts.cs (I wasn't sure which naming convention to follow, i.e., using the `OmniSharp` prefix or not; based on the existing test files I chose to include the prefix).
The null check with early return in FindImplementationsService.cs was needed since a NullReferenceException would occur when checking `!symbol.IsAbstract` when a request was done without pointing at a symbol (the test `CannotFindImplementationsWithoutSymbol` checks this case).
=> Add support for textDocument/implementation in LSP mode

mono-packaging/run
This should fix an issue when there's a space in the path where OmniSharp is installed.
=> Quote config_file in Mono ENV Options

src/OmniSharp.Abstractions/Models/Request.cs, src/OmniSharp.Roslyn/BufferManager.cs, tests/OmniSharp.Roslyn.CSharp.Tests/BufferManagerFacts.cs
I rebased this on current master and added an additional setting to `ApplyChangesTogether` to default it to false when not present.
@JoeRobich can you describe the issues you were still seeing in vscode with this change applied? I tried reverting the revert of my vscode-side change and adding this flag (https://github.com/OmniSharp/omnisharp-vscode/pull/4088), and everything that I've tried since has seemed to work. Completion still triggers correctly, colorization appears to work, etc, but I'm not sure if I'm missing a test scenario you had? What I tried:
1. Wait for omnisharp to load
2. Rename a local used in multiple location/Use multiple cursors to type garbage in a bunch of locations
3. Verify that the buffer update had multiple updates in it, not one big update.
4. Tested …
=> Apply bulk changes

.pipelines/init.yml, CHANGELOG.md, README.md, azure-pipelines.yml, build.json
I saw 6.12.0 was listed for download as stable.
Also, noticed that the 6.12.0 Mono ships with a 16.8 MSBuild meaning we can revert the meaning of `omnisharp.useGlobalMono` when we take the next release. Verified that the 6.12 Mono's MSBuild handles loading the dotnet/sdk sdk.sln which is firmly .NET 5. =)
```patch
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
Located 2 MSBuild instance(s)
!            1: Mono 16.8.0 - "/Library/Frameworks/Mono.framework/Versions/6.12.0/lib/mono/msbuild/Current/bin"
2: StandAlone 16.8.0 - "/Users/joeyrobichaud/.vscode-insiders/extensions/ms-dotnettools.csharp-1.23.3/.omnisharp/1.37.1/omnisharp/.msbuild/Current/Bin"
```
=> Update included Mono to 6.12.0

src/OmniSharp.Roslyn.CSharp/Helpers/DiagnosticExtensions.cs, src/OmniSharp.Roslyn.CSharp/Services/Diagnostics/CodeCheckService.cs, src/OmniSharp.Roslyn.CSharp/Services/Refactoring/GetFixAllCodeActionService.cs, src/OmniSharp.Roslyn.CSharp/Services/Refactoring/RunFixAllCodeActionService.cs, src/OmniSharp.Roslyn.CSharp/Services/Refactoring/V2/BaseCodeActionService.cs, src/OmniSharp.Roslyn.CSharp/Services/Refactoring/V2/CachingCodeFixProviderForProjects.cs, src/OmniSharp.Roslyn.CSharp/Workers/Diagnostics/AnalyzerWorkQueue.cs, src/OmniSharp.Roslyn.CSharp/Workers/Diagnostics/CSharpDiagnosticWorker.cs, src/OmniSharp.Roslyn.CSharp/Workers/Diagnostics/CSharpDiagnosticWorkerWithAnalyzers.cs, src/OmniSharp.Roslyn.CSharp/Workers/Diagnostics/CsharpDiagnosticWorkerComposer.cs, src/OmniSharp.Roslyn.CSharp/Workers/Diagnostics/DocumentDiagnostics.cs, src/OmniSharp.Roslyn.CSharp/Workers/Diagnostics/ICsDiagnosticWorker.cs, tests/OmniSharp.Roslyn.CSharp.Tests/AnalyzerWorkerQueueFacts.cs
This should fix https://github.com/OmniSharp/omnisharp-roslyn/issues/1983, fix https://github.com/OmniSharp/omnisharp-roslyn/issues/1982, and fix https://github.com/OmniSharp/omnisharp-vscode/issues/4111. I reverted the diagnostic worker change, and introduced a separate codepath for FixAll to use when calculating updated diagnostics. For easier review I broke this into 2 changes:
1. Revert select files back to 73292abe. No manual changes are in this commit.
2. Make changes to keep code compiling, and add separate bypass methods for the fixall service to use when calculating updated diagnostics.
=> Targeted DiagnosticWorker Revert

src/OmniSharp.Host/MSBuild/Discovery/Providers/MonoInstanceProvider.cs
This commit https://github.com/OmniSharp/omnisharp-roslyn/commit/2bfebbcf59f8bd13b74b977629621ab084950863 contains a bug where the global Mono MSBuild version was always reported the same as the bundled MSBuild.
Running on global Mono 6.12, before the changes:
```
[info]: OmniSharp.Stdio.Host
Starting OmniSharp on MacOS 10.15.6 (x64)
[info]: OmniSharp.Services.DotNetCliService
DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
Located 2 MSBuild instance(s)
1: Mono 16.8.0 - "/Library/Frameworks/Mono.framework/Versions/6.12.0/lib/mono/msbuild/Current/bin"
2: StandAlone 16.8.0 - "/Users/filipw/.vscode/extensions/ms-dotnettools.csharp-1.23.4/.omnisharp/1.37.3/omnisharp/.msbuild/Current/Bin"
```
After the change:
```
[info]: OmniSharp.Stdio.Host
Starting OmniSharp on …
```
=> fixed global Mono MSBuild version reporting

src/OmniSharp.Script/ScriptProjectProvider.cs
This values were always being parsed but they were not being used. Here is an example of a .rsp file that I am using
```
/using:System
/using:System.Core
/using:Microsoft.CSharp
/using:System
/using:System.IO
/using:System.Collections.Generic
/using:System.Console
/using:System.Diagnostics
/using:System.Dynamic
/using:System.Linq
/using:System.Linq.Expressions
/using:System.Text
/using:System.Threading.Tasks
/loadPaths:C:\\Users\\byron\\Desktop\\scriptingIncludes
```
=> Omnisharp now uses libPaths and sourcePaths defined in custom .rsp file

src/OmniSharp.Script/ScriptProjectProvider.cs, tests/OmniSharp.Script.Tests/ScriptProjectProviderTests.cs, tests/OmniSharp.Script.Tests/WorkspaceInformationTests.cs
In the past lang version `Latest` used to resolve to `7.1` so in order to force C# 8 in scripting we enabled it explicitly.
Now this is no longer correct, so resetting back to `Latest` as Roslyn does it https://github.com/dotnet/roslyn/blob/version-3.2.0/src/Scripting/CSharp/CSharpScriptCompiler.cs#L14
Additionally added a test so if `Latest` no longer means `9`, the test will break and let us decide how to proceed.
=> C# scripting should use language version "latest" by default

README.md
Unfortunately the link we use in the docs to list all releases is not suitable anymore - Azure Blob Storage doesn't allow listing more than 5000 blobs and we have a lot more files there already.
Updated the readme with instructions on how to use github releases to download builds and how to use filtering mechanism when querying the Blob Storage.
fixes #1996
=> updated release documentation

src/OmniSharp.Abstractions/Plugins/Plugin.cs, src/OmniSharp.Abstractions/Services/IProjectSystem.cs, src/OmniSharp.Cake/CakeProjectSystem.cs, src/OmniSharp.LanguageServerProtocol/Handlers/OmniSharpTextDocumentSyncHandler.cs, src/OmniSharp.LanguageServerProtocol/LanguageServerHost.cs, src/OmniSharp.MSBuild/ProjectSystem.cs, src/OmniSharp.Script/ScriptProjectSystem.cs, tests/OmniSharp.Http.Tests/EndpointMiddlewareFacts.cs, tests/OmniSharp.Lsp.Tests/AbstractLanguageServerTestBase.cs, tests/OmniSharp.Lsp.Tests/OmniSharpCodeActionHandlerFacts.cs, tests/OmniSharp.Stdio.Tests/EndpointHandlerFacts.cs
Some background:
https://github.com/coc-extensions/coc-omnisharp/issues/33
https://github.com/coc-extensions/coc-omnisharp/issues/35
https://github.com/OmniSharp/omnisharp-roslyn/issues/1742
https://github.com/OmniSharp/omnisharp-roslyn/issues/1515
https://github.com/OmniSharp/omnisharp-roslyn/issues/1083
--------
In short, there's race condition between (workspace initialization + project reference adding) and (client requests coming in at a random point of time).
This PR blocks incoming LSP requests until the initial project system processing is completed. Should help us to get rid of a bunch of issues.
=> Lsp init fix

src/OmniSharp.LanguageServerProtocol/LanguageServerHost.cs
I was looking forward to a working lsp mode but when I come back to check this, even the logging functionality is toast...
`¯\_(ツ)_/¯`
=> fix lsp mode logging

.editorconfig, build/Packages.props, src/OmniSharp.Host/MSBuild/Discovery/MSBuildLocator.cs, src/OmniSharp.LanguageServerProtocol/Handlers/OmniSharpCodeActionHandler.cs, src/OmniSharp.LanguageServerProtocol/LanguageProtocolInteropHandler.cs, src/OmniSharp.LanguageServerProtocol/LanguageServerHost.cs
No breaking changes (other than the analyzer that is getting chained from NerdBank).
=> Upgraded lsp to 0.18.3

src/OmniSharp.Cake/Services/CakeScriptService.cs
- Log path used for service.
- If returned script is null or empty, return null to avoid updating any buffer.
=> Improve handling with Cake Script Service.

build/Packages.props, tools/packages.config
We can get off some of the pre packages (at least for the time being) as everything was published as part of .NET 5.0.
Updated:
- Roslyn to 3.8.0
- MSBuild to 16.8.0
- DotNetHostResolver to 5.0.0
=> Roslyn and MSBuild updates to latest stable

tools/packages.config
A follow up to https://github.com/OmniSharp/omnisharp-roslyn/pull/2015. Updates other packages to match the .NET 5 GA.
=> Update Tools packages to match .NET 5.0.100 SDK

src/OmniSharp.MSBuild/ProjectFile/ProjectFileInfoExtensions.cs, src/OmniSharp.MSBuild/ProjectManager.cs, src/OmniSharp.Roslyn.CSharp/Workers/Diagnostics/CSharpDiagnosticWorkerWithAnalyzers.cs, src/OmniSharp.Roslyn/OmniSharpWorkspace.cs, tests/OmniSharp.MSBuild.Tests/ProjectWithAnalyzersTests.cs
1. at the moment we set brand new `CompilationOptions` based on the csproj file when a project update is triggered (e.g. rebuild, change in csproj). This causes us to lose the editorconfig state because it is kept in `SyntaxTreeOptionsProvider` which gets reset then. The PR ensures the new compilation options are created only when necessary, and also derived from the previous ones. 
- fixes https://github.com/OmniSharp/omnisharp-vscode/issues/4184  
- fixes https://github.com/OmniSharp/omnisharp-vscode/issues/4165
- fixes https://github.com/OmniSharp/omnisharp-roslyn/issues/1955
2. when editorconfig file changes, even though we watch for changes, there is currently no event raised that would trigger a re-analysis. This PR introduces new targeted handling of editorconfig - if an …
=> Editorconfig improvements - do not lose state, trigger re-analysis on change

src/OmniSharp.Roslyn.CSharp/DocumentationComments/DocumentationCommentSnippetService.cs, src/OmniSharp.Roslyn.CSharp/Workers/Formatting/FormattingWorker.cs, tests/OmniSharp.Roslyn.CSharp.Tests/FormatAfterKeystrokeTests.cs, tests/TestUtility/AssertUtils.cs
IDocumentationCommentSnippetService was recently moved down to the Features layer, which means omnisharp can now take advantage of it and generate documentation comment snippets on typing. There are a couple of caveats:
1. LSP's "/onTypingFormat" endpoint has no support for setting the cursor location after format, which means that the cursor ends up after the inserted block. This is fine for newlines inside doc comments, but awkward for the initial expansion. However, unless we want to add special support with a custom endpoint, we can't get around this (the custom endpoint is how Roslyn does it).
2. The service itself is still internal, so I had to add a few new reflection points.
Server-side of https://github.com/OmniSharp/omnisharp-vscode/issues/8. It also needs a vscode change, but …
=> Add documentation comment creation to the FormatAfterKeystrokeService

src/OmniSharp.Abstractions/Models/v1/GotoDefinition/GotoDefinitionRequest.cs, src/OmniSharp.Roslyn.CSharp/Services/ExternalSourceServiceFactory.cs
The 2s timeout is quite aggressive and it was reported already a few times that it doesn't complete in time especially on large metadata files.
The client can still supply its own timeout, it's just the default is now 10s (VS Code Extension doesn't set it so it will automatically benefit from the higher timeout). 
Fixes https://github.com/OmniSharp/omnisharp-vscode/issues/4260
=> raise default GotoDefinitionRequest timeout from 2s to 10s

src/OmniSharp.Host/MSBuild/Discovery/MSBuildLocator.cs, src/OmniSharp.MSBuild/Options/MSBuildOptions.cs, tests/OmniSharp.MSBuild.Tests/MSBuildSelectionTests.cs
At the moment there is no way to force bundled MSBuild on Windows.
On Linux/Mac it is possible in VS Code using `omnisharp.useGlobalMono: never` but it is a client specific option, not a universal server option for all clients.
What this PR introduces is the following setting to `omnisharp.json`
```
{
"msbuild": {
"useBundledOnly": true
}
}
```
The effect is:
- on Windows, no Visual Studio / MSBuild Tools MSBuild is discovered anymore - only the bundled MSBuild is used
- on Linux/Mac, regardless whether running on global or local Mono - only the bundled MSBuild is used
This should unblock scenarios when:
- user has outdated Visual Studio
- user wants to run on global Mono but using the bundled MSBuild
Both of those have been repeated in multiple issues.
=> added `msbuild:UseBundledOnly` option to force the usage of bundled MSBuild

tests/TestUtility/TestServiceProvider.cs
As noted in https://github.com/OmniSharp/omnisharp-roslyn/pull/2034#issuecomment-745548208, when running tests we were always using the 5.0.100 sdk path. This change allows the LegacySdkResolver to locate the sdk that matches the global.json pinned version.
Instead of seeing this during testing
```
Loading project: /tmp/hy317v4y.d81/NetCore21Project/NetCore21Project.csproj
[dbug]: OmniSharp.MSBuild.SdksPathResolver
Set MSBuildSDKsPath environment variable to: /home/vsts/work/1/s/.dotnet/sdk/5.0.100/Sdks
```
You see this
```
Loading project: /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/9h7u5eac.5fx/NetCore21Project/NetCore21Project.csproj
[dbug]: OmniSharp.MSBuild.SdksPathResolver
Set MSBuildSDKsPath environment variable to: /Users/runner/work/1/s/.dotnet/sdk/2.1.811/Sdks
```
=> Allow LegacySDKResolver to find SDK path in tests

src/OmniSharp.Roslyn.CSharp/Services/SemanticHighlight/SemanticHighlightService.cs, tests/OmniSharp.Roslyn.CSharp.Tests/SemanticHighlightFacts.cs
Fixes https://github.com/OmniSharp/omnisharp-roslyn/issues/2048.
=> Handle records in syntax highlighting

src/OmniSharp.Roslyn.CSharp/Workers/Formatting/FormattingWorker.cs
Roslyn APIs were not intended to handle this case and doing so can cause very odd behavior, such as extraneous newlines being added for malformed code and/or automatic indentation being removed, making for a frustrating experience. Superscedes https://github.com/OmniSharp/omnisharp-roslyn/pull/2051.
=> Remove format on newline

src/OmniSharp.Roslyn.CSharp/DocumentationComments/DocumentationCommentSnippetService.cs
currently the compiler reports 15 errors
```
/Users/filipw/dev/omnisharp-roslyn/src/OmniSharp.Roslyn.CSharp/DocumentationComments/DocumentationCommentSnippetService.cs(45,64): error CS8602: Dereferenzierung eines möglichen Nullverweises. [/Users/filipw/dev/omnisharp-roslyn/src/OmniSharp.Roslyn.CSharp/OmniSharp.Roslyn.CSharp.csproj]
/Users/filipw/dev/omnisharp-roslyn/src/OmniSharp.Roslyn.CSharp/DocumentationComments/DocumentationCommentSnippetService.cs(45,64): error CS8601: Mögliche Nullverweiszuweisung. [/Users/filipw/dev/omnisharp-roslyn/src/OmniSharp.Roslyn.CSharp/OmniSharp.Roslyn.CSharp.csproj]
/Users/filipw/dev/omnisharp-roslyn/src/OmniSharp.Roslyn.CSharp/DocumentationComments/DocumentationCommentSnippetService.cs(46,60): error CS8601: Mögliche Nullverweiszuweisung. …
```
=> address nullability errors in DocumentationCommentSnippetService

src/OmniSharp.Abstractions/Models/v2/Range.cs, src/OmniSharp.Roslyn.CSharp/Services/SemanticHighlight/SemanticHighlightService.cs, tests/OmniSharp.Roslyn.CSharp.Tests/SemanticHighlightFacts.cs
When the client submits negative range we hit an argument exception in Roslyn (https://github.com/OmniSharp/omnisharp-vscode/issues/4317).
This is not an optimal experience. 
This PR adds basic validation for the range. The linked VS Code bug should be separately investigated but a validation on the server is needed regardless - similarly to what we do in other endpoints.
=> validation for highlighting range

src/OmniSharp.Roslyn.CSharp/Services/Completion/CompletionService.cs, tests/OmniSharp.Roslyn.CSharp.Tests/CompletionFacts.cs
We used to do it this way until the switch to CompletionService. This PR restores the old mapping of parameter to variable.
Fixes https://github.com/OmniSharp/omnisharp-roslyn/issues/2060
Fixes https://github.com/OmniSharp/omnisharp-vscode/issues/4314
=> use "variable" kind for parameter completion

src/OmniSharp.Host/WorkspaceInitializer.cs
I've been getting this error intermittently:
https://github.com/OmniSharp/omnisharp-roslyn/blob/8f3b6ea9915c4e692ca324a1e2e58e394a6cac75/src/OmniSharp.MSBuild/ProjectManager.cs#L375
I tracked it down to a race between `TryApplyChanges` calls.
Adding the project happens on a worker thread, and is queued on the main thread inside:
https://github.com/OmniSharp/omnisharp-roslyn/blob/8f3b6ea9915c4e692ca324a1e2e58e394a6cac75/src/OmniSharp.Host/WorkspaceInitializer.cs#L43
I believe `AddProject` can be called on a worker thread any time after this.
The other call is on the main thread via:
https://github.com/OmniSharp/omnisharp-roslyn/blob/8f3b6ea9915c4e692ca324a1e2e58e394a6cac75/src/OmniSharp.Host/WorkspaceInitializer.cs#L59
https://github.com/OmniSharp/omnisharp-roslyn/blob/8f3b6ea9915c4e692ca32 …
=> delay project system init to avoid solution update race

src/OmniSharp.Stdio/Host.cs
In https://github.com/OmniSharp/omnisharp-roslyn/pull/1963 we added a change that always logged responses at error level when an exception occurred. 
This PR extends this further, and in case of exceptions, when the server is running at log level higher than Debug, additionally logs corresponding request with Warning too.
This will improve the "out of the box" troubleshooting experience.
=> log request when response fails

src/OmniSharp.Abstractions/Models/v1/FixAll/RunFixAllRequest.cs
This is now equal to the go to metadata timeout which is also 10 seconds. Three seconds is too short especially for solution wide fixes.
That said, it would be good for editors to have their own setting.
=> changed the default RunFixAllRequest timeout to 10 seconds

src/OmniSharp.MSBuild/Logging/ErrorMessages.cs, src/OmniSharp.MSBuild/Logging/MSBuildDiagnostic.cs, src/OmniSharp.MSBuild/Logging/MSBuildLogger.cs, tests/OmniSharp.MSBuild.Tests/MSBuildDiagnosticTests.cs, tests/OmniSharp.MSBuild.Tests/OmniSharp.MSBuild.Tests.csproj
fixes https://github.com/OmniSharp/omnisharp-roslyn/issues/2029 
Instead of printing the default MSBuild message for MSB3644 which is Windows specific and has been very confusing to the users:
> The reference assemblies for {0} were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks
we now change it into a more relevant OmniSharp message on Unix:
> This project targets .NET version that requires reference assemblies that do not ship with OmniSharp out of the box (e.g. .NET Framework). The most common solution is to make sure Mono is installed on your machine (https://mono-project.com/download/) and that OmniSharp is …
=> use an OmniSharp specific message for MSB3644

src/OmniSharp.Roslyn.CSharp/Services/Navigation/FindUsagesService.cs, tests/OmniSharp.Roslyn.CSharp.Tests/FindReferencesFacts.cs
At the moment, on finding references, when the requested symbol is null, we still call Roslyn reference finder API which then results in an ugly unhandled exception.
```
System.InvalidOperationException: Unexpected null\r\n at Roslyn.Utilities.Contract.Fail(String message)\r\n at Microsoft.CodeAnalysis.FindSymbols.FindReferencesSearchEngine.MapToAppropriateSymbol(ISymbol symbol)\r\n at Microsoft.CodeAnalysis.FindSymbols.FindReferencesSearchEngine.d__20.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n at Microsoft.CodeAnalysis.FindSymbols.FindReferencesSearchEngine.d__19.MoveN …
```
=> Do not call FindReferencesAsync for null symbol

build.cake, build/Packages.props, src/OmniSharp.LanguageServerProtocol/LanguageServerHost.cs
* Upgraded extension dependencies to 3.1.
* Enabled console logging over stderr instead of stdout to ensure console logs don't cause issues for lsp functionality
+semver:minor
=> Updated to latest lsp version.  

.github/workflows/tests.yml, azure-pipelines.yml
This is where we see the most failures is with the tests on ADO.
The release pipeline will still run through ADO for the time being (on master and tags) but this should speed up builds a bit I hope.
=> Removed Azure DevOps test runs

src/OmniSharp.LanguageServerProtocol/Handlers/OmniSharpCompletionHandler.cs
I noticed this when working on the .NET 5 branch. It only gets reported when targeting .NET 5
=> fixed CS8605 "Unboxing possibly null value"

build/Packages.props, src/OmniSharp.Roslyn.CSharp/Services/Decompilation/AssemblyResolver.cs, tests/OmniSharp.Roslyn.CSharp.Tests/GoToDefinitionFacts.cs
This gives us, among other things, support for
- C# 9.0 records
- C# 9.0 with expressions
- C# 9.0 primary constructors
It is a preview release, but then, most of our dependencies are preview already anyway 🙂
=> updated to IL Spy 7.0.0.6372

src/OmniSharp.MSBuild/ProjectSystem.cs, tests/OmniSharp.MSBuild.Tests/WorkspaceInformationTests.cs
In https://github.com/OmniSharp/omnisharp-vscode/pull/4481 the solution file's name is reported in the project selector because we are settings the ProjectSystem _solutionName to be the parsed solution path from the solution filter.
This ensures the solution filter path is reported in Workspace Updated events.
=> Report back the solution filter name in workspace updated event

OmniSharp.sln, src/OmniSharp.Benchmarks/.gitignore, src/OmniSharp.Benchmarks/ImportCompletionBenchmarks.cs, src/OmniSharp.Benchmarks/OmniSharp.Benchmarks.csproj, src/OmniSharp.Benchmarks/OverrideCompletionBenchmarks.cs, src/OmniSharp.Benchmarks/Program.cs, src/OmniSharp.LanguageServerProtocol/Handlers/OmniSharpCompletionHandler.cs, src/OmniSharp.Roslyn.CSharp/Services/Completion/CompletionService.cs, src/OmniSharp.Shared/Utilities/ImmutableArrayExtensions.cs, tests/OmniSharp.Cake.Tests/CompletionFacts.cs, tests/OmniSharp.Lsp.Tests/OmnisharpCompletionHandlerFacts.cs, tests/OmniSharp.Roslyn.CSharp.Tests/CompletionFacts.cs, tests/TestUtility/Logging/TestLogger.cs
Recently, Roslyn undeprecated the CompletionChange.TextChanges API. This API gives changes in a significantly simpler manner for us to deal with, as it splits up things like imports and the actual main change element, so we can remove a whole bunch of code dedicated to finding the changed elements and mapping original source locations to the new document. The new pattern is much simpler: except for import completion, we always resolve the change up front. For most providers, this is an extremely quick call, as most providers just return the label, and for the ones that don't we can't do much about it anyway. We can then loop through the individual changes, putting changes that are not touching the current cursor location into AdditionalTextChanges. This shrinks the completion payload …
=> Rework completion resolution

src/OmniSharp.MSBuild/ProjectFile/ProjectFileInfo.ProjectData.cs, src/OmniSharp.MSBuild/ProjectFile/ProjectFileInfo.cs, src/OmniSharp.MSBuild/ProjectFile/ProjectFileInfoExtensions.cs, src/OmniSharp.MSBuild/ProjectFile/PropertyNames.cs, test-assets/test-projects/HelloWorld/HelloWorld.csproj, tests/OmniSharp.MSBuild.Tests/ProjectFileInfoTests.cs
`Platform` property of the compilation options should be [based on](https://github.com/dotnet/roslyn/issues/29369#issuecomment-414354632) the `PlatformTarget` MSBuild property.
=> Correctly set compilation platform of the project

src/OmniSharp.Host/ConfigurationBuilder.cs, src/OmniSharp.Host/ConfigurationResult.cs, src/OmniSharp.Http/Startup.cs, src/OmniSharp.LanguageServerProtocol/LanguageServerHost.cs, src/OmniSharp.Stdio.Driver/Program.cs, tests/OmniSharp.Tests/ConfigurationBuilderFacts.cs
At the moment when bootstrapping configuration, if anything invalid is found (e.g. JSON structure is bad) we have an unhandled exception and failure to start.
Since the config is really optional I think it is better to swallow the exception, log an error and start with default config. This has been source of several issues already (got closed after the user fixed the config on their side).
since when the config is bootstrapped, the DI container is not yet initialized, logging of the possible error is deferred until the logger is available.
=> Do not crash on startup when configuration is invalid

build/Packages.props, tests/OmniSharp.Roslyn.CSharp.Tests/GoToDefinitionFacts.cs
IL Spy 7 was released this week - since we are on a preview, it makes sense for us to update to it as well.
=> Updated IL Spy to 7.0.0 stable

src/OmniSharp.Roslyn.CSharp/Services/Structure/BlockStructureService.cs, src/OmniSharp.Roslyn.CSharp/Services/Structure/CodeStructureService.cs, tests/OmniSharp.Roslyn.CSharp.Tests/BlockStructureFacts.cs, tests/OmniSharp.Roslyn.CSharp.Tests/CodeStructureFacts.cs
We have a convention where we don't return `null` from services but an empty response instead - e.g. https://github.com/OmniSharp/omnisharp-roslyn/blob/master/src/OmniSharp.Roslyn.CSharp/Services/Navigation/FindSymbolsService.cs#L28 or https://github.com/OmniSharp/omnisharp-roslyn/blob/master/src/OmniSharp.Roslyn.CSharp/Services/Completion/CompletionService.cs#L107
This simplifies client integration. Adapted `BlockStructureService` and `CodeStructureService` accordingly.
=> Do not return null responses from BlockStructureService and CodeStructureService

src/OmniSharp.Host/Services/AnalyzerAssemblyLoader.cs
This is a port of https://github.com/dotnet/roslyn/pull/53166. There's a bigger question here about how to reuse this code better, but this caused a bunch of confusion while debugging an issue.
=> Only subscribe to AppDomain.AssemblyResolve once

src/OmniSharp.Abstractions/Models/v1/GotoDefinition/GotoDefinitionResponse.cs, src/OmniSharp.Abstractions/Models/v1/SourceGeneratedFile/SourceGeneratedFileClosedRequest.cs, src/OmniSharp.Abstractions/Models/v1/SourceGeneratedFile/SourceGeneratedFileClosedResponse.cs, src/OmniSharp.Abstractions/Models/v1/SourceGeneratedFile/SourceGeneratedFileInfo.cs, src/OmniSharp.Abstractions/Models/v1/SourceGeneratedFile/SourceGeneratedFileRequest.cs, src/OmniSharp.Abstractions/Models/v1/SourceGeneratedFile/SourceGeneratedFileResponse.cs, src/OmniSharp.Abstractions/Models/v1/SourceGeneratedFile/UpdateSourceGeneratedFileRequest.cs, src/OmniSharp.Abstractions/Models/v1/SourceGeneratedFile/UpdateSourceGeneratedFileResponse.cs, src/OmniSharp.Abstractions/Models/v2/GotoDefinition/GotoDefinitionResponse.cs, src/OmniSharp.Abstractions/OmniSharpEndpoints.cs, src/OmniSharp.Roslyn.CSharp/Services/Navigation/GoToDefinitionHelpers.cs, src/OmniSharp.Roslyn.CSharp/Services/Navigation/GotoDefinitionService.cs, src/OmniSharp.Roslyn.CSharp/Services/Navigation/GotoDefinitionServiceV2.cs, src/OmniSharp.Roslyn.CSharp/Services/Navigation/SourceGeneratedFileService.cs, tests/OmniSharp.Roslyn.CSharp.Tests/AbstractGoToDefinitionFacts.cs, tests/OmniSharp.Roslyn.CSharp.Tests/GoToDefinitionFacts.cs, tests/OmniSharp.Roslyn.CSharp.Tests/GoToDefinitionV2Facts.cs, tests/OmniSharp.Roslyn.CSharp.Tests/SourceGeneratorFacts.cs, tests/OmniSharp.Roslyn.CSharp.Tests/TestSourceGenerator.cs
This adds a new response element to gotodefinition responses: SourceGeneratedFileInfo. This is similar to MetadataSource, except that unlike MetadataSource it's not tracked on a type/project basis, but rather as a document/project basis. Retrieving info about a source generated file can be done through the SourceGeneratedFileService endpoints:
* SourceGeneratedFileInfo - Gets the file content of a source generated file.
* UpdateSourceGeneratedFileInfo - Gets the updated content of a source generated file, if it has changed since the last time information was returned.
* SourceGeneratedFileClosed - Sent to the server to inform it that the editor has closed the generated file and it can stop tracking Document version info for that file.
Currently, the only way to get the info needed to open …
=> Add support for GoToDefinition on source-generated files

src/OmniSharp.MSBuild/Logging/MSBuildDiagnostic.cs
Resolves https://github.com/OmniSharp/omnisharp-roslyn/issues/2171
Looking at the deserialize code for BuildErrorEventArgs and it appears that `null` is a valid value for the `Code` property - https://github.com/dotnet/msbuild/blob/206d7ae3e6187e2d214041bf79719600ec197c56/src/Framework/BuildErrorEventArgs.cs#L300
=> Defend against null value in BuildErrorEventArgs

src/OmniSharp.Stdio/Host.cs
If we log responses, we now do it with duration information.
For example:
```
************  Response (50.2536ms) ************ 
{
"Request_seq": 6,
"Command": "/codecheck",
"Running": true,
"Success": true,
"Message": null,
"Body": {
"QuickFixes": []
},
"Seq": 416,
"Type": "response"
}
```
or  
```
************  Response (4.0503ms) ************ 
{
"Request_seq": 125,
"Command": "/completion/resolve",
"Running": true,
"Success": true,
"Message": null,
"Body": {
"Item": {
"Label": "Console",
"Kind": 7,
"Tags": null,
"Detail": "",
"Documentation": "```csharp\nclass System.Console\n```\n\nRepresents the standard input, output, and error streams for console applications\\. This class cannot be inherited\\.",
"Preselect": false,
"SortText": null,
"FilterText": null,
"InsertTextFormat": 1, …
```
=> Include timing info in logged responses

src/OmniSharp.Roslyn.CSharp/Workers/Diagnostics/CSharpDiagnosticWorkerWithAnalyzers.cs
Fixes: #1711
DiagnosticSuppressor is a subclass of DiagnosticAnalyzer, so its instances are already imported from assemblies and excuted. However, they just mark diagnostics as suppressed, not exclude them directly. So the suppressors will take effect just by excluding suppressed diagnostics.
I tested this with VSCode and [Microsoft's Unity analyzers](https://github.com/microsoft/Microsoft.Unity.Analyzers/).
=> Exclude diagnostics suppressed by DiagnosticSuppressor

build.cake
Appends the following section to the OmniSharp.exe.config during publishing.
```xml
</assemblyBinding>
<assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
<dependentAssembly>
<assemblyIdentity name="OmniSharp.Roslyn" publicKeyToken="7e5bf7b3b470b509" culture="neutral" />
<bindingRedirect oldVersion="0.0.0.0-1.37.0.0" newVersion="1.37.0.0" />
</dependentAssembly>
<dependentAssembly>
<assemblyIdentity name="OmniSharp.Script" publicKeyToken="7e5bf7b3b470b509" culture="neutral" />
<bindingRedirect oldVersion="0.0.0.0-1.37.0.0" newVersion="1.37.0.0" />
</dependentAssembly>
<dependentAssembly>
<assemblyIdentity name="OmniSharp.Roslyn.CSharp" publicKeyToken="7e5bf7b3b470b509" culture="neutral" />
<bindingRedirect oldVersion="0.0.0.0-1.37.0.0" newVersion="1.37.0.0" />
</dependentAssembly> …
```
=> Generate binary redirects for OmniSharp libraries

src/OmniSharp.Roslyn.CSharp/Services/ExternalFeaturesHostServicesProvider.cs
Fixes https://github.com/OmniSharp/omnisharp-roslyn/issues/2201
=> log a warning when external features path has no assemblies

src/OmniSharp.MSBuild/ProjectManager.cs
In particular, the project loader exception was swallowed because it was passed in as argument.
=> Improved logging in project manager

src/OmniSharp.LanguageServerProtocol/Handlers/OmniSharpSignatureHelpHandler.cs
Fixes signature help UI in https://github.com/OmniSharp/omnisharp-roslyn/issues/2071 (sublime text) and https://github.com/ray-x/lsp_signature.nvim/issues/50 (neovim).
The VS Code plugin also currently ignores the incorrect signature help trigger characters delivered by this plugin and manually overrides them to `,` and `(`.
Fixing this will give a better out-of-the-box experience to all language-server supporting editors.
You can see here in the vs code's plugin where it's manually setting its own trigger characters:
https://github.com/OmniSharp/omnisharp-vscode/blob/master/src/omnisharp/extension.ts#L96
=> Fix incorrect signature help trigger characters

build.cake, tools/packages.config
Attempt to fix test failure in https://github.com/OmniSharp/omnisharp-roslyn/pull/2217
=> Update versions to match .NET SDK 6 RC1 (fix test)

src/OmniSharp.Roslyn.CSharp/Services/Structure/CodeStructureService.cs, tests/OmniSharp.Roslyn.CSharp.Tests/CodeStructureFacts.cs
Resolves https://github.com/OmniSharp/omnisharp-roslyn/issues/2225
=> Update CodeStructureService with FileScoped Namespace support

src/OmniSharp.Roslyn.CSharp/Services/SemanticHighlight/SemanticHighlightService.cs, tests/OmniSharp.Roslyn.CSharp.Tests/SemanticHighlightFacts.cs
Additionally, to avoid the key not found exceptions, which happened twice now, we will default to semantic highlighting classification as text in case a given span's classification cannot be mapped.
Fixes #2228
=> handle RecordStructName in semantic highlighting classification

tools/packages.config
Looks like RC1 included `6.0.0-preview.4.230` not `6.0.0-preview.4.220` of Nuget dependencies
https://github.com/dotnet/sdk/blob/v6.0.100-rc.1.21458.71/eng/Versions.props#L57
=> Nuget 6.0.0-preview.4.220 -> 6.0.0-preview.4.230

BUILD.md, README.md, build.cake, build.json, mono-packaging/copy-mono.sh, scripts/common.cake, tests/app.config, tools/packages.config
I have built this locally and confirmed the language server runs as expected. Without Azure Pipelines support for Linux Arm64 images there is no CI for this build.
=> Produce an Arm64 build for Linux

build.cake
The Linux arm64 build was not usable because it was built on a x64 vm and was shipping the x64 hostfxr library.
=> Ensure each published platform uses matching hostfxr library

src/OmniSharp.Roslyn.CSharp/Services/Refactoring/RunFixAllCodeActionService.cs, src/OmniSharp.Roslyn.CSharp/Workers/Diagnostics/AnalyzerOptionExtensions.cs, src/OmniSharp.Roslyn.CSharp/Workers/Diagnostics/CSharpDiagnosticWorker.cs, src/OmniSharp.Roslyn.CSharp/Workers/Diagnostics/CSharpDiagnosticWorkerWithAnalyzers.cs, src/OmniSharp.Roslyn.CSharp/Workers/Diagnostics/CsharpDiagnosticWorkerComposer.cs, src/OmniSharp.Roslyn.CSharp/Workers/Diagnostics/DiagnosticAnalyzerExtensions.cs, src/OmniSharp.Roslyn.CSharp/Workers/Diagnostics/ICsDiagnosticWorker.cs, src/OmniSharp.Roslyn/OmniSharpWorkspace.cs, tests/OmniSharp.Roslyn.CSharp.Tests/CSharpDiagnosticWorkerWithAnalyzersFacts.cs, tests/OmniSharp.Roslyn.CSharp.Tests/SourceGeneratorFacts.cs, tests/TestUtility/TestHelpers.cs
This change will filter the analyzers which are run by whether they can produce a meaningful diagnostic. If a diagnostic has been configured in the .editorconfig with a severity of `none`, then it should be filtered out.
Resolves https://github.com/OmniSharp/omnisharp-vscode/issues/4718
=> Check diagnostic analyzer's configured severity before running it

src/OmniSharp.MSBuild/ProjectSystem.cs
At the moment when no MSBuild was found the server would hard crash with a null reference exception.
This way we allow it continue further - it would still not work, but at least moves into a more appropriate failure state, where the log shows that 0 MSBuild instances are found, and then some errors about missing MSBuild dlls are written.
=> [vnext] do not throw null reference when no MSBuild was registered

tests/TestUtility/TestHelpers.cs
It was imported by mistake and it fails the .NET 6 build https://github.com/OmniSharp/omnisharp-roslyn/pull/2284/files#diff-c95ff663a95d485d35049bd84e197fd823e275377d4be94876327e3249088f4aR8
=> Removed bogus using directive

build.cake
This is OK since the net6 builds will use the MSBuild included in the SDK.
=> Do not include msbuild folder in net6 packages

src/OmniSharp.Host/HostHelpers.cs, src/OmniSharp.Host/MSBuild/Discovery/Extensions.cs, src/OmniSharp.Host/MSBuild/Discovery/MSBuildNotFoundException.cs, src/OmniSharp.Host/MSBuild/Discovery/Providers/MicrosoftBuildLocatorInstanceProvider.cs
Since we fail when loading SDKs with mismatched NuGet.Framework, we can limit our SDK discovery to a known good SDK version.
=> Require a known good version of .NET SDK be installed.

src/OmniSharp.Abstractions/Models/v2/SemanticHighlight/SemanticHighlightRequest.cs, src/OmniSharp.Roslyn.CSharp/Services/SemanticHighlight/SemanticHighlightService.cs, tests/OmniSharp.Roslyn.CSharp.Tests/SemanticHighlightFacts.cs
To fix diff highlighting in the VSCode C# extension, we need to pass along alternate versions of the document we are highlighting. Request has a `Buffer` property but populating that will invoke the updateBufferHandler when the request is handled (as alluded to in https://github.com/OmniSharp/omnisharp-vscode/pull/4915#discussion_r760604439).
https://github.com/OmniSharp/omnisharp-roslyn/blob/52f9ed3efbd2aa85afd3feb1433462474ad30fcd/src/OmniSharp.Host/Endpoint/EndpointHandler.cs#L109-L116
This PR adds an optional `VersionedText` property to the highlight request which can carry the alternate version of the document contents. The highlight service will then swap the document text for the duration of the request when it is populated.
=> Allow for alternate versions of documents to be semantically highlighted

build.cake, scripts/common.cake, src/OmniSharp.Abstractions/SemanticVersion.cs, src/OmniSharp.Abstractions/Services/DotNetInfo.cs, src/OmniSharp.Abstractions/Services/IDotNetCliService.cs, src/OmniSharp.DotNetTest/TestManager.cs, src/OmniSharp.DotNetTest/VSTestManager.cs, src/OmniSharp.Host/MSBuild/Discovery/Extensions.cs, src/OmniSharp.Host/MSBuild/Discovery/MSBuildInstanceProvider.cs, src/OmniSharp.Host/MSBuild/Discovery/Providers/MicrosoftBuildLocatorInstanceProvider.cs, src/OmniSharp.Host/MSBuild/Discovery/Providers/StandAloneInstanceProvider.cs, src/OmniSharp.Host/Services/DotNetCliService.cs, src/OmniSharp.MSBuild/Notification/ProjectLoadedEventArgs.cs, tests/OmniSharp.Tests/DotNetCliServiceFacts.cs, tests/OmniSharp.Tests/SemanticVersionFacts.cs
By not shipping NuGet libraries ourselves in our net6 packages, we will load the NuGet libraries shipped with the SDK registered by the MSBuildLocator. I did need to add a SemanticVersion implementation in order to remove our use of NuGet.Versioning.
To test you can install 6.0.2xx version of the .NET SDK from [dotnet/installers](https://github.com/dotnet/installer).
=> Allow net6 build of O# to load newer .NET SDKs

src/OmniSharp.Roslyn.CSharp/Services/Completion/CompletionListBuilder_Sync.cs, tests/OmniSharp.Roslyn.CSharp.Tests/CompletionFacts.cs
LSP filters expect that the range of the main text edit is going to start on the same line as the cursor. However, when trailing whitespace preceeds the override marker, Roslyn will return a single text edit for the whole range that trims that whitespace. This confuses the vscode intellisense engine, which then unhelpfully displays no completions with no user feedback that this filtering is happening. To avoid this, we now detect when this case occurs, and split up the change into non-overlapping edits from before the current line. Fixes https://github.com/OmniSharp/omnisharp-vscode/issues/4600.
=> Handle completions with trailing whitespace on previous lines

src/OmniSharp.MSBuild/ProjectManager.cs
I often hit 'Failed to add project to workspace: <project-file>' error in OmniSharp log when opening one of internal projects. I only see this issue on Linux (Ubuntu 20.04) and not on Windows. I always have omnisharp.enableMsBuildLoadProjectsOnDemand set to "true". The problem occurs often but not all the time.
In both success and failure cases I see the following sequence of events (shortened to highlight only important parts):
```
[info]: OmniSharp.MSBuild.ProjectManager
Queue project update for '/home/<path_to_project>/ProjectName.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
Loading project: /home/<path_to_project>/ProjectName.csproj
[dbug]: OmniSharp.Stdio.Host
************ Request ************
{
"Type": "request",
"Seq": 7,
"Command": "/filesChanged",
"Arguments": [
{
"FileName": …
```
=> Add MSBuild project to solution and apply the change to Roslyn workspace as a unit

src/OmniSharp.Roslyn.CSharp/Workers/Diagnostics/CSharpDiagnosticWorker.cs
`List<T>` is not thread safe, use `ImmutableList` and `ImmutableInterlocked` like `CSharpDiagnosticWorkerWithAnalyzers` does.
I have reproduced the issue and tested the fix and it seems to work.
Fixes OmniSharp/omnisharp-vscode#5017
=> Fix concurrency issue in CSharpDiagnosticWorker

src/OmniSharp.Roslyn.CSharp/Workers/Diagnostics/CSharpDiagnosticWorkerWithAnalyzers.cs, src/OmniSharp.Shared/Options/RoslynExtensionsOptions.cs, tests/OmniSharp.Roslyn.CSharp.Tests/CustomRoslynAnalyzerFacts.cs, tests/TestUtility/AbstractCodeActionsTestFixture.cs, tests/TestUtility/TestHelpers.cs
Hey, this is a pull requestion to add an `AnalyzeOpenDocumentsOnly` option to `RoslynExtensionsOptions`, which `CSharpDiagnosticWorkerWithAnalyzer` uses to decided if it runs full roslyn anaylizers or just the base diagnostics provided by  `syntaxTree.GetDiagnostics()`.
The main benefit is the speed of the initial analysis of all files in the solution. For large solutions this is pretty handy, for example the roslyn solution takes 18 minutes for that first pass, vs. 1 minute with `AnalyzeOpenDocumentsOnly` set to true.
=> Add analyze open documents only

azure-pipelines.yml
Due to this breaking change we have not been publishing nightly builds - https://docs.microsoft.com/en-us/cli/azure/release-notes-azure-cli#storage
=> Pass --overwrite when pushing build artifacts to azure

build.cake
The SDK ships a newer version of System.Configuration.ConfigurationManager than we do, and it's causing load issues. This is a quick patch to fix https://github.com/OmniSharp/omnisharp-vscode/issues/5113 for now, but we'll want to remove all dlls that the SDK ships to avoid this long-term.
=> Delete System.Configuration.ConfigurationManager from deployed packages

build/Settings.props, src/OmniSharp.Abstractions/LoggingExtensions/LoggingExtensions.cs, src/OmniSharp.Abstractions/Models/v1/InlayHints/InlayHint.cs, src/OmniSharp.Abstractions/Models/v1/InlayHints/InlayHintRequest.cs, src/OmniSharp.Abstractions/Models/v1/InlayHints/InlayHintResolveRequest.cs, src/OmniSharp.Abstractions/Models/v1/InlayHints/InlayHintResponse.cs, src/OmniSharp.Abstractions/OmniSharpEndpoints.cs, src/OmniSharp.Roslyn.CSharp/Services/InlayHints/InlayHintService.cs, src/OmniSharp.Shared/Options/InlayHintsOptions.cs, src/OmniSharp.Shared/Options/RoslynExtensionsOptions.cs, tests/OmniSharp.Roslyn.CSharp.Tests/InlayHintsFacts.cs, tests/TestUtility/AssertEx.cs, tests/TestUtility/DiffUtil.cs, tests/TestUtility/TestUtility.csproj
I've based the O# api on the proposed inlay hint LSP api, https://github.com/microsoft/vscode-languageserver-node/blob/main/protocol/src/common/protocol.inlayHint.ts, which is pretty much stable now and 3.17 should be out shortly with this shape. I've also done a couple of refactors while touching code:
* Update to C# 10.
* Add some additional assert utils from roslyn, to make test results more readable and actionable.
* Add an interpolated string handler for logging, so that interpolated strings can be used in logging without a perf penalty when they're uneeded.
=> Support inlay hints

src/OmniSharp.LanguageServerProtocol/Handlers/OmniSharpSignatureHelpHandler.cs, tests/OmniSharp.Lsp.Tests/SignatureHandlerFact.cs
Fixes #2372
Continuation of #2376, but for the lsp mode only. Following what @JoeRobich said on the issue.
=> Use human readable doc in lsp's signature help

src/OmniSharp.Abstractions/Services/DotNetVersion.cs, src/OmniSharp.Abstractions/Services/IDotNetCliService.cs, src/OmniSharp.DotNetTest/TestManager.cs, src/OmniSharp.Host/Services/DotNetCliService.cs, tests/OmniSharp.Tests/DotNetCliServiceFacts.cs, tests/OmniSharp.Tests/DotNetVersionFacts.cs
Reported in https://github.com/OmniSharp/omnisharp-vscode/issues/5128
As part of creating the TestManager OmniSharp attempts to parse the .NET CLI version. When a global.json is being used by a project and the SDK version pinned in the SDK is not installed a detailed error message is output to a combination of stderr and stdout. OmniSharp would then fail to parse a valid SemanticVersion from this output and the user would be given a generic FormatException. This change adds additional parsing of the output when it is not a valid SemanticVersion to provide the user with a more meaningful error.
Prior to this change users would see the following error in their OmniSharp log:
```
[fail]: OmniSharp.Stdio.Host
************  Response (35.0185ms) ************ 
{
"Request_seq": 1013,
"Command": …
```
=> Return meaningful error when pinned SDK version is not found.

CHANGELOG.md, build/Packages.props, global.json, src/OmniSharp.Abstractions/Configuration.cs, src/OmniSharp.Http.Driver/app.config, src/OmniSharp.LanguageServerProtocol/app.config, src/OmniSharp.Roslyn.CSharp/Services/Completion/CompletionListBuilder_Async.cs, src/OmniSharp.Roslyn.CSharp/Services/Completion/CompletionListBuilder_Sync.cs, src/OmniSharp.Roslyn.CSharp/Services/Completion/CompletionService.cs, src/OmniSharp.Roslyn.CSharp/Services/Refactoring/V2/BaseCodeActionService.cs, src/OmniSharp.Roslyn.CSharp/Workers/Formatting/FormattingWorker.cs, src/OmniSharp.Roslyn/HostServicesAggregator.cs, src/OmniSharp.Roslyn/Utilities/CodeActionOptionsFactory.cs, src/OmniSharp.Roslyn/WorkspaceServices/ExtractClassWorkspaceService.cs, src/OmniSharp.Roslyn/WorkspaceServices/OmniSharpLineFormattingOptionsProvider.cs, src/OmniSharp.Stdio.Driver/app.config, tests/OmniSharp.Roslyn.CSharp.Tests/CompletionFacts.cs, tests/OmniSharp.Roslyn.CSharp.Tests/EditorConfigFacts.cs, tests/OmniSharp.Script.Tests/ScriptProjectProviderTests.cs, tests/TestUtility/TestHelpers.cs, tests/app.config
The changes are mostly around how Global Options in Roslyn is changing. We need to provide fallbacks which derive from OmniSharpOptions for LineFormatting options that are normally found in the .editorconfig.
=> Update Roslyn to 4.4.0 1.22369.1

src/OmniSharp.Roslyn.CSharp/Services/SemanticHighlight/SemanticHighlightService.cs, tests/OmniSharp.Roslyn.CSharp.Tests/SemanticHighlightFacts.cs
For files that are included in multiple projects (such as via `Compile Include` directives), we currently attempt to retrieve semantic highlights for every document. However, this means that highlight spans will have overlapping results from every project, and the service will crash. Further, we have no way of actually selecting what project to display the file as, so retrieving any but the first document doesn't serve the user. Therefore, we remove the loop, and just look through the first document found.
Fixes https://github.com/OmniSharp/omnisharp-roslyn/issues/2421.
Fixes https://github.com/OmniSharp/omnisharp-roslyn/issues/2050.
=> Only get first document's highlights

.github/workflows/build.yml
Fixes build issue brought up in https://github.com/OmniSharp/omnisharp-roslyn/pull/2424#issuecomment-1196947613
The test CI were already using these OS versions.
=> Update VMs used in build CI.

src/OmniSharp.Abstractions/Models/v2/CodeActions/CodeAction.cs, src/OmniSharp.Abstractions/Models/v2/CodeActions/CodeActionKind.cs, src/OmniSharp.LanguageServerProtocol/Handlers/OmniSharpCodeActionHandler.cs, src/OmniSharp.Roslyn.CSharp/Services/Refactoring/V2/AvailableCodeAction.cs, src/OmniSharp.Roslyn.CSharp/Services/Refactoring/V2/BaseCodeActionService.cs, src/OmniSharp.Roslyn.CSharp/Services/Refactoring/V2/GetCodeActionsService.cs, tests/OmniSharp.Cake.Tests/CodeActionsV2Facts.cs, tests/OmniSharp.Roslyn.CSharp.Tests/CodeActionsV2Facts.cs, tests/OmniSharp.Roslyn.CSharp.Tests/CodeActionsWithOptionsFacts.cs, tests/TestUtility/AbstractCodeActionsTestFixture.cs
Omnisharp-roslyn side of fixing https://github.com/OmniSharp/omnisharp-vscode/issues/5335.
=> Record whether a CodeAction is a fix or not

src/OmniSharp.Host/Services/DotNetCliService.cs
Take the first found CLI path instead of the last one (as described in _https://github.com/OmniSharp/omnisharp-roslyn/pull/2227#discussion_r728553310_)
=> Take the first found dotnet CLI path instead of the last one

src/OmniSharp.Abstractions/Models/v1/SymbolLocation.cs, src/OmniSharp.LanguageServerProtocol/Handlers/OmniSharpWorkspaceSymbolsHandler.cs, src/OmniSharp.Roslyn.CSharp/Services/Navigation/GoToDefinitionHelpers.cs, src/OmniSharp.Roslyn.CSharp/Services/Navigation/GotoDefinitionService.cs, src/OmniSharp.Roslyn.CSharp/Services/Navigation/GotoDefinitionServiceV2.cs, src/OmniSharp.Roslyn.CSharp/Services/Navigation/GotoTypeDefinitionService.cs, src/OmniSharp.Roslyn/Extensions/SolutionExtensions.cs, tests/OmniSharp.Roslyn.CSharp.Tests/FindSymbolsFacts.cs
Updates the workspace symbols requests to provide a SourceGeneratedFileInfo when the symbol is from a source generated file, so aware editors can retrieve information about the file and display it correctly, rather than showing no information.
=> Provide SourceGeneratedFileInfo for workspace symbols requests

src/OmniSharp.DotNetTest/TestFrameworks/NUnitTestFramework.cs, test-assets/test-projects/NUnitTestProject/TestProgram.cs, tests/OmniSharp.DotNetTest.Tests/RunTestFacts.cs
Fixes https://github.com/OmniSharp/omnisharp-roslyn/issues/2379.
=> Support NUnit TheoryAttribute

src/OmniSharp.Roslyn.CSharp/Helpers/LocationExtensions.cs, src/OmniSharp.Roslyn/Extensions/SolutionExtensions.cs, tests/OmniSharp.Roslyn.CSharp.Tests/FindReferencesFacts.cs
Allows find references to provide information about references in source-generated files.
=> Return generated file info for find references

build/Packages.props, src/OmniSharp.Http/Host.cs, src/OmniSharp.Http/Middleware/StopServerMiddleware.cs, src/OmniSharp.Http/OmniSharp.Http.csproj
The HTTP driver is currently using ASP.NET Core 2.2.  This reached its end of life in Dec 2019, almost 3 years ago.
This PR updates to the latest ASP.NET core version.
ASP.NET Core 3 and later do not support .NET framework, so this only applies to the build for .NET 6 (and later when supported)
Fixes #2259
=> Upgrade http driver to latest ASP.NET Core version when running in .NET 6

CHANGELOG.md, src/OmniSharp.Http/OmniSharp.Http.csproj, src/OmniSharp.Stdio/OmniSharp.Stdio.csproj, test-assets/test-projects/CakeProject/tools/packages.config
Seems we forgot to remove the TFM check on project reference for Cake after .NET 6 support was added.
=> Include Cake bits in .NET 6 builds

CHANGELOG.md, src/OmniSharp.Cake/Extensions/ResponseExtensions.cs, src/OmniSharp.Cake/Services/RequestHandlers/SemanticHighlight/SemanticHighlightHandler.cs, tests/OmniSharp.Cake.Tests/SemanticHighlightFacts.cs
This endpoint handler have been missing for a while in Cake
=> Adds V2 Highlight support to Cake

src/OmniSharp.Roslyn.CSharp/Helpers/LocationExtensions.cs, tests/OmniSharp.Lsp.Tests/ReferencesHandlerFacts.cs
**Problem:** O# sets the start/end characters of a location to 0 if the location is within a line mapping directive. This is problematic in Razor, where we're attempting to implement document highlighting for the first time and need exact start/end characters.
**Solution**: Use the original line and character locations (edit: only in Razor files). This also means we need to return the non-mapped file path.
I confirmed features that go through this call path (document highlighting, find all references, go-to-impl, etc.) still work correctly with this change in both C# and Razor files. Most features still work since many [do their own re-mapping](https://github.com/OmniSharp/omnisharp-vscode/blob/1f2d7de27a9e89d8a7303104a710a918eb699827/src/features/referenceProvider.ts#L32) behind the …
=> Don't remap line mappings in Razor files

src/OmniSharp.LanguageServerProtocol/Handlers/OmniSharpTypeDefinitionHandler.cs, src/OmniSharp.LanguageServerProtocol/LanguageServerHost.cs
Noticed this was missing as I was working on LSP support in the C# ext.
=> Add the TypeDefinitionHandler to the LSP 

src/OmniSharp.Abstractions/Models/v2/CodeFoldingBlock.cs, src/OmniSharp.LanguageServerProtocol/Handlers/OmniSharpDocumentHighlightHandler.cs, src/OmniSharp.LanguageServerProtocol/Handlers/OmniSharpDocumentOnTypeFormattingHandler.cs, src/OmniSharp.LanguageServerProtocol/Handlers/OmniSharpFoldingRangeHandler.cs, src/OmniSharp.LanguageServerProtocol/Handlers/OmniSharpSemanticTokensHandler.cs, src/OmniSharp.LanguageServerProtocol/LanguageServerHost.cs, src/OmniSharp.Roslyn.CSharp/Services/SemanticHighlight/SemanticHighlightService.cs
Discovered as part of the work to move the C# extension over to using the O# LSP.
Other missing handlers:
InlayHintsHandler - Required csharp-language-server-protocol to update with the 3.17 spec. I believe this is currently in a feature branch.
=> Add missing LSP Handlers

.github/workflows/build.yml, .github/workflows/tests-net6.yml, .github/workflows/tests.yml, azure-pipelines.yml, build.cake
The macos and linux build CI legs take longer than necessary because they are building for both platforms. Also this disables CI job for changes to changelog.md.
=> Infrastructure improvements

.vscode/tasks.json, build/Packages.props
This is needed to support intellisense in dotnet-script 1.4.0 (which was released with support for .net 7)
=> Updated dotnet-script dependencies to 1.4.0

src/OmniSharp.Roslyn.CSharp/Services/Completion/CompletionListBuilder_Sync.cs
Previously, when upgrading Roslyn to a newer version, we [disabled snippets](https://github.com/OmniSharp/omnisharp-roslyn/pull/2486/files#diff-fcd6685e91560d2c357ca740527ebe592b32bd3e59c51765ddee005f385b8d3eR49) due to duplicates in the completion list (see #2485). We did this in our async completion logic, but it turns out we need to do the same in our sync completion logic as well. This fixes issues such as `@inject [||]` not displaying C# completions in Razor files.
=> Disable snippets in synchronous completion logic

build/Packages.props
Razor insertion is broken https://github.com/OmniSharp/omnisharp-vscode/pull/5604 because they upgraded to vs threading 17.5, but O#-roslyn is shipping 17.4
=> Update MS.VS.Threading to un-break Razor

src/OmniSharp.Roslyn.CSharp/Services/Completion/CompletionListBuilder_Sync.cs, tests/OmniSharp.Roslyn.CSharp.Tests/CompletionFacts.cs
Fixes https://github.com/dotnet/vscode-csharp/issues/5801
VSCode made a change in completion somewhere between 1.78.2 and 1.79.2 where they now trigger completion automatically inside words.  This was confirmed as an intentional change here - https://github.com/microsoft/vscode/issues/185286
However, this has caused lots of bug reports on us because O# will replace the entire word (including after the cursor) if a completion is accepted, instead of just inserting the selected completion item before the cursor. 
This does the same change as we did to fix this in Roslyn LSP - we limit the range to the cursor position.  See https://github.com/dotnet/roslyn/pull/68624
Now looks like
=> Respond to vscode breaking change in 1.79.2 that triggers completion inside words

azure-pipelines.yml
Currently attempting to get in contact with the owner of the token and nuget.org permissions, but this should unblock the vscode update.
=> Bypass nuget.org publishing due to auth failures temporarily

global.json, src/OmniSharp.LanguageServerProtocol/Handlers/OmniSharpSemanticTokensHandler.cs, tests/OmniSharp.Lsp.Tests/OmniSharpSemanticTokensHandlerFacts.cs
Closes https://github.com/OmniSharp/omnisharp-roslyn/issues/2483
- Adds LSP SemanticTokensHandler tests.
=> Use core LSP TokenTypes where possible and validate token names

build.cake
Was seeing errors like `chmod: cannot access "'/home/vsts/work/1/s/artifacts/publish/OmniSharp.Stdio.Driver/linux-x64/run'": No such file or directory` in the CI build log as well as locally.
Resolves https://github.com/OmniSharp/omnisharp-roslyn/issues/2547
=> Use double quote when quoting un script path

src/OmniSharp.DotNetTest/VSTestManager.cs
When multiple .sln or .csproj files are present in the same directory as the project that tests are being run against, dotnet errors that we should specify which we want built.
=> Include the project file name when invoking `dotnet build`

src/OmniSharp.LanguageServerProtocol/Handlers/OmniSharpInlayHintHandler.cs, tests/OmniSharp.Lsp.Tests/OmniSharpInlayHintHandlerFacts.cs
this fixes #2550
the issue happens with lambdas as parameters of a function call (Though it might happen in other cases too) es `function(sp => sp.GetService<CloudAdapter>()`
this should expand to `function(|paramName:| |Type| sp => sp.GetService<CloudAdapter>()`
each hint has a field called TextEdits of type `LinePositionSpanTextChange[]?` (either is an array or is null), which tell the editor that there is an option to promote the virtual text to real text in the document, but for lambdas paramenters type this is not an option so is set to null, when the TextEdits object gets passed to a foreach loop without checking for null the LSP would crash with a null reference
```csharp
public static IEnumerable<TextEdit> ToTextEdits(LinePositionSpanTextChange[] textChanges)
{
foreach (var change …
```
=> fix #2550 inlay hints lambdas parameter type null reference exception

.github/workflows/build.yml, .github/workflows/tests-net6.yml, .github/workflows/tests.yml, Directory.Build.targets, Directory.Packages.props, azure-pipelines.yml, src/OmniSharp.MSBuild/OmniSharp.MSBuild.csproj
Same changes as #2610 just getting a new run of CI.
=> Remove NuGet.Packaging.Core, as it's an assembly that only contains forwarders 

Directory.Build.targets, Directory.Packages.props, src/OmniSharp.MSBuild/OmniSharp.MSBuild.csproj
Remove NuGet.Packaging.Core since it only contains type forwarders.
=> Remove NuGet.Packaging.Core, as it's an assembly that only contains forwarders

src/OmniSharp.Roslyn.CSharp/Services/Refactoring/V2/CachingCodeFixProviderForProjects.cs
Update CodeFixer construction to match how it is implemented in dotnet-format (see https://github.com/dotnet/format/pull/1885).
Resolves #2608
=> Fix code fix construction

azure-pipelines.yml, doc/How-Releases-Are-Made.md
```mermaid
sequenceDiagram
autonumber
Maintainer ->> GitHub: Merges PR into the `master` branch
GitHub --) OmniSharp ADO: Merge to `master` triggers pipeline
activate OmniSharp ADO
OmniSharp ADO ->> GitHub: Pulls source for omnisharp-roslyn
note over OmniSharp ADO: Calculates a build version
OmniSharp ADO ->> GitHub: Creates a draft release and `v#35;.#35;.#35;-beta.#35;` tag
deactivate OmniSharp ADO
GitHub --) OmniSharp ADO: `v*` tag creation triggers pipeline
activate OmniSharp ADO
OmniSharp ADO ->> GitHub: Pulls source for omnisharp-roslyn
note over OmniSharp ADO: Builds packages for various platforms
OmniSharp ADO ->> GitHub: Adds packages to release and unmark as draft
deactivate OmniSharp ADO
```
=> Create GitHub releases for merges into main

src/OmniSharp.Host/CommandLineApplication.cs, tests/OmniSharp.Tests/CommandLineApplicationFacts.cs, tests/TestUtility/UseCultureAttribute.cs
The option is optional and defaults to the system locale. Extensions will need to be updated to pass this along when starting O#.
resolves #2661
=> Add `--locale` commandline option

azure-pipelines.yml
Mono is not preinstalled on 24.04 images.
=> Use ubuntu 22.04 image for building release packages.

build/Settings.props
We use an old MSBuild version only as a reference package. Actual MSBuild libraries are loaded by MSBuildLocator and come from the installed MSBuild tooling.
=> NoWarn NU1903

BUILD.md, README.md, build.cake
[Build log](https://github.com/OmniSharp/omnisharp-roslyn/actions/runs/16761470084/job/47457514100?pr=2653#step:7:4297) showing the linux-bionic-arm64 packages were created.
=> Add linux-bionic-arm64 build
